bulk_aerosol_properties – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
bulk_aerosol_properties Interface
3 statements
Source File
public interface bulk_aerosol_properties
Calls
Module Procedures
private function constructor(list_idx) result(newobj)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: list_idx
Return Value type(bulk_aerosol_properties), pointer
Call graph
bulk_aerosol_properties calls constructor
constructor calls rad_aer_get_props, aero_props_init, rad_aer_get_info
rad_aer_get_props calls rad_aer_get_mam_props_by_idx, rad_aer_get_props_by_idx
rad_aer_get_mam_props_by_idx calls endrun, physprop_get
rad_aer_get_props_by_idx calls endrun, physprop_get