carma_aerosol_properties – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
carma_aerosol_properties Interface
3 statements
Source File
public interface carma_aerosol_properties
Calls
Module Procedures
private function constructor(list_idx) result(newobj)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: list_idx
Return Value type(carma_aerosol_properties), pointer
Call graph
carma_aerosol_properties calls constructor
constructor calls aero_props_init, bin_name, indexer, rad_aer_get_info_by_bin, species_type, rad_aer_get_info
bin_name calls rad_aer_get_info_by_bin
rad_aer_get_info_by_bin calls endrun
species_type calls rad_aer_get_info_by_bin_spec
rad_aer_get_info_by_bin_spec calls endrun