hygrocoreshell_aerosol_optics – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
hygrocoreshell_aerosol_optics Interface
3 statements
Source File
public interface hygrocoreshell_aerosol_optics
Calls
Module Procedures
private function constructor(aero_props, aero_state, ibin, ncol, nlev, relhum) result(newobj)
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in) :: aero_props
class(aerosol_state), intent(in) :: aero_state
integer, intent(in) :: ibin
integer, intent(in) :: ncol
integer, intent(in) :: nlev
real(kind=r8), intent(in) :: relhum(ncol,nlev)
Return Value type(hygrocoreshell_aerosol_optics), pointer
Call graph
hygrocoreshell_aerosol_optics calls constructor
constructor calls get, get_ambient_mmr, hygroscopicity, nspecies, optics_params
optics_params calls physprop_get, physprop_id