hygroscopic_aerosol_optics – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
hygroscopic_aerosol_optics Interface
3 statements
Source File
public interface hygroscopic_aerosol_optics
Calls
Module Procedures
private function constructor(aero_props, aero_state, ibin, ncols, nlevs, numrh, relhum) result(newobj)
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in) :: aero_props
class(aerosol_state), intent(in) :: aero_state
integer, intent(in) :: ibin
integer, intent(in) :: ncols
integer, intent(in) :: nlevs
integer, intent(in) :: numrh
real(kind=r8), intent(in) :: relhum(ncols,nlevs)
Return Value type(hygroscopic_aerosol_optics), pointer
Call graph
hygroscopic_aerosol_optics calls constructor
constructor calls get_ambient_mmr, optics_params
optics_params calls physprop_get, physprop_id