rad_aer_get_props – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rad_aer_get_props Interface
4 statements
Source File
public interface rad_aer_get_props
Calls
Called by
Module Procedures
private subroutine rad_aer_get_props_by_idx(list_idx, aer_idx, opticstype, sw_hygro_ext, sw_hygro_ssa, sw_hygro_asm, lw_hygro_ext, sw_nonhygro_ext, sw_nonhygro_ssa, sw_nonhygro_asm, sw_nonhygro_scat, sw_nonhygro_ascat, lw_ext, refindex_aer_sw, refindex_aer_lw, r_sw_ext, r_sw_scat, r_sw_ascat, r_lw_abs, mu, aername, density_aer, hygro_aer, dryrad_aer, dispersion_aer, num_to_mass_aer)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
integer, intent(in) :: aer_idx
character(len=ot_length), intent(out), optional :: opticstype
real(kind=r8), optional, pointer :: sw_hygro_ext(:,:)
real(kind=r8), optional, pointer :: sw_hygro_ssa(:,:)
real(kind=r8), optional, pointer :: sw_hygro_asm(:,:)
real(kind=r8), optional, pointer :: lw_hygro_ext(:,:)
real(kind=r8), optional, pointer :: sw_nonhygro_ext(:)
real(kind=r8), optional, pointer :: sw_nonhygro_ssa(:)
real(kind=r8), optional, pointer :: sw_nonhygro_asm(:)
real(kind=r8), optional, pointer :: sw_nonhygro_scat(:)
real(kind=r8), optional, pointer :: sw_nonhygro_ascat(:)
real(kind=r8), optional, pointer :: lw_ext(:)
complex(kind=r8), optional, pointer :: refindex_aer_sw(:)
complex(kind=r8), optional, pointer :: refindex_aer_lw(:)
real(kind=r8), optional, pointer :: r_sw_ext(:,:)
real(kind=r8), optional, pointer :: r_sw_scat(:,:)
real(kind=r8), optional, pointer :: r_sw_ascat(:,:)
real(kind=r8), optional, pointer :: r_lw_abs(:,:)
real(kind=r8), optional, pointer :: mu(:)
character(len=20), intent(out), optional :: aername
real(kind=r8), intent(out), optional :: density_aer
real(kind=r8), intent(out), optional :: hygro_aer
real(kind=r8), intent(out), optional :: dryrad_aer
real(kind=r8), intent(out), optional :: dispersion_aer
real(kind=r8), intent(out), optional :: num_to_mass_aer
private subroutine rad_aer_get_mam_props_by_idx(list_idx, mode_idx, spec_idx, opticstype, sw_hygro_ext, sw_hygro_ssa, sw_hygro_asm, lw_hygro_ext, sw_nonhygro_ext, sw_nonhygro_ssa, sw_nonhygro_asm, sw_nonhygro_scat, sw_nonhygro_ascat, lw_ext, refindex_aer_sw, refindex_aer_lw, r_sw_ext, r_sw_scat, r_sw_ascat, r_lw_abs, mu, aername, density_aer, hygro_aer, dryrad_aer, dispersion_aer, num_to_mass_aer, spectype)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
integer, intent(in) :: mode_idx
integer, intent(in) :: spec_idx
character(len=ot_length), intent(out), optional :: opticstype
real(kind=r8), optional, pointer :: sw_hygro_ext(:,:)
real(kind=r8), optional, pointer :: sw_hygro_ssa(:,:)
real(kind=r8), optional, pointer :: sw_hygro_asm(:,:)
real(kind=r8), optional, pointer :: lw_hygro_ext(:,:)
real(kind=r8), optional, pointer :: sw_nonhygro_ext(:)
real(kind=r8), optional, pointer :: sw_nonhygro_ssa(:)
real(kind=r8), optional, pointer :: sw_nonhygro_asm(:)
real(kind=r8), optional, pointer :: sw_nonhygro_scat(:)
real(kind=r8), optional, pointer :: sw_nonhygro_ascat(:)
real(kind=r8), optional, pointer :: lw_ext(:)
complex(kind=r8), optional, pointer :: refindex_aer_sw(:)
complex(kind=r8), optional, pointer :: refindex_aer_lw(:)
real(kind=r8), optional, pointer :: r_sw_ext(:,:)
real(kind=r8), optional, pointer :: r_sw_scat(:,:)
real(kind=r8), optional, pointer :: r_sw_ascat(:,:)
real(kind=r8), optional, pointer :: r_lw_abs(:,:)
real(kind=r8), optional, pointer :: mu(:)
character(len=20), intent(out), optional :: aername
real(kind=r8), intent(out), optional :: density_aer
real(kind=r8), intent(out), optional :: hygro_aer
real(kind=r8), intent(out), optional :: dryrad_aer
real(kind=r8), intent(out), optional :: dispersion_aer
real(kind=r8), intent(out), optional :: num_to_mass_aer
character(len=32), intent(out), optional :: spectype
Call graph
rad_aer_get_props calls rad_aer_get_mam_props_by_idx, rad_aer_get_props_by_idx
rad_aer_get_mam_props_by_idx calls endrun, physprop_get
rad_aer_get_props_by_idx calls endrun, physprop_get
constructor calls rad_aer_get_props
get calls rad_aer_get_props
soluble calls rad_aer_get_props
bulk_aerosol_properties calls constructor
hydrophilic calls soluble
rebin_bulk_fluxes calls get
species_type calls get