rad_aer_get_info – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rad_aer_get_info Interface
6 statements
Source File
private interface rad_aer_get_info
Calls
Module Procedures
private interface rad_aer_get_info()
Arguments
None
public subroutine rad_aer_get_info_by_mode(list_idx, m_idx, mode_type, num_name, num_name_cw, nspec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
integer, intent(in) :: m_idx
character(len=32), intent(out), optional :: mode_type
character(len=32), intent(out), optional :: num_name
character(len=32), intent(out), optional :: num_name_cw
integer, intent(out), optional :: nspec
public subroutine rad_aer_get_info_by_mode_spec(list_idx, m_idx, s_idx, spec_type, spec_name, spec_name_cw)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
integer, intent(in) :: m_idx
integer, intent(in) :: s_idx
character(len=32), intent(out), optional :: spec_type
character(len=32), intent(out), optional :: spec_name
character(len=32), intent(out), optional :: spec_name_cw
public subroutine rad_aer_get_info_by_spectype(list_idx, spectype, mode_idx, spec_idx)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
character(len=*), intent(in) :: spectype
integer, intent(out), optional :: mode_idx
integer, intent(out), optional :: spec_idx
Call graph
rad_aer_get_info calls rad_aer_get_info, rad_aer_get_info_by_mode, rad_aer_get_info_by_mode_spec, rad_aer_get_info_by_spectype
rad_aer_get_info_by_mode calls endrun
rad_aer_get_info_by_mode_spec calls endrun