refractive_aerosol_optics – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
refractive_aerosol_optics Interface
3 statements
Source File
public interface refractive_aerosol_optics
Calls
Module Procedures
private function constructor(aero_props, aero_state, ibin, ncol, nlev, nsw, nlw, crefwsw, crefwlw) result(newobj)
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in), target :: aero_props
class(aerosol_state), intent(in), target :: aero_state
integer, intent(in) :: ibin
integer, intent(in) :: ncol
integer, intent(in) :: nlev
integer, intent(in) :: nsw
integer, intent(in) :: nlw
complex(kind=r8), intent(in) :: crefwsw(nsw)
complex(kind=r8), intent(in) :: crefwlw(nlw)
Return Value type(refractive_aerosol_optics), pointer
Call graph
refractive_aerosol_optics calls constructor
constructor calls get, get_ambient_mmr, nspecies, get_alogsig, modal_size_parameters, optics_params, water_uptake
optics_params calls physprop_get, physprop_id