aerosol_optics_lw_bin – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
aerosol_optics_lw_bin Subroutine
45 statements
Source File
public subroutine aerosol_optics_lw_bin(aeroprops, aerostate, ibin, ncol, nlev, nswbands, nlwbands, numrh, relh, sulfwtpct, mass, crefwsw, crefwlw, geometric_radius, tau_lw_bin, absorp_bin, errmsg, errflg)
Uses
aerosol_state_mod
aerosol_optics_mod
aerosol_properties_mod
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in), target :: aeroprops
class(aerosol_state), intent(in), target :: aerostate
integer, intent(in) :: ibin
integer, intent(in) :: ncol
integer, intent(in) :: nlev
integer, intent(in) :: nswbands
integer, intent(in) :: nlwbands
integer, intent(in) :: numrh
real(kind=r8), intent(in) :: relh(:,:)
real(kind=r8), intent(in) :: sulfwtpct(:,:)
real(kind=r8), intent(in) :: mass(:,:)
complex(kind=r8), intent(in) :: crefwsw(:)
complex(kind=r8), intent(in) :: crefwlw(:)
real(kind=r8), intent(in), optional, pointer :: geometric_radius(:,:)
real(kind=r8), intent(out) :: tau_lw_bin(:,:,:)
real(kind=r8), intent(out) :: absorp_bin(:,:,:)
character(len=*), intent(out) :: errmsg
integer, intent(out) :: errflg
Calls
Variables
Type Visibility Attributes Name Initial
class(aerosol_optics), private, pointer :: aero_optics
integer, private :: icol
integer, private :: ilev
integer, private :: iwav
real(kind=r8), private :: pabs(ncol)
Source Code
  subroutine aerosol_optics_lw_bin(aeroprops, aerostate, ibin, &
                                   ncol, nlev, nswbands, nlwbands, numrh, &
                                   relh, sulfwtpct, mass, crefwsw, crefwlw, &
                                   geometric_radius, &
                                   tau_lw_bin, absorp_bin, &
                                   errmsg, errflg)
    use aerosol_properties_mod, only: aerosol_properties
    use aerosol_state_mod, only: aerosol_state
    use aerosol_optics_mod, only: aerosol_optics
    class(aerosol_properties), intent(in), target :: aeroprops
    class(aerosol_state),      intent(in), target :: aerostate
    integer,     intent(in)         :: ibin
    integer,     intent(in)         :: ncol, nlev
    integer,     intent(in)         :: nswbands
    integer,     intent(in)         :: nlwbands
    integer,     intent(in)         :: numrh
    real(r8),    intent(in)         :: relh(:, :)
    real(r8),    intent(in)         :: sulfwtpct(:, :)
    real(r8),    intent(in)         :: mass(:, :)
    complex(r8), intent(in)         :: crefwsw(:)
    complex(r8), intent(in)         :: crefwlw(:)
    real(r8),    intent(in), optional, pointer :: geometric_radius(:, :)
    real(r8),    intent(out)        :: tau_lw_bin(:, :, :)   ! (ncol,nlev,nlwbands) absorption OD
    real(r8),    intent(out)        :: absorp_bin(:, :, :)   ! (ncol,nlev,nlwbands) raw specific absorption (pabs)
    character(len=*), intent(out) :: errmsg
    integer,          intent(out) :: errflg
    class(aerosol_optics), pointer :: aero_optics
    real(r8) :: pabs(ncol)
    integer  :: iwav, ilev, icol
    errflg = 0
    errmsg = ''
    tau_lw_bin = 0._r8
    absorp_bin = 0._r8
    ! Create aerosol optics object
    aero_optics => create_aerosol_optics_object(aeroprops, aerostate, ibin, &
                                                ncol, nlev, nswbands, nlwbands, numrh, &
                                                relh, sulfwtpct, crefwsw, crefwlw, &
                                                geometric_radius)
    if (.not. associated(aero_optics)) then
      errflg = 1
      errmsg = 'unrecognized aerosol optics type, could not create object'
      return
    end if
    do iwav = 1, nlwbands
      do ilev = 1, nlev
        call aero_optics%lw_props(ncol, ilev, iwav, pabs)
        do icol = 1, ncol
          tau_lw_bin(icol, ilev, iwav) = pabs(icol)*mass(icol, ilev)
          absorp_bin(icol, ilev, iwav) = pabs(icol)
        end do
      end do
    end do
    deallocate (aero_optics)
  end subroutine aerosol_optics_lw_bin
Call graph
aerosol_optics_lw_bin calls lw_props, create_aerosol_optics_object
create_aerosol_optics_object calls optics_params
optics_params calls physprop_get, physprop_id