amb_mmr_name – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
amb_mmr_name Subroutine
11 statements
Source File
private subroutine amb_mmr_name(self, bin_ndx, species_ndx, name)
Type Bound
carma_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: species_ndx
character(len=*), intent(out) :: name
Calls
Source Code
  subroutine amb_mmr_name(self, bin_ndx, species_ndx, name)
    class(carma_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx           ! bin number
    integer, intent(in) :: species_ndx       ! species number
    character(len=*), intent(out) :: name   ! constituent name of ambient aerosol MMR
    if (species_ndx>0) then
       call rad_aer_get_info_by_bin_spec(self%list_idx_, bin_ndx, species_ndx, spec_name=name)
    else
       call rad_aer_get_info_by_bin(self%list_idx_, bin_ndx,  mmr_name=name)
    end if
  end subroutine amb_mmr_name
Call graph
amb_mmr_name calls rad_aer_get_info_by_bin, rad_aer_get_info_by_bin_spec
rad_aer_get_info_by_bin calls endrun
rad_aer_get_info_by_bin_spec calls endrun