ambient_total_bin_mmr – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
ambient_total_bin_mmr Function
18 statements
Source File
private function ambient_total_bin_mmr(self, aero_props, bin_ndx, col_ndx, lyr_ndx) result(mmr_tot)
Type Bound
carma_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: bin_ndx
integer, intent(in) :: col_ndx
integer, intent(in) :: lyr_ndx
Return Value real(kind=r8)
Calls
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: bin_name
integer, private :: ibin
integer, private :: igroup
integer, private :: nchr
integer, private :: rc
character(len=aero_name_len), private :: shortname
real(kind=r8), private :: totmmr(pcols,pver)
Source Code
  function ambient_total_bin_mmr(self, aero_props, bin_ndx, col_ndx, lyr_ndx) result(mmr_tot)
    class(carma_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    integer, intent(in) :: bin_ndx      ! bin index
    integer, intent(in) :: col_ndx      ! column index
    integer, intent(in) :: lyr_ndx      ! vertical layer index
    real(r8) :: mmr_tot                 ! mass mixing ratios totaled for all species
    real(r8) :: totmmr(pcols,pver)
    character(len=aero_name_len) :: bin_name, shortname
    integer :: igroup, ibin, rc, nchr
    call rad_aer_get_info_by_bin(self%list_idx_, bin_ndx, bin_name=bin_name)
    nchr = len_trim(bin_name)-2
    shortname = bin_name(:nchr)
    call  carma_get_group_by_name(shortname, igroup, rc)
    read(bin_name(nchr+1:),*) ibin
    call carma_get_total_mmr(self%state, igroup, ibin, totmmr, rc)
    mmr_tot = totmmr(col_ndx,lyr_ndx)
  end function ambient_total_bin_mmr
Call graph
ambient_total_bin_mmr calls carma_get_group_by_name, carma_get_total_mmr, rad_aer_get_info_by_bin
rad_aer_get_info_by_bin calls endrun