coated_frac – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
coated_frac Function
83 statements
Source File
private function coated_frac(self, bin_ndx, species_type, ncol, nlev, aero_props, radius) result(frac)
Type Bound
aerosol_state
Arguments
Type Intent Optional Attributes Name
class(aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
character(len=*), intent(in) :: species_type
integer, intent(in) :: ncol
integer, intent(in) :: nlev
class(aerosol_properties), intent(in) :: aero_props
real(kind=r8), intent(in) :: radius(:,:)
Return Value real(kind=r8), (ncol,nlev)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, pointer :: aer_mmr(:,:)
real(kind=r8), private :: alnsg
real(kind=r8), private, parameter :: dr_so4_monolayers_dust = n_so4_monolayers_dust*4.76e-10_r8
real(kind=r8), private :: fac_volsfc
integer, private :: ispc
real(kind=r8), private, parameter :: n_so4_monolayers_dust = 1.0_r8
real(kind=r8), private, pointer :: pom_mmr(:,:)
integer, private :: pom_ndx
real(kind=r8), private, pointer :: soa_mmr(:,:)
integer, private :: soa_ndx
real(kind=r8), private :: specdens
real(kind=r8), private :: specdens_pom
real(kind=r8), private :: specdens_so4
real(kind=r8), private :: specdens_soa
integer, private :: species_ndx
character(len=aero_name_len), private :: spectype
real(kind=r8), private, pointer :: sulf_mmr(:,:)
integer, private :: sulf_ndx
real(kind=r8), private :: tmp1(ncol,nlev)
real(kind=r8), private :: tmp2(ncol,nlev)
real(kind=r8), private :: vol_core(ncol,nlev)
real(kind=r8), private :: vol_shell(ncol,nlev)
Source Code
  function coated_frac(self, bin_ndx,  species_type, ncol, nlev, aero_props, radius) result(frac)
    class(aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    character(len=*), intent(in) :: species_type  ! species type
    integer, intent(in) :: ncol                   ! number of columns
    integer, intent(in) :: nlev                   ! number of vertical levels
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    real(r8), intent(in) :: radius(:,:) ! m
    real(r8) :: frac(ncol,nlev)                              ! coated fraction
    !------------coated variables--------------------
    real(r8), parameter :: n_so4_monolayers_dust = 1.0_r8 ! number of so4(+nh4) monolayers needed to coat a dust particle
    real(r8), parameter :: dr_so4_monolayers_dust = n_so4_monolayers_dust * 4.76e-10_r8
    real(r8) :: vol_shell(ncol,nlev)
    real(r8) :: vol_core(ncol,nlev)
    real(r8) :: alnsg, fac_volsfc
    real(r8) :: tmp1(ncol,nlev), tmp2(ncol,nlev)
    real(r8),pointer :: sulf_mmr(:,:)
    real(r8),pointer :: soa_mmr(:,:)
    real(r8),pointer :: pom_mmr(:,:)
    real(r8),pointer :: aer_mmr(:,:)
    integer :: sulf_ndx
    integer :: soa_ndx
    integer :: pom_ndx
    integer :: species_ndx
    real(r8) :: specdens_so4
    real(r8) :: specdens_pom
    real(r8) :: specdens_soa
    real(r8) :: specdens
    character(len=aero_name_len) :: spectype
    integer :: ispc
    frac = -huge(1._r8)
    sulf_ndx = -1
    pom_ndx = -1
    soa_ndx = -1
    species_ndx = -1
    do ispc = 1, aero_props%nspecies(bin_ndx)
       call aero_props%species_type(bin_ndx, ispc, spectype)
       select case ( trim(spectype) )
       case('sulfate')
          sulf_ndx = ispc
       case('p-organic')
          pom_ndx = ispc
       case('s-organic')
          soa_ndx = ispc
       end select
       if (spectype==species_type) then
          species_ndx = ispc
       end if
    end do
    vol_shell(:ncol,:) = 0._r8
    if (sulf_ndx>0) then
       call aero_props%get(bin_ndx, sulf_ndx, density=specdens_so4)
       call self%get_ambient_mmr(species_ndx=sulf_ndx, bin_ndx=bin_ndx, mmr=sulf_mmr)
       vol_shell(:ncol,:) = vol_shell(:ncol,:) + sulf_mmr(:ncol,:)/specdens_so4
    end if
    if (pom_ndx>0) then
       call aero_props%get(bin_ndx, pom_ndx, density=specdens_pom)
       call self%get_ambient_mmr(species_ndx=pom_ndx, bin_ndx=bin_ndx, mmr=pom_mmr)
       vol_shell(:ncol,:) = vol_shell(:ncol,:) + pom_mmr(:ncol,:)*aero_props%pom_equivso4_factor()/specdens_pom
    end if
    if (soa_ndx>0) then
       call aero_props%get(bin_ndx, soa_ndx, density=specdens_soa)
       call self%get_ambient_mmr(species_ndx=soa_ndx, bin_ndx=bin_ndx, mmr=soa_mmr)
       vol_shell(:ncol,:) = vol_shell(:ncol,:) + soa_mmr(:ncol,:)*aero_props%soa_equivso4_factor()/specdens_soa
    end if
    call aero_props%get(bin_ndx, species_ndx, density=specdens)
    call self%get_ambient_mmr(species_ndx=species_ndx, bin_ndx=bin_ndx, mmr=aer_mmr)
    vol_core(:ncol,:) = aer_mmr(:ncol,:)/specdens
    alnsg = aero_props%alogsig(bin_ndx)
    fac_volsfc = exp(2.5_r8*alnsg**2)
    tmp1(:ncol,:) = vol_shell(:ncol,:)*(radius(:ncol,:)*2._r8)*fac_volsfc
    tmp2(:ncol,:) = max(6.0_r8*dr_so4_monolayers_dust*vol_core(:ncol,:), 0.0_r8)
    where(tmp1(:ncol,:)>0._r8 .and. tmp2(:ncol,:)>0._r8)
       frac(:ncol,:) = tmp1(:ncol,:)/tmp2(:ncol,:)
    elsewhere
       frac(:ncol,:) = 0.001_r8
    end where
    where(frac(:ncol,:)>1._r8)
       frac(:ncol,:) = 1._r8
    end where
    where(frac(:ncol,:) < 0.001_r8)
       frac(:ncol,:) = 0.001_r8
    end where
  end function coated_frac
Call graph
coated_frac calls get, get_ambient_mmr, nspecies, get_alogsig, pom_equivso4_factor, soa_equivso4_factor, species_type