constructor – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
constructor Function
47 statements
Source File
private function constructor(list_idx) result(newobj)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: list_idx
Return Value type(bulk_aerosol_properties), pointer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, allocatable :: alogsig(:)
real(kind=r8), private :: dispersion_val
real(kind=r8), private, allocatable :: f1(:)
integer, private :: i
integer, private :: ierr
integer, private :: list_idx_loc
integer, private :: naero
integer, private, allocatable :: nspecies(:)
Source Code
  function constructor(list_idx) result(newobj)
    integer, optional, intent(in) :: list_idx ! radiation list index (0=climate)
    type(bulk_aerosol_properties), pointer :: newobj
    integer,allocatable :: nspecies(:)
    real(r8),allocatable :: alogsig(:)
    real(r8),allocatable :: f1(:)
    integer :: ierr, naero, i
    integer :: list_idx_loc
    real(r8) :: dispersion_val
    list_idx_loc = 0
    if (present(list_idx)) list_idx_loc = list_idx
    allocate(newobj,stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    call rad_aer_get_info(list_idx_loc, naero=naero)
    ! Here treat each aerosol as a separate bin
    allocate( nspecies(naero),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate( alogsig(naero),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate( f1(naero),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    ! Bulk aerosols have 1 chemical species in each bin
    nspecies(:) = 1
    ! Read actual dispersion (sigma_logr) from physprop files
    do i = 1, naero
       call rad_aer_get_props(list_idx_loc, i, dispersion_aer=dispersion_val)
       alogsig(i) = log(dispersion_val)
    end do
    f1(:) = 1._r8
    ! For bulk aerosols, the number of bins and total number of constituents are
    ! the same (naero) -- one constituent (species and mass) per bin.
    call newobj%initialize(nbin=naero, ncnst=naero, nspec=nspecies, nmasses=nspecies, &
                           alogsig=alogsig, f1=f1, f2=f1, ierr=ierr, list_idx=list_idx_loc)
    deallocate(nspecies)
    deallocate(alogsig)
    deallocate(f1)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
  end function constructor
Call graph
constructor calls rad_aer_get_props, aero_props_init, rad_aer_get_info
rad_aer_get_props calls rad_aer_get_mam_props_by_idx, rad_aer_get_props_by_idx
rad_aer_get_mam_props_by_idx calls endrun, physprop_get
rad_aer_get_props_by_idx calls endrun, physprop_get
bulk_aerosol_properties calls constructor