constructor – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
constructor Function
37 statements
Source File
private function constructor(aero_props, aero_state, ibin, ncol, nlev, wgtpct_in) result(newobj)
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in) :: aero_props
class(aerosol_state), intent(in) :: aero_state
integer, intent(in) :: ibin
integer, intent(in) :: ncol
integer, intent(in) :: nlev
real(kind=r8), intent(in) :: wgtpct_in(ncol,nlev)
Return Value type(hygrowghtpct_aerosol_optics), pointer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
integer, private :: ierr
integer, private :: ispec
integer, private :: k
integer, private :: nspec
real(kind=r8), private, pointer :: specmmr(:,:)
Source Code
  function constructor(aero_props, aero_state, ibin, ncol, nlev, wgtpct_in) result(newobj)
    class(aerosol_properties),intent(in) :: aero_props ! aerosol_properties object
    class(aerosol_state),intent(in) :: aero_state      ! aerosol_state object
    integer, intent(in) :: ibin   ! bin number
    integer, intent(in) :: ncol   ! number of columns
    integer, intent(in) :: nlev   ! number of levels
    real(r8),intent(in) :: wgtpct_in(ncol,nlev) ! sulfate weight percent
    type(hygrowghtpct_aerosol_optics), pointer :: newobj
    integer :: ierr, nspec
    integer :: ispec
    integer :: i,k
    real(r8), pointer :: specmmr(:,:)   ! species mass mixing ratio
    allocate(newobj, stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%totalmmr(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%wgtpct(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    ! weight percent of H2SO4/H2O solution
    newobj%wgtpct(:ncol,:nlev) = wgtpct_in(:ncol,:nlev)
    call aero_props%optics_params(ibin, wgtpct=newobj%tbl_wgtpct, nwtp=newobj%nwtp)
    nspec = aero_props%nspecies(ibin)
    newobj%totalmmr(:,:) = 0._r8
    do ispec = 1,nspec
       call aero_state%get_ambient_mmr(species_ndx=ispec,bin_ndx=ibin,mmr=specmmr)
       newobj%totalmmr(:ncol,:nlev) = newobj%totalmmr(:ncol,:nlev) + specmmr(:ncol,:nlev)
    end do
    call aero_props%optics_params(ibin,  &
         sw_hygro_ext_wtp=newobj%sw_hygro_ext_wtp, &
         sw_hygro_ssa_wtp=newobj%sw_hygro_ssa_wtp, &
         sw_hygro_asm_wtp=newobj%sw_hygro_asm_wtp, &
         lw_hygro_ext_wtp=newobj%lw_hygro_abs_wtp)
  end function constructor
Call graph
constructor calls get_ambient_mmr, nspecies, optics_params
optics_params calls physprop_get, physprop_id
hygrowghtpct_aerosol_optics calls constructor