constructor – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
constructor Function
95 statements
Source File
private function constructor(aero_props, aero_state, ibin, ncol, nlev, relhum) result(newobj)
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in) :: aero_props
class(aerosol_state), intent(in) :: aero_state
integer, intent(in) :: ibin
integer, intent(in) :: ncol
integer, intent(in) :: nlev
real(kind=r8), intent(in) :: relhum(ncol,nlev)
Return Value type(hygrocoreshell_aerosol_optics), pointer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: bcdustmmr(ncol,nlev)
real(kind=r8), private :: corebcmmr(ncol,nlev)
real(kind=r8), private :: coredustmmr(ncol,nlev)
real(kind=r8), private :: coremmr(ncol,nlev)
integer, private :: icol
integer, private :: ierr
integer, private :: ilev
integer, private :: ispec
integer, private :: nspec
real(kind=r8), private :: shellmmr(ncol,nlev)
real(kind=r8), private :: specdens
real(kind=r8), private, pointer :: specmmr(:,:)
character(len=32), private :: specmorph
character(len=32), private :: spectype
Source Code
 function constructor(aero_props, aero_state, ibin, ncol, nlev, relhum) result(newobj)
    class(aerosol_properties),intent(in) :: aero_props ! aerosol_properties object
    class(aerosol_state),intent(in) :: aero_state      ! aerosol_state object
    integer, intent(in) :: ibin   ! bin number
    integer, intent(in) :: ncol   ! number of columns
    integer, intent(in) :: nlev   ! number of levels
    real(r8),intent(in) :: relhum(ncol,nlev) ! relative humidity
    type(hygrocoreshell_aerosol_optics), pointer :: newobj
    integer :: ierr, nspec
    integer :: ilev, ispec, icol
    real(r8), pointer :: specmmr(:,:)   ! species mass mixing ratio
    real(r8) :: coremmr(ncol,nlev)
    real(r8) :: coredustmmr(ncol,nlev)
    real(r8) :: corebcmmr(ncol,nlev)
    real(r8) :: shellmmr(ncol,nlev)
    real(r8) :: bcdustmmr(ncol,nlev)
    character(len=32) :: spectype  ! species type
    character(len=32) :: specmorph
    real(r8)          :: specdens  ! species density (kg/m3)
    allocate(newobj, stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%totalmmr(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%corefrac(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%bcdust(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%kappa(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%relh(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    nspec = aero_props%nspecies(ibin)
    coremmr(:,:) = 0._r8
    coredustmmr(:,:) = 0._r8
    corebcmmr(:,:) = 0._r8
    shellmmr(:,:) = 0._r8
    do ispec = 1,nspec
       call aero_state%get_ambient_mmr(species_ndx=ispec,bin_ndx=ibin,mmr=specmmr)
       call aero_props%get(ibin, ispec, density=specdens, &
                           spectype=spectype, specmorph=specmorph)
       if (trim(specmorph) == 'core') then
          if (trim(spectype) == 'dust') then
             coredustmmr(:ncol,:nlev) = coredustmmr(:ncol,:nlev) + specmmr(:ncol,:nlev)
          end if
          if (trim(spectype) == 'black-c') then
             corebcmmr(:ncol,:nlev) = corebcmmr(:ncol,:nlev) + specmmr(:ncol,:nlev)
          end if
          coremmr(:ncol,:nlev) = coremmr(:ncol,:nlev) + specmmr(:ncol,:nlev)
       else if (trim(specmorph) == 'shell') then
          shellmmr(:ncol,:nlev) = shellmmr(:ncol,:nlev) + specmmr(:ncol,:nlev)
       else
          nullify(newobj)
          return
       end if
    end do
    newobj%totalmmr(:,:) = coremmr(:,:) + shellmmr(:,:)
    bcdustmmr(:,:) = corebcmmr(:,:) + coredustmmr(:,:)
    do ilev = 1, nlev
       do icol = 1, ncol
          if (newobj%totalmmr(icol,ilev) > 0._r8) then
             newobj%corefrac(icol,ilev) = coremmr(icol,ilev) / newobj%totalmmr(icol,ilev)
          else
             newobj%corefrac(icol,ilev) = 0._r8
          end if
          newobj%corefrac(icol,ilev) = max(0._r8, min(1.0_r8, newobj%corefrac(icol,ilev)))
          if (bcdustmmr(icol,ilev) > 0._r8) then
             newobj%bcdust(icol,ilev) = corebcmmr(icol,ilev) / bcdustmmr(icol,ilev)
          else
             newobj%bcdust(icol,ilev) = 0._r8
          end if
          newobj%bcdust(icol,ilev) = max(0._r8, min(1.0_r8, newobj%bcdust(icol,ilev)))
       end do
    end do
    call aero_state%hygroscopicity(ibin, newobj%kappa)
    call aero_props%optics_params(ibin, &
         corefrac=newobj%tbl_corefrac, kap=newobj%tbl_kap, &
         bcdust=newobj%tbl_bcdust, relh=newobj%tbl_relh, &
         nfrac=newobj%nfrac, nbcdust=newobj%nbcdust, &
         nkap=newobj%nkap, nrelh=newobj%nrelh)
    newobj%relh(:ncol,:) = relhum(:ncol,:)
    ! long wave optical properties table
    call aero_props%optics_params(ibin,  &
         sw_hygro_coreshell_ext=newobj%sw_hygro_coreshell_ext, &
         sw_hygro_coreshell_ssa=newobj%sw_hygro_coreshell_ssa, &
         sw_hygro_coreshell_asm=newobj%sw_hygro_coreshell_asm, &
         lw_hygro_coreshell_ext=newobj%lw_hygro_coreshell_abs)
  end function constructor
Call graph
constructor calls get, get_ambient_mmr, hygroscopicity, nspecies, optics_params
optics_params calls physprop_get, physprop_id
hygrocoreshell_aerosol_optics calls constructor