constructor – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
constructor Function
88 statements
Source File
private function constructor(aero_props, aero_state, ibin, ncol, nlev, nsw, nlw, crefwsw, crefwlw) result(newobj)
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in), target :: aero_props
class(aerosol_state), intent(in), target :: aero_state
integer, intent(in) :: ibin
integer, intent(in) :: ncol
integer, intent(in) :: nlev
integer, intent(in) :: nsw
integer, intent(in) :: nlw
complex(kind=r8), intent(in) :: crefwsw(nsw)
complex(kind=r8), intent(in) :: crefwlw(nlw)
Return Value type(refractive_aerosol_optics), pointer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: dgnumwet(ncol,nlev)
real(kind=r8), private :: dryvol(ncol)
integer, private :: icol
integer, private :: ierr
integer, private :: ilev
integer, private :: ispec
real(kind=r8), private :: logsigma
integer, private :: nspec
real(kind=r8), private :: qaerwat(ncol,nlev)
real(kind=r8), private, parameter :: rh2odens = 1._r8/rhoh2o
real(kind=r8), private :: specdens
real(kind=r8), private, pointer :: specmmr(:,:)
real(kind=r8), private :: vol(ncol)
Source Code
  function constructor(aero_props, aero_state, ibin, ncol, nlev, nsw, nlw, crefwsw, crefwlw) &
       result(newobj)
    class(aerosol_properties),intent(in), target :: aero_props   ! aerosol_properties object
    class(aerosol_state),intent(in), target :: aero_state        ! aerosol_state object
    integer, intent(in) :: ibin   ! bin number
    integer, intent(in) :: ncol   ! number of columns
    integer, intent(in) :: nlev   ! number of levels
    integer, intent(in) :: nsw    ! number of short wave lengths
    integer, intent(in) :: nlw    ! number of long wave lengths
    complex(r8), intent(in) :: crefwsw(nsw) ! complex refractive index for water visible
    complex(r8), intent(in) :: crefwlw(nlw) ! complex refractive index for water infrared
    type(refractive_aerosol_optics), pointer :: newobj
    integer :: ierr, icol, ilev, ispec, nspec
    real(r8) :: vol(ncol)             ! volume concentration of aerosol species (m3/kg)
    real(r8) :: dryvol(ncol)          ! volume concentration of aerosol mode (m3/kg)
    real(r8) :: specdens              ! species density (kg/m3)
    real(r8), pointer :: specmmr(:,:) ! species mass mixing ratio
    real(r8) :: logsigma              ! geometric standard deviation of number distribution
    real(r8) :: dgnumwet(ncol,nlev)   ! aerosol wet number mode diameter (m)
    real(r8) :: qaerwat(ncol,nlev)    ! aerosol water (g/g)
    real(r8), parameter :: rh2odens = 1._r8/rhoh2o
    allocate(newobj, stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    ! get mode properties
    call aero_props%optics_params(ibin, &
         refrtabsw=newobj%refrtabsw, refitabsw=newobj%refitabsw, &
         refrtablw=newobj%refrtablw, refitablw=newobj%refitablw,&
         extpsw=newobj%extpsw, abspsw=newobj%abspsw, asmpsw=newobj%asmpsw, &
         absplw=newobj%absplw, ncoef=newobj%ncoef, prefr=newobj%prefr, prefi=newobj%prefi)
    allocate(newobj%watervol(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%wetvol(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%cheb(newobj%ncoef,ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%radsurf(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%logradsurf(ncol,nlev),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%crefwlw(nlw),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    newobj%crefwlw(:) = crefwlw(:)
    allocate(newobj%crefwsw(nsw),stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    newobj%crefwsw(:) = crefwsw(:)
    call aero_state%water_uptake(aero_props, ibin,  ncol, nlev, dgnumwet, qaerwat)
    nspec = aero_props%nspecies(ibin)
    logsigma=aero_props%alogsig(ibin)
    ! calc size parameter for all columns
    call modal_size_parameters(newobj%ncoef, ncol, nlev, logsigma, dgnumwet, &
                               newobj%radsurf, newobj%logradsurf, newobj%cheb)
    do ilev = 1, nlev
       dryvol(:ncol) = 0._r8
       do ispec = 1, nspec
          call aero_state%get_ambient_mmr(species_ndx=ispec,bin_ndx=ibin,mmr=specmmr)
          call aero_props%get(ibin, ispec, density=specdens)
          do icol = 1, ncol
             vol(icol) = specmmr(icol,ilev)/specdens
             dryvol(icol) = dryvol(icol) + vol(icol)
             newobj%watervol(icol,ilev) = qaerwat(icol,ilev)*rh2odens
             newobj%wetvol(icol,ilev) = newobj%watervol(icol,ilev) + dryvol(icol)
             if (newobj%watervol(icol,ilev) < 0._r8) then
                newobj%watervol(icol,ilev) = 0._r8
                newobj%wetvol(icol,ilev) = dryvol(icol)
             end if
          end do
       end do
    end do
    newobj%aero_state => aero_state
    newobj%aero_props => aero_props
    newobj%ibin = ibin
  end function constructor
Call graph
constructor calls get, get_ambient_mmr, nspecies, get_alogsig, modal_size_parameters, optics_params, water_uptake
optics_params calls physprop_get, physprop_id
refractive_aerosol_optics calls constructor