constructor – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
constructor Function
30 statements
Source File
private function constructor(aero_props, aero_state, ibin, ncols, nlevs, numrh, relhum) result(newobj)
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in) :: aero_props
class(aerosol_state), intent(in) :: aero_state
integer, intent(in) :: ibin
integer, intent(in) :: ncols
integer, intent(in) :: nlevs
integer, intent(in) :: numrh
real(kind=r8), intent(in) :: relhum(ncols,nlevs)
Return Value type(hygro_aerosol_optics), pointer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: ierr
real(kind=r8), private :: rhtrunc(ncols,nlevs)
Source Code
  function constructor(aero_props, aero_state, ibin, ncols, nlevs, numrh, relhum) &
                result(newobj)
    class(aerosol_properties),intent(in) :: aero_props   ! aerosol_properties object
    class(aerosol_state),     intent(in) :: aero_state      ! aerosol_state object
    integer, intent(in) :: ibin   ! bin number
    integer, intent(in) :: ncols, nlevs, numrh
    real(r8),intent(in) :: relhum(ncols,nlevs)
    type(hygro_aerosol_optics), pointer :: newobj
    real(r8) :: rhtrunc(ncols,nlevs)
    integer :: ierr
    allocate(newobj, stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%wrh(ncols,nlevs), stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
    allocate(newobj%krh(ncols,nlevs), stat=ierr)
    if (ierr/=0) then
       nullify(newobj)
       return
    end if
! NOTE should try to use table_interp_mod utility !!!
    rhtrunc(1:ncols,1:nlevs)  = min(relhum(1:ncols,1:nlevs),1._r8)
    newobj%krh(1:ncols,1:nlevs) = min(floor( rhtrunc(1:ncols,1:nlevs) * numrh ) + 1, numrh - 1)  ! index into rh mesh
    newobj%wrh(1:ncols,1:nlevs) = rhtrunc(1:ncols,1:nlevs) * numrh - newobj%krh(1:ncols,1:nlevs) ! (-) weighting on left side values
    ! optical properties tables
    call aero_props%optics_params(ibin, &
         sw_hygroscopic_ext=newobj%ext_sw, &
         sw_hygroscopic_ssa=newobj%ssa_sw, &
         sw_hygroscopic_asm=newobj%asm_sw, &
         lw_insoluble_ext=newobj%abs_lw )
    call aero_state%get_ambient_mmr(species_ndx=1, bin_ndx=ibin, mmr=newobj%mmr)
  end function constructor
Call graph
constructor calls get_ambient_mmr, optics_params
optics_params calls physprop_get, physprop_id
hygro_aerosol_optics calls constructor