constructor – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
constructor Function
230 statements
Source File
private function constructor(list_idx) result(newobj)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: list_idx
Return Value type(modal_aerosol_properties), pointer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, allocatable :: alogsig(:)
real(kind=r8), private, allocatable :: dgnum_arr(:)
real(kind=r8), private :: dgnum_val
real(kind=r8), private, allocatable :: dgnumhi_arr(:)
real(kind=r8), private :: dgnumhi_val
real(kind=r8), private, allocatable :: dgnumlo_arr(:)
real(kind=r8), private :: dgnumlo_val
real(kind=r8), private, allocatable :: f1(:)
real(kind=r8), private, allocatable :: f2(:)
integer, private :: ierr
integer, private :: itmp
integer, private :: l
integer, private :: list_idx_loc
integer, private :: m
integer, private :: mm
integer, private :: nbc
integer, private :: ncnst_tot
integer, private :: nmodes
integer, private :: npoa
integer, private :: nsoa
integer, private, allocatable :: nspecies(:)
real(kind=r8), private, allocatable :: rhcrystal_arr(:)
real(kind=r8), private :: rhcrystal_val
real(kind=r8), private, allocatable :: rhdeliques_arr(:)
real(kind=r8), private :: rhdeliques_val
real(kind=r8), private, allocatable :: sigmag(:)
character(len=aero_name_len), private :: spectype
Source Code
  function constructor(list_idx) result(newobj)
    integer, optional, intent(in) :: list_idx ! radiation list index (0=climate)
    type(modal_aerosol_properties), pointer :: newobj
    integer :: l, m, nmodes, ncnst_tot, mm, itmp
    integer :: list_idx_loc
    real(r8) :: dgnumlo_val
    real(r8) :: dgnumhi_val
    real(r8) :: dgnum_val
    real(r8) :: rhcrystal_val, rhdeliques_val
    integer,allocatable :: nspecies(:)
    real(r8),allocatable :: sigmag(:)
    real(r8),allocatable :: alogsig(:)
    real(r8),allocatable :: f1(:)
    real(r8),allocatable :: f2(:)
    real(r8),allocatable :: dgnum_arr(:)
    real(r8),allocatable :: dgnumhi_arr(:)
    real(r8),allocatable :: dgnumlo_arr(:)
    real(r8),allocatable :: rhcrystal_arr(:)
    real(r8),allocatable :: rhdeliques_arr(:)
    integer :: ierr
    character(len=aero_name_len) :: spectype
    integer :: npoa, nsoa, nbc
    list_idx_loc = 0
    if (present(list_idx)) list_idx_loc = list_idx
    allocate(newobj,stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    call rad_aer_get_info(list_idx_loc, nmodes=nmodes)
    allocate(nspecies(nmodes),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(alogsig(nmodes),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate( f1(nmodes),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate( f2(nmodes),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(sigmag(nmodes),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%exp45logsig_(nmodes),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%voltonumblo_(nmodes),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%voltonumbhi_(nmodes),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(dgnum_arr(nmodes),dgnumhi_arr(nmodes),dgnumlo_arr(nmodes), &
             rhcrystal_arr(nmodes),rhdeliques_arr(nmodes),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%mode_size_order_(nmodes),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    ncnst_tot = 0
    do m = 1, nmodes
       call rad_aer_get_info(list_idx_loc, m, nspec=nspecies(m))
       ncnst_tot =  ncnst_tot + nspecies(m) + 1
       call rad_aer_get_mode_props(list_idx_loc, m, sigmag=sigmag(m), &
                                    dgnum=dgnum_val, dgnumhi=dgnumhi_val, dgnumlo=dgnumlo_val, &
                                    rhcrystal=rhcrystal_val, rhdeliques=rhdeliques_val)
       dgnum_arr(m) = dgnum_val
       dgnumhi_arr(m) = dgnumhi_val
       dgnumlo_arr(m) = dgnumlo_val
       rhcrystal_arr(m) = rhcrystal_val
       rhdeliques_arr(m) = rhdeliques_val
       alogsig(m) = log(sigmag(m))
       newobj%exp45logsig_(m) = exp(4.5_r8*alogsig(m)*alogsig(m))
       f1(m) = 0.5_r8*exp(2.5_r8*alogsig(m)*alogsig(m))
       f2(m) = 1._r8 + 0.25_r8*alogsig(m)
       newobj%voltonumblo_(m) = 1._r8 / ( (pi/6._r8)* &
            (dgnumlo_val**3._r8)*exp(4.5_r8*alogsig(m)**2._r8) )
       newobj%voltonumbhi_(m) = 1._r8 / ( (pi/6._r8)* &
            (dgnumhi_val**3._r8)*exp(4.5_r8*alogsig(m)**2._r8) )
    end do
    ! compute mode_size_order_: indices sorted by dgnum_ descending (largest first)
    do m = 1, nmodes
       newobj%mode_size_order_(m) = m
    end do
    do m = 1, nmodes-1
       do l = m+1, nmodes
          if (dgnum_arr(newobj%mode_size_order_(l)) > dgnum_arr(newobj%mode_size_order_(m))) then
             itmp = newobj%mode_size_order_(m)
             newobj%mode_size_order_(m) = newobj%mode_size_order_(l)
             newobj%mode_size_order_(l) = itmp
          end if
       end do
    end do
    call newobj%initialize(nmodes,ncnst_tot,nspecies,nspecies,alogsig,f1,f2,ierr,list_idx_loc, &
                           dgnum=dgnum_arr,dgnumhi=dgnumhi_arr,dgnumlo=dgnumlo_arr, &
                           rhcrystal=rhcrystal_arr,rhdeliques=rhdeliques_arr)
    npoa = 0
    nsoa = 0
    nbc = 0
    m = 1
    do l = 1,newobj%nspecies(m)
       mm = newobj%indexer(m,l)
       call newobj%species_type(m, l, spectype)
       select case ( trim(spectype) )
       case('p-organic')
          npoa = npoa + 1
       case('s-organic')
          nsoa = nsoa + 1
       case('black-c')
          nbc = nbc + 1
       end select
    end do
    newobj%num_soa_ = nsoa
    newobj%num_poa_ = npoa
    newobj%num_bc_ = nbc
    allocate(newobj%sulfate_mode_ndxs_(newobj%nbins()),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%dust_mode_ndxs_(newobj%nbins()),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%ssalt_mode_ndxs_(newobj%nbins()),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%ammon_mode_ndxs_(newobj%nbins()),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%nitrate_mode_ndxs_(newobj%nbins()),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%msa_mode_ndxs_(newobj%nbins()),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    newobj%sulfate_mode_ndxs_ = 0
    newobj%dust_mode_ndxs_ = 0
    newobj%ssalt_mode_ndxs_ = 0
    newobj%ammon_mode_ndxs_ = 0
    newobj%nitrate_mode_ndxs_ = 0
    newobj%msa_mode_ndxs_ = 0
    allocate(newobj%porganic_mode_ndxs_(newobj%nbins(),npoa),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%sorganic_mode_ndxs_(newobj%nbins(),nsoa),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(newobj%bcarbon_mode_ndxs_(newobj%nbins(),nbc),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    newobj%porganic_mode_ndxs_ = 0._r8
    newobj%sorganic_mode_ndxs_ = 0._r8
    newobj%bcarbon_mode_ndxs_ = 0._r8
    do m = 1,newobj%nbins()
       npoa = 0
       nsoa = 0
       nbc = 0
       do l = 1,newobj%nspecies(m)
          mm = newobj%indexer(m,l)
          call newobj%species_type(m, l, spectype)
          select case ( trim(spectype) )
          case('sulfate')
             newobj%sulfate_mode_ndxs_(m) = mm
          case('dust')
             newobj%dust_mode_ndxs_(m) = mm
          case('nitrate')
             newobj%nitrate_mode_ndxs_(m) = mm
          case('ammonium')
             newobj%ammon_mode_ndxs_(m) = mm
          case('seasalt')
             newobj%ssalt_mode_ndxs_(m) = mm
          case('msa')
             newobj%msa_mode_ndxs_(m) = mm
          case('p-organic')
             npoa = npoa + 1
             newobj%porganic_mode_ndxs_(m,npoa)  = mm
          case('s-organic')
             nsoa = nsoa + 1
             newobj%sorganic_mode_ndxs_(m,nsoa)  = mm
          case('black-c')
             nbc = nbc + 1
             newobj%bcarbon_mode_ndxs_(m,nbc)  = mm
          end select
       end do
    end do
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    deallocate(nspecies)
    deallocate(alogsig)
    deallocate(sigmag)
    deallocate(f1)
    deallocate(f2)
    deallocate(dgnum_arr)
    deallocate(dgnumhi_arr)
    deallocate(dgnumlo_arr)
    deallocate(rhcrystal_arr)
    deallocate(rhdeliques_arr)
  end function constructor
Call graph
constructor calls aero_props_init, get_nbins, indexer, rad_aer_get_mode_props, species_type, rad_aer_get_info
rad_aer_get_mode_props calls endrun, physprop_get
species_type calls rad_aer_get_info
modal_aerosol_properties calls constructor