constructor – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
constructor Function
151 statements
Source File
private function constructor(list_idx) result(newobj)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: list_idx
Return Value type(carma_aerosol_properties), pointer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, allocatable :: alogsig(:)
character(len=32), private :: bin_name
character(len=32), private :: bin_name_l
real(kind=r8), private, allocatable :: f1(:)
real(kind=r8), private, allocatable :: f2(:)
integer, private, pointer :: ibl(:)
integer, private :: ierr
integer, private :: ii
integer, private :: imx
integer, private, allocatable :: imx_bl(:)
integer, private :: imx_mmr
integer, private, allocatable :: imx_mmr_bl(:)
integer, private :: imx_num
integer, private, allocatable :: imx_num_bl(:)
integer, private :: ipr
integer, private :: ipr_mmr
integer, private :: ipr_num
integer, private :: l
integer, private :: list_idx_loc
integer, private :: m
integer, private :: nbins
integer, private :: ncnst_tot
integer, private, allocatable :: nmasses(:)
integer, private, allocatable :: nspecies(:)
character(len=32), private :: spectype
Source Code
  function constructor(list_idx) result(newobj)
    integer, optional, intent(in) :: list_idx ! radiation list index (0=climate)
    type(carma_aerosol_properties), pointer :: newobj
    integer :: l, m, nbins, ncnst_tot
    integer :: list_idx_loc
    integer,allocatable :: nspecies(:)
    integer,allocatable :: nmasses(:)
    real(r8),allocatable :: alogsig(:)
    real(r8),allocatable :: f1(:)
    real(r8),allocatable :: f2(:)
    integer :: ierr
    integer, pointer :: ibl(:)
    integer :: ii, imx, imx_num, imx_mmr, ipr, ipr_num, ipr_mmr
    character(len=32) :: spectype
    character(len=32) :: bin_name
    character(len=32) :: bin_name_l    ! bin name of the larger bin
    integer, allocatable :: imx_bl(:)     ! index used to map pure sulfate bin to mixed sulfate bin
    integer, allocatable :: imx_mmr_bl(:) ! index used to map pure sulfate bin to mixed sulfate bin for mmr
    integer, allocatable :: imx_num_bl(:) ! index used to map pure sulfate bin to mixed sulfate bin for num
    list_idx_loc = 0
    if (present(list_idx)) list_idx_loc = list_idx
    allocate(newobj,stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    call rad_aer_get_info( list_idx_loc, nbins=nbins)
    allocate( nspecies(nbins),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate( nmasses(nbins),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate( alogsig(nbins),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate( f1(nbins),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate( f2(nbins),stat=ierr )
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    ncnst_tot = 0
    do m = 1, nbins
       call rad_aer_get_info_by_bin(list_idx_loc, m, nspec=nspecies(m))
       ncnst_tot = ncnst_tot + nspecies(m) + 1
       nmasses(m) = nspecies(m)
    end do
    alogsig(:) = log(2._r8)
    f1 = 1._r8
    f2 = 1._r8
    call newobj%initialize(nbins,ncnst_tot,nspecies,nmasses,alogsig,f1,f2,ierr,list_idx_loc)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    deallocate(nspecies)
    deallocate(nmasses)
    deallocate(alogsig)
    deallocate(f1)
    deallocate(f2)
    allocate(newobj%ibl(ncnst_tot),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    ibl => newobj%ibl
    ibl = -1
    allocate(imx_num_bl(nbins),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(imx_mmr_bl(nbins),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    allocate(imx_bl(nbins),stat=ierr)
    if( ierr /= 0 ) then
       nullify(newobj)
       return
    end if
    imx = 0
    imx_mmr = 0
    imx_num = 0
    ipr = 0
    ipr_mmr = 0
    ipr_num = 0
    do m = 1,nbins
       bin_name = newobj%bin_name(m)
       bin_name_l = ' '
       if (m<nbins) then
          bin_name_l = newobj%bin_name(m+1)
       end if
       do l = 0,newobj%nspecies(m)
          ii = newobj%indexer(m,l)
          ibl(ii) = ii
          ! derive index  array for larger bin, for evaporation into larger bi
          if (l>0 .and. l<=newobj%nspecies(m)) then
             call newobj%species_type(m,l,spectype)
          else
             spectype = 'other'
          end if
          ! identification is required for pure and mixed aerosols, mixed aeroosols are moved to
          ! larger bin, pure aerosols are moved to mixed sulfate
          if (index(bin_name,'MXAER')>0 .and. index(bin_name_l,'MXAER')>0) then
             ! for mixed aerosols
             ! find larger bin
             ibl(ii) = newobj%indexer(m+1,l)
             ! define mixed aerosol sulfate index to be used for pure sulfate only
             if (trim(spectype) == 'sulfate') then
                imx = imx + 1
                imx_bl(imx) = ibl(ii)
             end if
             if (l == newobj%nspecies(m)+1) then !  only for mmr
                imx_mmr = imx_mmr + 1
                ibl(ii) = newobj%indexer(m+1,l)
                imx_mmr_bl(imx_mmr) = ibl(ii)
             end if
             if (l == 0) then !  only for num
                imx_num = imx_num + 1
                ibl(ii) =  newobj%indexer(m+1,l)
                imx_num_bl(imx_num) = ibl(ii)
             end if
          end if ! MXAER
          if (index(bin_name,'PRSUL')>0 .and. index(bin_name_l,'PRSUL')>0) then
             ! pure sulfate bins
             if (trim(spectype) == 'sulfate') then
                ipr = ipr +1
                ibl(ii) = imx_bl(ipr)
             end if
             if (l == newobj%nspecies(m)+1) then ! only for mmr reset counter to only go from 1-20 bins
                ipr_mmr = ipr_mmr + 1
                ibl(ii) = imx_mmr_bl(ipr_mmr)
             end if
             if (l == 0 ) then ! only for num reset counter to only go from 1-20 bins
                ipr_num = ipr_num + 1
                ibl(ii) = imx_num_bl(ipr_num)
             end if
          end if
          if (ibl(ii).eq.0) then
             ibl(ii) = ii
          end if
       end do
    end do
    deallocate(imx_mmr_bl, imx_num_bl, imx_bl)
  end function constructor
Call graph
constructor calls aero_props_init, bin_name, indexer, rad_aer_get_info_by_bin, species_type, rad_aer_get_info
bin_name calls rad_aer_get_info_by_bin
rad_aer_get_info_by_bin calls endrun
species_type calls rad_aer_get_info_by_bin_spec
rad_aer_get_info_by_bin_spec calls endrun
carma_aerosol_properties calls constructor