convcld_actfrac – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
convcld_actfrac Function
61 statements
Source File
private function convcld_actfrac(self, aero_props, ibin, ispc, ncol, nlev) result(frac)
Uses
aerosol_properties_mod
Type Bound
modal_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: ibin
integer, intent(in) :: ispc
integer, intent(in) :: ncol
integer, intent(in) :: nlev
Return Value real(kind=r8), (ncol,nlev)
Calls
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: bin_type
real(kind=r8), private, pointer :: dust_mmr(:,:)
integer, private :: dust_ndx
real(kind=r8), private :: f_act_conv_coarse(ncol,nlev)
real(kind=r8), private :: f_act_conv_coarse_dust
real(kind=r8), private :: f_act_conv_coarse_nacl
integer, private :: i
integer, private :: k
integer, private :: l
real(kind=r8), private, pointer :: nacl_mmr(:,:)
integer, private :: nacl_ndx
character(len=aero_name_len), private :: spectype
real(kind=r8), private :: tmpdust
real(kind=r8), private :: tmpnacl
Source Code
  function convcld_actfrac(self, aero_props, ibin, ispc, ncol, nlev) result(frac)
    use aerosol_properties_mod, only: aero_name_len
    class(modal_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    integer, intent(in) :: ibin   ! bin index
    integer, intent(in) :: ispc   ! species index
    integer, intent(in) :: ncol   ! number of columns
    integer, intent(in) :: nlev   ! number of vertical levels
    real(r8) :: frac(ncol,nlev)
    real(r8) :: f_act_conv_coarse(ncol,nlev)
    real(r8) :: f_act_conv_coarse_dust, f_act_conv_coarse_nacl
    real(r8) :: tmpdust, tmpnacl
    real(r8), pointer :: dust_mmr(:,:), nacl_mmr(:,:)
    integer :: dust_ndx, nacl_ndx
    integer :: i,k,l
    character(len=aero_name_len) :: bin_type, spectype
    bin_type = aero_props%bin_name(ibin)
    f_act_conv_coarse(:,:) = 0.60_r8
    f_act_conv_coarse_dust = 0.40_r8
    f_act_conv_coarse_nacl = 0.80_r8
    if (trim(bin_type) == 'coarse') then
       ! find dust and seasalt species indices in the coarse mode
       dust_ndx = -1
       nacl_ndx = -1
       do l = 1, aero_props%nspecies(ibin)
          call aero_props%species_type(ibin, l, spectype)
          if (trim(spectype) == 'dust') dust_ndx = l
          if (trim(spectype) == 'seasalt') nacl_ndx = l
       end do
       if ((dust_ndx > 0) .and. (nacl_ndx > 0)) then
          call self%get_ambient_mmr(species_ndx=dust_ndx, bin_ndx=ibin, mmr=dust_mmr)
          call self%get_ambient_mmr(species_ndx=nacl_ndx, bin_ndx=ibin, mmr=nacl_mmr)
          do k = 1, nlev
             do i = 1, ncol
                tmpdust = max( 0.0_r8, dust_mmr(i,k) )
                tmpnacl = max( 0.0_r8, nacl_mmr(i,k) )
                if ((tmpdust+tmpnacl) > 1.0e-30_r8) then
                   f_act_conv_coarse(i,k) = (f_act_conv_coarse_dust*tmpdust &
                        + f_act_conv_coarse_nacl*tmpnacl)/(tmpdust+tmpnacl)
                end if
             end do
          end do
       end if
    end if
    if (trim(bin_type) == 'primary_carbon') then
       frac = 0.0_r8
    else if ((trim(bin_type) == 'fine_dust') .or. (trim(bin_type) == 'coarse_dust')) then
       frac = 0.4_r8
    else
       frac = 0.8_r8
    end if
    ! set f_act_conv for interstitial (lphase=1) coarse mode species
    ! for the convective in-cloud, we conceptually treat the coarse dust and seasalt
    ! as being externally mixed, and apply f_act_conv = f_act_conv_coarse_dust/nacl to dust/seasalt
    ! number and sulfate are conceptually partitioned to the dust and seasalt
    ! on a mass basis, so the f_act_conv for number and sulfate are
    ! mass-weighted averages of the values used for dust/seasalt
    if (trim(bin_type) == 'coarse') then
       frac = f_act_conv_coarse
       if (ispc>0) then
          call aero_props%species_type(ibin, ispc, spectype)
          if (trim(spectype) == 'dust') then
             frac = f_act_conv_coarse_dust
          else if (trim(spectype) == 'seasalt') then
             frac = f_act_conv_coarse_nacl
          end if
       end if
    end if
  end function convcld_actfrac
Call graph
convcld_actfrac calls bin_name, nspecies, get_ambient_mmr, species_type
get_ambient_mmr calls rad_cnst_get_aer_mmr