create_aerosol_optics_object – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
create_aerosol_optics_object Function
50 statements
Source File
public function create_aerosol_optics_object(aeroprops, aerostate, ibin, ncol, nlev, nswbands, nlwbands, numrh, relh, sulfwtpct, crefwsw, crefwlw, geometric_radius) result(aero_optics)
Uses
aerosol_optics_mod
hygroscopic_aerosol_optics_mod
phys_prop
aerosol_properties_mod
volcrad_aerosol_optics_mod
hygrocoreshell_aerosol_optics_mod
aerosol_state_mod
refractive_aerosol_optics_mod
insoluble_aerosol_optics_mod
hygrowghtpct_aerosol_optics_mod
hygro_aerosol_optics_mod
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in), target :: aeroprops
class(aerosol_state), intent(in), target :: aerostate
integer, intent(in) :: ibin
integer, intent(in) :: ncol
integer, intent(in) :: nlev
integer, intent(in) :: nswbands
integer, intent(in) :: nlwbands
integer, intent(in) :: numrh
real(kind=r8), intent(in) :: relh(:,:)
real(kind=r8), intent(in) :: sulfwtpct(:,:)
complex(kind=r8), intent(in) :: crefwsw(:)
complex(kind=r8), intent(in) :: crefwlw(:)
real(kind=r8), intent(in), optional, pointer :: geometric_radius(:,:)
Return Value class(aerosol_optics), pointer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=ot_length), private :: opticstype
Source Code
  function create_aerosol_optics_object(aeroprops, aerostate, ibin, &
                                        ncol, nlev, nswbands, nlwbands, numrh, &
                                        relh, sulfwtpct, crefwsw, crefwlw, &
                                        geometric_radius) result(aero_optics)
    use phys_prop, only: ot_length
    use aerosol_properties_mod, only: aerosol_properties
    use aerosol_state_mod, only: aerosol_state
    use aerosol_optics_mod, only: aerosol_optics
    use refractive_aerosol_optics_mod, only: refractive_aerosol_optics
    use hygrocoreshell_aerosol_optics_mod, only: hygrocoreshell_aerosol_optics
    use hygrowghtpct_aerosol_optics_mod, only: hygrowghtpct_aerosol_optics
    use hygro_aerosol_optics_mod, only: hygro_aerosol_optics
    use hygroscopic_aerosol_optics_mod, only: hygroscopic_aerosol_optics
    use insoluble_aerosol_optics_mod, only: insoluble_aerosol_optics
    use volcrad_aerosol_optics_mod, only: volcrad_aerosol_optics
    class(aerosol_properties), intent(in), target :: aeroprops
    class(aerosol_state),      intent(in), target :: aerostate
    integer,     intent(in)                       :: ibin
    integer,     intent(in)                       :: ncol
    integer,     intent(in)                       :: nlev
    integer,     intent(in)                       :: nswbands
    integer,     intent(in)                       :: nlwbands
    integer,     intent(in)                       :: numrh
    real(r8),    intent(in)                       :: relh(:, :)
    real(r8),    intent(in)                       :: sulfwtpct(:, :)
    complex(r8), intent(in)                       :: crefwsw(:)
    complex(r8), intent(in)                       :: crefwlw(:)
    real(r8),    intent(in), optional, pointer    :: geometric_radius(:, :)
    class(aerosol_optics), pointer :: aero_optics
    character(len=ot_length) :: opticstype
    nullify (aero_optics)
    call aeroprops%optics_params(bin_ndx=ibin, opticstype=opticstype)
    select case (trim(opticstype))
    case ('modal') ! refractive method
      aero_optics => refractive_aerosol_optics(aeroprops, aerostate, ibin, &
                                               ncol, nlev, nswbands, nlwbands, crefwsw, crefwlw)
    case ('hygroscopic_coreshell')
      aero_optics => hygrocoreshell_aerosol_optics(aeroprops, aerostate, &
                                                   ibin, ncol, nlev, relh)
    case ('hygroscopic_wtp')
      aero_optics => hygrowghtpct_aerosol_optics(aeroprops, aerostate, &
                                                 ibin, ncol, nlev, sulfwtpct)
    case ('hygro')
      ! Short-wave hygroscopic aerosol, Long-wave non-hygroscopic
      ! aerosol optical properties
      aero_optics => hygro_aerosol_optics(aeroprops, aerostate, &
                                          ibin, ncol, nlev, numrh, relh)
    case ('hygroscopic')
      ! Short-wave and long-wave hygroscopic aerosol properties
      aero_optics => hygroscopic_aerosol_optics(aeroprops, aerostate, ibin, &
                                                ncol, nlev, numrh, relh)
    case ('nonhygro', 'insoluble')
      aero_optics => insoluble_aerosol_optics(aeroprops, aerostate, ibin)
    case ('volcanic_radius', 'volcanic_radius1', 'volcanic_radius2', 'volcanic_radius3', 'volcanic_radius5')
      if (present(geometric_radius)) then
        if (associated(geometric_radius)) then
          aero_optics => volcrad_aerosol_optics(aeroprops, aerostate, &
                                                ibin, ncol, nlev, geometric_radius)
        end if
      end if
    end select
  end function create_aerosol_optics_object
Call graph
create_aerosol_optics_object calls optics_params
optics_params calls physprop_get, physprop_id
aerosol_optics_lw_bin calls create_aerosol_optics_object
aerosol_optics_sw_bin calls create_aerosol_optics_object