dry_volume – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
dry_volume Function
13 statements
Source File
public function dry_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
Type Bound
bulk_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(bulk_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: bin_idx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
Return Value real(kind=r8), (ncol,nlev)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), public :: dens
real(kind=r8), public, pointer :: mmr(:,:)
Source Code
  function dry_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
    class(bulk_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props
    integer, intent(in) :: bin_idx   ! bin number
    integer, intent(in) :: ncol      ! number of columns
    integer, intent(in) :: nlev      ! number of levels
    real(r8) :: vol(ncol,nlev)       ! m3/kg
    real(r8), pointer :: mmr(:,:)    ! kg/kg
    real(r8) :: dens                 ! kg/m3
    call aero_props%get(bin_idx, 1, density=dens)
    call self%get_ambient_mmr(species_ndx=1, bin_ndx=bin_idx, mmr=mmr)
    vol(:ncol,:nlev) = mmr(:ncol,:nlev)/dens
  end function dry_volume
Call graph
dry_volume calls get, get_ambient_mmr
get_ambient_mmr calls rad_cnst_get_aer_mmr
wet_volume calls dry_volume