get – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
get Subroutine
46 statements
Source File
private subroutine get(self, bin_ndx, species_ndx, density, hygro, spectype, specname, specmorph, refindex_sw, refindex_lw, num_to_mass_aer, dryrad)
Uses
cam_abortutils
Type Bound
carma_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: species_ndx
real(kind=r8), intent(out), optional :: density
real(kind=r8), intent(out), optional :: hygro
character(len=*), intent(out), optional :: spectype
character(len=*), intent(out), optional :: specname
character(len=*), intent(out), optional :: specmorph
complex(kind=r8), intent(out), optional, pointer :: refindex_sw(:)
complex(kind=r8), intent(out), optional, pointer :: refindex_lw(:)
real(kind=r8), intent(out), optional :: num_to_mass_aer
real(kind=r8), intent(out), optional :: dryrad
Calls
Called by
Source Code
  subroutine get(self, bin_ndx, species_ndx, density, hygro, &
                 spectype, specname, specmorph, refindex_sw, refindex_lw, num_to_mass_aer, &
                 dryrad)
    use cam_abortutils, only: endrun
    class(carma_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx             ! bin index
    integer, intent(in) :: species_ndx         ! species index
    real(r8), optional, intent(out) :: density ! density (kg/m3)
    real(r8), optional, intent(out) :: hygro   ! hygroscopicity
    character(len=*), optional, intent(out) :: spectype  ! species type
    character(len=*), optional, intent(out) :: specname  ! species name
    character(len=*), optional, intent(out) :: specmorph ! species morphology
    complex(r8), pointer, optional, intent(out) :: refindex_sw(:) ! short wave species refractive indices
    complex(r8), pointer, optional, intent(out) :: refindex_lw(:) ! long wave species refractive indices
    real(r8), optional, intent(out) :: num_to_mass_aer ! ratio of number to mass concentration
    real(r8), optional, intent(out) :: dryrad  ! dry radius (m)
    if (present(density)) then
       call rad_aer_get_bin_props_by_idx(self%list_idx_, bin_ndx, species_ndx, density_aer=density)
    end if
    if (present(hygro)) then
       call rad_aer_get_bin_props_by_idx(self%list_idx_, bin_ndx, species_ndx, hygro_aer=hygro)
    end if
    if (present(spectype)) then
       call rad_aer_get_bin_props_by_idx(self%list_idx_, bin_ndx, species_ndx, spectype=spectype)
    end if
    if (present(refindex_sw)) then
       call rad_aer_get_bin_props_by_idx(self%list_idx_, bin_ndx, species_ndx, refindex_aer_sw=refindex_sw)
    end if
    if (present(refindex_lw)) then
       call rad_aer_get_bin_props_by_idx(self%list_idx_, bin_ndx, species_ndx, refindex_aer_lw=refindex_lw)
    end if
    if (present(specmorph)) then
       call rad_aer_get_bin_props_by_idx(self%list_idx_, bin_ndx, species_ndx, specmorph=specmorph)
    end if
    if (present(specname)) then
       if (species_ndx>self%nspecies(bin_ndx)) then
          call rad_aer_get_info_by_bin(self%list_idx_, bin_ndx,  mmr_name=specname)
       else
          call rad_aer_get_info_by_bin_spec(self%list_idx_, bin_ndx, species_ndx, spec_name=specname)
       end if
    end if
    if (present(num_to_mass_aer)) then
       ! num_to_mass_aer for sectional aerosols should not be read from file
       call endrun('carma_aerosol_properties_mod%get: num_to_mass_aer should not be read from file for sectional aerosols')
    end if
    if (present(dryrad)) then
       ! dryrad for sectional aerosols should not be read from file
       call endrun('carma_aerosol_properties_mod%get: dryrad should not be read from file for sectional aerosols')
    end if
  end subroutine get
Call graph
get calls endrun, nspecies, rad_aer_get_bin_props_by_idx, rad_aer_get_info_by_bin, rad_aer_get_info_by_bin_spec
rad_aer_get_bin_props_by_idx calls endrun, physprop_get
rad_aer_get_info_by_bin calls endrun
rad_aer_get_info_by_bin_spec calls endrun
rebin_bulk_fluxes calls get
scav_diam calls get