get_amb_species_numdens – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
get_amb_species_numdens Subroutine
18 statements
Source File
private subroutine get_amb_species_numdens(self, bin_ndx, ncol, nlev, species_type, aero_props, rho, numdens)
Uses
aerosol_properties_mod
Type Bound
aerosol_state
Arguments
Type Intent Optional Attributes Name
class(aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
character(len=*), intent(in) :: species_type
class(aerosol_properties), intent(in) :: aero_props
real(kind=r8), intent(in) :: rho(:,:)
real(kind=r8), intent(out) :: numdens(:,:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, pointer :: num(:,:)
real(kind=r8), private :: size_wght(ncol,nlev)
real(kind=r8), private :: type_wght(ncol,nlev)
Source Code
  subroutine get_amb_species_numdens(self, bin_ndx, ncol, nlev, species_type, aero_props, rho, numdens)
    use aerosol_properties_mod, only: aerosol_properties
    class(aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    integer, intent(in) :: ncol                   ! number of columns
    integer, intent(in) :: nlev                   ! number of vertical levels
    character(len=*), intent(in) :: species_type  ! species type
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    real(r8), intent(in) :: rho(:,:)              ! air density (kg m-3)
    real(r8), intent(out) :: numdens(:,:)         ! species number densities (#/cm^3)
    real(r8), pointer :: num(:,:)
    real(r8) :: type_wght(ncol,nlev)
    real(r8) :: size_wght(ncol,nlev)
    size_wght = self%hetfrz_size_wght(bin_ndx, ncol, nlev)
    call self%icenuc_type_wght_base(bin_ndx, ncol, nlev, species_type, aero_props, rho, type_wght)
    call self%get_ambient_num(bin_ndx, num)
    numdens(:ncol,:) = num(:ncol,:)*rho(:ncol,:)*type_wght(:ncol,:)*size_wght(:ncol,:)*per_cm3
  end subroutine get_amb_species_numdens
Call graph
get_amb_species_numdens calls get_ambient_num, hetfrz_size_wght, icenuc_type_wght_base
icenuc_type_wght_base calls get_ambient_mmr, get_cldbrne_mmr, nspecies, species_type
mass_mean_radius calls get_amb_species_numdens
watact_mfactor calls get_amb_species_numdens