get_nbins – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
get_nbins Function
5 statements
Source File
private pure function get_nbins(self) result(nbins)
Type Bound
aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in) :: self
Return Value integer
Called by
Source Code
  pure function get_nbins(self) result(nbins)
    class(aerosol_properties), intent(in) :: self
    integer :: nbins
    nbins = self%nbins_
  end function get_nbins
Call graph
aqu_gain_binfraction calls get_nbins
constructor calls get_nbins
get_states calls get_nbins
nuclice_get_numdens calls get_nbins
rebin_bulk_fluxes calls get_nbins
sox_cldaero_create_obj calls get_nbins
sox_cldaero_init calls get_nbins
sox_cldaero_update calls get_nbins
water_uptake calls get_nbins
modal_aerosol_properties calls constructor
resuspension_resize calls accumulate_to_larger_mode
water_volume calls water_uptake
wet_volume calls water_volume