get_ambient_num – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
get_ambient_num Subroutine
6 statements
Source File
private subroutine get_ambient_num(self, bin_ndx, num)
Type Bound
modal_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
real(kind=r8), pointer :: num(:,:)
Calls
Called by
Source Code
  subroutine get_ambient_num(self, bin_ndx, num)
    class(modal_aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx     ! bin index
    real(r8), pointer   :: num(:,:)    ! number densities
    call rad_cnst_get_mode_num(self%list_idx_, bin_ndx, 'a', self%state, self%pbuf, num)
  end subroutine get_ambient_num
Call graph
get_ambient_num calls rad_cnst_get_mode_num
get_states calls get_ambient_num
update_bin calls get_ambient_num