get_ambient_mmr – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
get_ambient_mmr Subroutine
7 statements
Source File
public subroutine get_ambient_mmr(self, species_ndx, bin_ndx, mmr)
Type Bound
bulk_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(bulk_aerosol_state), intent(in) :: self
integer, intent(in) :: species_ndx
integer, intent(in) :: bin_ndx
real(kind=r8), pointer :: mmr(:,:)
Calls
Called by
Source Code
  subroutine get_ambient_mmr(self, species_ndx, bin_ndx, mmr)
    class(bulk_aerosol_state), intent(in) :: self
    integer, intent(in) :: species_ndx  ! species index
    integer, intent(in) :: bin_ndx      ! bin index
    real(r8), pointer :: mmr(:,:)       ! mass mixing ratios (ncol,nlev)
    ! species_ndx is ignored in the bulk implementation.
    ! bin_ndx is used to identify each individual bulk aerosol.
    call rad_cnst_get_aer_mmr(self%list_idx_, bin_ndx, self%state, self%pbuf, mmr)
  end subroutine get_ambient_mmr
Call graph
get_ambient_mmr calls rad_cnst_get_aer_mmr
ambient_total_bin_mmr calls get_ambient_mmr
dry_volume calls get_ambient_mmr
wet_volume calls dry_volume