get_cldbrne_num – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
get_cldbrne_num Subroutine
17 statements
Source File
private subroutine get_cldbrne_num(self, bin_ndx, num)
Type Bound
carma_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
real(kind=r8), pointer :: num(:,:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: bin_name
integer, private :: ibin
integer, private :: igroup
integer, private :: nchr
integer, private :: ncol
real(kind=r8), private :: nmr(pcols,pver)
integer, private :: rc
character(len=aero_name_len), private :: shortname
Source Code
  subroutine get_cldbrne_num(self, bin_ndx, num)
    class(carma_aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx     ! bin index
    real(r8), pointer :: num(:,:)      ! number mixing ratios
    character(len=aero_name_len) :: bin_name, shortname
    integer :: igroup, ibin, rc, nchr, ncol
    real(r8) :: nmr(pcols,pver)
    ncol = self%state%ncol
    call rad_aer_get_info_by_bin(self%list_idx_, bin_ndx, bin_name=bin_name)
    nchr = len_trim(bin_name)-2
    shortname = bin_name(:nchr)
    call  carma_get_group_by_name(shortname, igroup, rc)
    read(bin_name(nchr+1:),*) ibin
    call rad_cnst_get_bin_num(self%list_idx_, bin_ndx, 'c', self%state, self%pbuf, num)
    call carma_get_number_cld(self%pbuf, igroup, ibin,  ncol, pver, nmr, rc)
    num(:ncol,:) = nmr(:ncol,:)
  end subroutine get_cldbrne_num
Call graph
get_cldbrne_num calls carma_get_group_by_name, carma_get_number_cld, rad_aer_get_info_by_bin, rad_cnst_get_bin_num
rad_aer_get_info_by_bin calls endrun
get_states calls get_cldbrne_num