get_states – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
get_states Subroutine
17 statements
Source File
private subroutine get_states(self, aero_props, raer, qqcw)
Type Bound
carma_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
type(ptr2d_t), intent(out) :: raer(:)
type(ptr2d_t), intent(out) :: qqcw(:)
Calls
Variables
Type Visibility Attributes Name Initial
integer, private :: ibin
integer, private :: indx
integer, private :: ispc
Source Code
  subroutine get_states( self, aero_props, raer, qqcw )
    class(carma_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props
    type(ptr2d_t), intent(out) :: raer(:)
    type(ptr2d_t), intent(out) :: qqcw(:)
    integer :: ibin,ispc, indx
    do ibin = 1, aero_props%nbins()
       indx = aero_props%indexer(ibin, 0)
       call self%get_ambient_num(ibin, raer(indx)%fld)
       call self%get_cldbrne_num(ibin, qqcw(indx)%fld)
       do ispc = 1, aero_props%nspecies(ibin)
          indx = aero_props%indexer(ibin, ispc)
          call self%get_ambient_mmr(species_ndx=ispc, bin_ndx=ibin, mmr=raer(indx)%fld)
          call self%get_cldbrne_mmr(species_ndx=ispc, bin_ndx=ibin, mmr=qqcw(indx)%fld)
       end do
    end do
  end subroutine get_states
Call graph
get_states calls nspecies, get_ambient_mmr, get_ambient_num, get_cldbrne_mmr, get_cldbrne_num, get_nbins, indexer
get_ambient_mmr calls rad_cnst_get_bin_mmr_by_idx
get_ambient_num calls carma_get_group_by_name, carma_get_number, rad_aer_get_info_by_bin, rad_cnst_get_bin_num
get_cldbrne_mmr calls rad_cnst_get_bin_mmr_by_idx
get_cldbrne_num calls carma_get_group_by_name, carma_get_number_cld, rad_aer_get_info_by_bin, rad_cnst_get_bin_num
rad_aer_get_info_by_bin calls endrun