get – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
get Subroutine
57 statements
Source File
private subroutine get(self, bin_ndx, species_ndx, density, hygro, spectype, specname, specmorph, refindex_sw, refindex_lw, num_to_mass_aer, dryrad)
Type Bound
bulk_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(bulk_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: species_ndx
real(kind=r8), intent(out), optional :: density
real(kind=r8), intent(out), optional :: hygro
character(len=*), intent(out), optional :: spectype
character(len=*), intent(out), optional :: specname
character(len=*), intent(out), optional :: specmorph
complex(kind=r8), intent(out), optional, pointer :: refindex_sw(:)
complex(kind=r8), intent(out), optional, pointer :: refindex_lw(:)
real(kind=r8), intent(out), optional :: num_to_mass_aer
real(kind=r8), intent(out), optional :: dryrad
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=20), private :: aername
Source Code
  subroutine get(self, bin_ndx, species_ndx, density, hygro, &
                 spectype, specname, specmorph, refindex_sw, refindex_lw, num_to_mass_aer, &
                 dryrad)
    class(bulk_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx             ! bin index
    integer, intent(in) :: species_ndx         ! species index
    real(r8), optional, intent(out) :: density ! density (kg/m3)
    real(r8), optional, intent(out) :: hygro   ! hygroscopicity
    character(len=*), optional, intent(out) :: spectype  ! species type
    character(len=*), optional, intent(out) :: specname  ! species name
    character(len=*), optional, intent(out) :: specmorph ! species morphology
    complex(r8), pointer, optional, intent(out) :: refindex_sw(:) ! short wave species refractive indices
    complex(r8), pointer, optional, intent(out) :: refindex_lw(:) ! long wave species refractive indices
    real(r8), optional, intent(out) :: num_to_mass_aer ! ratio of number to mass concentration
    real(r8), optional, intent(out) :: dryrad  ! dry radius (m)
    character(len=20) :: aername
    if (present(density)) then
       call rad_aer_get_props(self%list_idx_, bin_ndx,  density_aer=density)
    end if
    if (present(hygro)) then
       call rad_aer_get_props(self%list_idx_, bin_ndx,  hygro_aer=hygro)
    end if
    if (present(spectype)) then
       call rad_aer_get_props(self%list_idx_, bin_ndx,  aername=aername)
       select case ( to_lower( aername(:4) ) )
       case('dust')
          spectype = 'dust'
       case('sulf','volc')
          spectype = 'sulfate'
       case('bcar','bcph')
          spectype = 'black-c'
       case('ocar','ocph')
          spectype = 'p-organic'
       case('sslt','seas','ssam','sscm')
          spectype = 'seasalt'
       case default
          spectype = 'UNKNOWN'
          call endrun('ERROR: bulk_aerosol_properties_mod%get aername not recognized : '//aername)
       end select
    end if
    if (present(specmorph)) then
      call endrun('ERROR: bulk_aerosol_properties_mod%get specmorph not yet implemented')
    end if
    if (present(specname)) then
       call rad_aer_get_props(self%list_idx_, bin_ndx,  aername=specname)
    end if
    if (present(refindex_sw)) then
       call rad_aer_get_props(self%list_idx_, bin_ndx,  refindex_aer_sw=refindex_sw)
    end if
    if (present(refindex_lw)) then
       call rad_aer_get_props(self%list_idx_, bin_ndx,  refindex_aer_lw=refindex_lw)
    end if
    if (present(num_to_mass_aer)) then
       call rad_aer_get_props(self%list_idx_, bin_ndx,  num_to_mass_aer=num_to_mass_aer)
    end if
    if (present(dryrad)) then
       call rad_aer_get_props(self%list_idx_, bin_ndx,  dryrad_aer=dryrad)
    end if
  end subroutine get
Call graph
get calls endrun, rad_aer_get_props, to_lower
rad_aer_get_props calls rad_aer_get_mam_props_by_idx, rad_aer_get_props_by_idx
rad_aer_get_mam_props_by_idx calls endrun, physprop_get
rad_aer_get_props_by_idx calls endrun, physprop_get
species_type calls get