get – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
get Subroutine
28 statements
Source File
private subroutine get(self, bin_ndx, species_ndx, density, hygro, spectype, specname, specmorph, refindex_sw, refindex_lw, num_to_mass_aer, dryrad)
Uses
cam_abortutils
Type Bound
modal_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: species_ndx
real(kind=r8), intent(out), optional :: density
real(kind=r8), intent(out), optional :: hygro
character(len=*), intent(out), optional :: spectype
character(len=*), intent(out), optional :: specname
character(len=*), intent(out), optional :: specmorph
complex(kind=r8), intent(out), optional, pointer :: refindex_sw(:)
complex(kind=r8), intent(out), optional, pointer :: refindex_lw(:)
real(kind=r8), intent(out), optional :: num_to_mass_aer
real(kind=r8), intent(out), optional :: dryrad
Calls
Called by
Source Code
  subroutine get(self, bin_ndx, species_ndx, density, hygro, &
                 spectype, specname, specmorph, refindex_sw, refindex_lw, num_to_mass_aer, &
                 dryrad)
    use cam_abortutils, only: endrun
    class(modal_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx             ! bin index
    integer, intent(in) :: species_ndx         ! species index
    real(r8), optional, intent(out) :: density ! density (kg/m3)
    real(r8), optional, intent(out) :: hygro   ! hygroscopicity
    character(len=*), optional, intent(out) :: spectype  ! species type
    character(len=*), optional, intent(out) :: specname  ! species name
    character(len=*), optional, intent(out) :: specmorph ! species morphology
    complex(r8), pointer, optional, intent(out) :: refindex_sw(:) ! short wave species refractive indices
    complex(r8), pointer, optional, intent(out) :: refindex_lw(:) ! long wave species refractive indices
    real(r8), optional, intent(out) :: num_to_mass_aer ! ratio of number to mass concentration
    real(r8), optional, intent(out) :: dryrad  ! dry radius (m)
    call rad_aer_get_props(self%list_idx_, bin_ndx, species_ndx, &
                                density_aer=density, hygro_aer=hygro, spectype=spectype, &
                                refindex_aer_sw=refindex_sw, refindex_aer_lw=refindex_lw)
    if (present(specname)) then
       call rad_aer_get_info(self%list_idx_, bin_ndx, species_ndx, spec_name=specname)
    end if
    if (present(specmorph)) then
       specmorph = 'UNKNOWN'
    end if
    if (present(num_to_mass_aer)) then
       ! num_to_mass_aer for modal aerosols should not be read from file
       call endrun('modal_aerosol_properties_mod%get: num_to_mass_aer should not be read from file for modal aerosols')
    end if
    if (present(dryrad)) then
       ! dryrad for modal aerosols should not be read from file
       call endrun('modal_aerosol_properties_mod%get: dryrad should not be read from file for modal aerosols')
    end if
  end subroutine get
Call graph
get calls endrun, rad_aer_get_props, rad_aer_get_info
rad_aer_get_props calls rad_aer_get_mam_props_by_idx, rad_aer_get_props_by_idx
rad_aer_get_mam_props_by_idx calls endrun, physprop_get
rad_aer_get_props_by_idx calls endrun, physprop_get
rebin_bulk_fluxes calls get