hetfrz_species – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
hetfrz_species Function
12 statements
Source File
private function hetfrz_species(self, bin_ndx, spc_ndx) result(res)
Type Bound
carma_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: spc_ndx
Return Value logical
Calls
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: species_type
Source Code
  function hetfrz_species(self, bin_ndx, spc_ndx) result(res)
    class(carma_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx  ! bin number
    integer, intent(in) :: spc_ndx  ! species number
    logical :: res
    character(len=aero_name_len) :: species_type
    res = .false.
    call self%species_type(bin_ndx, spc_ndx, species_type)
    if ( trim(species_type)=='black-c' .or. trim(species_type)=='dust' ) then
       res = .true.
    end if
  end function hetfrz_species
Call graph
hetfrz_species calls species_type
species_type calls rad_aer_get_info_by_bin_spec
rad_aer_get_info_by_bin_spec calls endrun