hydrophilic – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
hydrophilic Function
5 statements
Source File
private function hydrophilic(self, bin_ndx)
Type Bound
bulk_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(bulk_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
Return Value logical
Calls
Source Code
  logical function hydrophilic(self, bin_ndx)
    class(bulk_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx ! bin number
    hydrophilic = self%soluble(bin_ndx)
  end function hydrophilic
Call graph
hydrophilic calls soluble
soluble calls rad_aer_get_props, to_lower
rad_aer_get_props calls rad_aer_get_mam_props_by_idx, rad_aer_get_props_by_idx
rad_aer_get_mam_props_by_idx calls endrun, physprop_get
rad_aer_get_props_by_idx calls endrun, physprop_get