icenuc_size_wght_val – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
icenuc_size_wght_val Subroutine
12 statements
Source File
private subroutine icenuc_size_wght_val(self, bin_ndx, col_ndx, lyr_ndx, species_type, use_preexisting_ice, wght)
Type Bound
carma_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: col_ndx
integer, intent(in) :: lyr_ndx
character(len=*), intent(in) :: species_type
logical, intent(in) :: use_preexisting_ice
real(kind=r8), intent(out) :: wght
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: wght_arr(pcols,pver)
Source Code
  subroutine icenuc_size_wght_val(self, bin_ndx, col_ndx, lyr_ndx, species_type, use_preexisting_ice, wght)
    class(carma_aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    integer, intent(in) :: col_ndx                ! column index
    integer, intent(in) :: lyr_ndx                ! vertical layer index
    character(len=*), intent(in) :: species_type  ! species type
    logical, intent(in) :: use_preexisting_ice    ! pre-existing ice flag
    real(r8), intent(out) :: wght
    real(r8) :: wght_arr(pcols,pver)
    call self%icenuc_size_wght(bin_ndx, self%state%ncol, pver, species_type, use_preexisting_ice, wght_arr)
    wght = wght_arr(col_ndx,lyr_ndx)
  end subroutine icenuc_size_wght_val
Call graph
icenuc_size_wght_val calls icenuc_size_wght, endrun, pbuf_get_field, pbuf_get_index, rad_aer_get_mode_props, rad_aer_get_info
icenuc_size_wght_arr calls endrun, pbuf_get_field, pbuf_get_index, rad_aer_get_mode_props, rad_aer_get_info
rad_aer_get_mode_props calls endrun, physprop_get