icenuc_updates_num – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
icenuc_updates_num Function
17 statements
Source File
private function icenuc_updates_num(self, bin_ndx) result(res)
Type Bound
modal_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
Return Value logical
Calls
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: modetype
integer, private :: spc_ndx
character(len=aero_name_len), private :: spectype
Source Code
  function icenuc_updates_num(self, bin_ndx) result(res)
    class(modal_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx           ! bin number
    logical :: res
    character(len=aero_name_len) :: spectype
    character(len=aero_name_len) :: modetype
    integer :: spc_ndx
    res = .false.
    call rad_aer_get_info(self%list_idx_, bin_ndx, mode_type=modetype)
    if (.not.(modetype=='coarse' .or. modetype=='coarse_dust')) then
       return
    end if
    do spc_ndx = 1, self%nspecies(bin_ndx)
       call self%species_type( bin_ndx, spc_ndx, spectype)
       if (spectype=='dust') res = .true.
    end do
  end function icenuc_updates_num
Call graph
icenuc_updates_num calls nspecies, species_type, rad_aer_get_info
species_type calls rad_aer_get_info