icenuc_size_wght_arr – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
icenuc_size_wght_arr Subroutine
48 statements
Source File
private subroutine icenuc_size_wght_arr(self, bin_ndx, ncol, nlev, species_type, use_preexisting_ice, wght)
Type Bound
modal_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
character(len=*), intent(in) :: species_type
logical, intent(in) :: use_preexisting_ice
real(kind=r8), intent(out) :: wght(:,:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, pointer :: dgnum(:,:,:)
integer, private :: i
integer, private :: k
character(len=aero_name_len), private :: modetype
real(kind=r8), private :: sigmag_aitken
Source Code
  subroutine icenuc_size_wght_arr(self, bin_ndx, ncol, nlev, species_type, use_preexisting_ice, wght)
    class(modal_aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    integer, intent(in) :: ncol                ! number of columns
    integer, intent(in) :: nlev                ! number of vertical levels
    character(len=*), intent(in) :: species_type  ! species type
    logical, intent(in) :: use_preexisting_ice ! pre-existing ice flag
    real(r8), intent(out) :: wght(:,:)
    character(len=aero_name_len) :: modetype
    real(r8), pointer :: dgnum(:,:,:)    ! mode dry radius
    real(r8) :: sigmag_aitken
    integer :: i,k
    if (self%list_idx_ /= 0) then
       call endrun('modal_aerosol_state::icenuc_size_wght_arr: only valid for climate list (list_idx=0)')
    end if
    call rad_aer_get_info(0, bin_ndx, mode_type=modetype)
    wght = 0._r8
    select case ( trim(species_type) )
    case('dust')
       if (modetype=='coarse' .or. modetype=='coarse_dust') then
          wght(:ncol,:) = 1._r8
       end if
    case('sulfate')
       if (modetype=='aitken') then
          if ( use_preexisting_ice ) then
             wght(:ncol,:) = 1._r8
          else
             call rad_aer_get_mode_props(0, bin_ndx, sigmag=sigmag_aitken)
             call pbuf_get_field(self%pbuf, pbuf_get_index('DGNUM' ), dgnum)
             do k = 1,nlev
                do i = 1,ncol
                   if (dgnum(i,k,bin_ndx) > 0._r8) then
                      ! only allow so4 with D>0.1 um in ice nucleation
                      wght(i,k) = max(0._r8,(0.5_r8 - 0.5_r8* &
                           erf(log(0.1e-6_r8/dgnum(i,k,bin_ndx))/ &
                           (2._r8**0.5_r8*log(sigmag_aitken)))  ))
                   end if
                end do
             end do
          endif
       endif
    case('black-c')
       if (modetype=='accum') then
          wght(:ncol,:) = 1._r8
       endif
    case('sulfate_strat')
       if (modetype=='accum' .or. modetype=='coarse' .or. modetype=='coarse_strat') then
          wght(:ncol,:) = 1._r8
       endif
    end select
  end subroutine icenuc_size_wght_arr
Call graph
icenuc_size_wght_arr calls endrun, pbuf_get_field, pbuf_get_index, rad_aer_get_mode_props, rad_aer_get_info
rad_aer_get_mode_props calls endrun, physprop_get
icenuc_size_wght_val calls icenuc_size_wght
nuclice_get_numdens calls icenuc_size_wght