icenuc_size_wght_arr – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
icenuc_size_wght_arr Subroutine
32 statements
Source File
private subroutine icenuc_size_wght_arr(self, bin_ndx, ncol, nlev, species_type, use_preexisting_ice, wght)
Type Bound
carma_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
character(len=*), intent(in) :: species_type
logical, intent(in) :: use_preexisting_ice
real(kind=r8), intent(out) :: wght(:,:)
Calls
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: bin_name
real(kind=r8), private :: diamdry
integer, private :: i
integer, private :: ibin
integer, private :: igroup
integer, private :: k
integer, private :: nchr
integer, private :: rc
real(kind=r8), private :: rdry(ncol,nlev)
real(kind=r8), private :: rhopdry(ncol,nlev)
character(len=aero_name_len), private :: shortname
Source Code
  subroutine icenuc_size_wght_arr(self, bin_ndx, ncol, nlev, species_type, use_preexisting_ice, wght)
    class(carma_aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    integer, intent(in) :: ncol                   ! number of columns
    integer, intent(in) :: nlev                ! number of vertical levels
    character(len=*), intent(in) :: species_type  ! species type
    logical, intent(in) :: use_preexisting_ice ! pre-existing ice flag
    real(r8), intent(out) :: wght(:,:)
    character(len=aero_name_len) :: bin_name, shortname
    real(r8) :: rdry(ncol,nlev), rhopdry(ncol,nlev)
    integer :: i,k
    real(r8) :: diamdry
    integer :: igroup, ibin, rc, nchr
    if (self%list_idx_ /= 0) then
       call endrun('carma_aerosol_state::icenuc_size_wght_arr: only valid for climate list (list_idx=0)')
    end if
    wght = 0._r8
    call rad_aer_get_info_by_bin(0, bin_ndx, bin_name=bin_name)
    nchr = len_trim(bin_name)-2
    shortname = bin_name(:nchr)
    call  carma_get_group_by_name(shortname, igroup, rc)
    read(bin_name(nchr+1:),*) ibin
    call carma_get_dry_radius(self%state, igroup, ibin, rdry, rhopdry, rc) ! m, kg/m3
    do k = 1,nlev
       do i = 1,ncol
          diamdry = rdry(i,k) * 2._r8 * 1.e6_r8 ! diameter in microns (from radius in m)
          if (diamdry >= 0.1_r8) then ! size threashold
             wght(i,k) = 1._r8
          end if
       end do
    end do
  end subroutine icenuc_size_wght_arr
Call graph
icenuc_size_wght_arr calls carma_get_dry_radius, carma_get_group_by_name, endrun, rad_aer_get_info_by_bin
rad_aer_get_info_by_bin calls endrun