icenuc_type_wght_base – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
icenuc_type_wght_base Subroutine
46 statements
Source File
private subroutine icenuc_type_wght_base(self, bin_ndx, ncol, nlev, species_type, aero_props, rho, wght, cloud_borne)
Uses
aerosol_properties_mod
Type Bound
aerosol_state
Arguments
Type Intent Optional Attributes Name
class(aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
character(len=*), intent(in) :: species_type
class(aerosol_properties), intent(in) :: aero_props
real(kind=r8), intent(in) :: rho(:,:)
real(kind=r8), intent(out) :: wght(:,:)
logical, intent(in), optional :: cloud_borne
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, pointer :: aer_bin(:,:)
logical, private :: cldbrne
integer, private :: ispc
real(kind=r8), private :: mass(ncol,nlev)
character(len=aero_name_len), private :: spectype
character(len=aero_name_len), private :: sptype
real(kind=r8), private :: totalmass(ncol,nlev)
Source Code
  subroutine icenuc_type_wght_base(self, bin_ndx, ncol, nlev, species_type, aero_props, rho, wght, cloud_borne)
    use aerosol_properties_mod, only: aerosol_properties
    class(aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    integer, intent(in) :: ncol                   ! number of columns
    integer, intent(in) :: nlev                   ! number of vertical levels
    character(len=*), intent(in) :: species_type  ! species type
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    real(r8), intent(in) :: rho(:,:)              ! air density (kg m-3)
    real(r8), intent(out) :: wght(:,:)            ! type weights
    logical, optional, intent(in) :: cloud_borne  ! if TRUE cloud-borne aerosols are used
                                                  ! otherwise ambient aerosols are used
    real(r8) :: mass(ncol,nlev)
    real(r8) :: totalmass(ncol,nlev)
    real(r8), pointer :: aer_bin(:,:)
    character(len=aero_name_len) :: spectype, sptype
    integer :: ispc
    logical :: cldbrne
    if (present(cloud_borne)) then
       cldbrne = cloud_borne
    else
       cldbrne = .false.
    end if
    wght(:,:) = 0._r8
    totalmass(:,:) = 0._r8
    mass(:,:)   = 0._r8
    if (species_type=='sulfate_strat') then
       sptype = 'sulfate'
    else
       sptype = species_type
    end if
    do ispc = 1, aero_props%nspecies(bin_ndx)
       if (cldbrne) then
          call self%get_cldbrne_mmr(species_ndx=ispc, bin_ndx=bin_ndx, mmr=aer_bin)
       else
          call self%get_ambient_mmr(species_ndx=ispc, bin_ndx=bin_ndx, mmr=aer_bin)
       end if
       call aero_props%species_type(bin_ndx, ispc, spectype=spectype)
       totalmass(:ncol,:) = totalmass(:ncol,:) + aer_bin(:ncol,:)*rho(:ncol,:)
       if (trim(spectype) == trim(sptype)) then
          mass(:ncol,:) = mass(:ncol,:) + aer_bin(:ncol,:)*rho(:ncol,:)
       end if
    end do
    where (totalmass(:ncol,:) > 0._r8)
       wght(:ncol,:) = mass(:ncol,:)/totalmass(:ncol,:)
    end where
  end subroutine icenuc_type_wght_base
Call graph
icenuc_type_wght_base calls get_ambient_mmr, get_cldbrne_mmr, nspecies, species_type
get_amb_species_numdens calls icenuc_type_wght_base
get_cld_species_numdens calls icenuc_type_wght_base
icenuc_type_wght calls icenuc_type_wght_base
nuclice_get_numdens calls icenuc_type_wght_base
mass_mean_radius calls get_amb_species_numdens
watact_mfactor calls get_amb_species_numdens