icenuc_updates_mmr – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
icenuc_updates_mmr Function
15 statements
Source File
private function icenuc_updates_mmr(self, bin_ndx, species_ndx) result(res)
Type Bound
carma_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: species_ndx
Return Value logical
Calls
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: spectype
Source Code
  function icenuc_updates_mmr(self, bin_ndx, species_ndx) result(res)
    class(carma_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx           ! bin number
    integer, intent(in) :: species_ndx       ! species number
    logical :: res
    character(len=aero_name_len) :: spectype
    res = .false.
    if (species_ndx==0) then
       res = self%icenuc_updates_num(bin_ndx)
    else
       call self%species_type( bin_ndx, species_ndx, spectype)
       if (trim(spectype)=='dust') res = .true.
       if (trim(spectype)=='sulfate') res = .true.
    end if
  end function icenuc_updates_mmr
Call graph
icenuc_updates_mmr calls icenuc_updates_num, species_type
icenuc_updates_num calls species_type, nspecies
species_type calls rad_aer_get_info_by_bin_spec
rad_aer_get_info_by_bin_spec calls endrun