icenuc_type_wght – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
icenuc_type_wght Subroutine
34 statements
Source File
private subroutine icenuc_type_wght(self, bin_ndx, ncol, nlev, species_type, aero_props, rho, wght, cloud_borne)
Uses
aerosol_properties_mod
Type Bound
modal_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
character(len=*), intent(in) :: species_type
class(aerosol_properties), intent(in) :: aero_props
real(kind=r8), intent(in) :: rho(:,:)
real(kind=r8), intent(out) :: wght(:,:)
logical, intent(in), optional :: cloud_borne
Calls
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: modetype
Source Code
  subroutine icenuc_type_wght(self, bin_ndx, ncol, nlev, species_type, aero_props, rho, wght, cloud_borne)
    use aerosol_properties_mod, only: aerosol_properties
    use aerosol_properties_mod, only: aero_name_len
    class(modal_aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    integer, intent(in) :: ncol                   ! number of columns
    integer, intent(in) :: nlev                   ! number of vertical levels
    character(len=*), intent(in) :: species_type  ! species type
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    real(r8), intent(in) :: rho(:,:)              ! air density (kg m-3)
    real(r8), intent(out) :: wght(:,:)            ! type weights
    logical, optional, intent(in) :: cloud_borne  ! if TRUE cloud-borne aerosols are used
                                                  ! otherwise ambient aerosols are used
    character(len=aero_name_len) :: modetype
    if (self%list_idx_ /= 0) then
       call endrun('modal_aerosol_state::icenuc_type_wght: only valid for climate list (list_idx=0)')
    end if
    call rad_aer_get_info(0, bin_ndx, mode_type=modetype)
    wght = 0._r8
    if (species_type == 'dust') then
       if (modetype=='coarse_dust') then
          wght(:ncol,:) = 1._r8
       else
          call self%icenuc_type_wght_base(bin_ndx, ncol, nlev, species_type, aero_props, rho, wght, cloud_borne)
       end if
    else if (species_type == 'sulfate_strat') then
       if (modetype=='accum') then
          wght(:ncol,:) = 1._r8
       elseif ( modetype=='coarse' .or. modetype=='coarse_strat') then
          call self%icenuc_type_wght_base(bin_ndx, ncol, nlev, species_type, aero_props, rho, wght, cloud_borne)
       endif
    else
       wght(:ncol,:) = 1._r8
    end if
  end subroutine icenuc_type_wght
Call graph
icenuc_type_wght calls endrun, icenuc_type_wght_base, rad_aer_get_info
icenuc_type_wght_base calls get_ambient_mmr, get_cldbrne_mmr, nspecies, species_type