indexer – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
indexer Function
6 statements
Source File
private pure function indexer(self, bin_ndx, species_ndx)
Type Bound
aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: species_ndx
Return Value integer
Called by
Source Code
  pure integer function indexer(self,bin_ndx,species_ndx)
    class(aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx           ! bin number
    integer, intent(in) :: species_ndx       ! species number
    indexer = self%indexer_(bin_ndx,species_ndx)
  end function indexer
Call graph
constructor calls indexer
get_states calls indexer
rebin_bulk_fluxes calls indexer
carma_aerosol_properties calls constructor
modal_aerosol_properties calls constructor