loadaer – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
loadaer Subroutine
64 statements
Source File
private subroutine loadaer(self, aero_props, ncol, nlev, m, cs, phase, naerosol, vaerosol, hygro, errnum, errstr, pom_hygro)
Uses
aerosol_properties_mod
Type Bound
aerosol_state
Arguments
Type Intent Optional Attributes Name
class(aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: ncol
integer, intent(in) :: nlev
integer, intent(in) :: m
real(kind=r8), intent(in) :: cs(:,:)
integer, intent(in) :: phase
real(kind=r8), intent(out) :: naerosol(:,:)
real(kind=r8), intent(out) :: vaerosol(:,:)
real(kind=r8), intent(out) :: hygro(:,:)
integer, intent(out) :: errnum
character(len=*), intent(out) :: errstr
real(kind=r8), intent(in), optional :: pom_hygro
Calls
Variables
Type Visibility Attributes Name Initial
integer, private :: l
real(kind=r8), private, pointer :: qqcw(:,:)
real(kind=r8), private, pointer :: raer(:,:)
real(kind=r8), private :: specdens
real(kind=r8), private :: spechygro
character(len=aero_name_len), private :: spectype
real(kind=r8), private :: vol(ncol,nlev)
Source Code
  subroutine loadaer( self, aero_props, ncol, nlev,  m, cs, phase, &
                       naerosol, vaerosol, hygro, errnum, errstr, pom_hygro)
    use aerosol_properties_mod, only: aerosol_properties
    ! input arguments
    class(aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props
    integer,  intent(in) :: ncol, nlev
    integer,  intent(in) :: m           ! mode or bin index
    real(r8), intent(in) :: cs(:,:)     ! air density (kg/m3)
    integer,  intent(in) :: phase       ! phase of aerosol: 1 for interstitial, 2 for cloud-borne, 3 for sum
    ! output arguments
    real(r8), intent(out) :: naerosol(:,:)  ! number conc (1/m3)
    real(r8), intent(out) :: vaerosol(:,:)  ! volume conc (m3/m3)
    real(r8), intent(out) :: hygro(:,:)     ! bulk hygroscopicity of mode
    integer ,         intent(out) :: errnum
    character(len=*), intent(out) :: errstr
    real(r8), optional, intent(in) :: pom_hygro     ! POM hygroscopicity override
    ! internal
    real(r8), pointer :: raer(:,:) ! interstitial aerosol mass, number mixing ratios
    real(r8), pointer :: qqcw(:,:) ! cloud-borne aerosol mass, number mixing ratios
    real(r8) :: specdens, spechygro
    character(len=aero_name_len) :: spectype
    real(r8) :: vol(ncol,nlev) ! aerosol volume mixing ratio
    integer  :: l
    !-------------------------------------------------------------------------------
    errnum = 0
    vaerosol(:,:) = 0._r8
    hygro(:,:)    = 0._r8
    do l = 1, aero_props%nspecies(m)
       call self%get_ambient_mmr(species_ndx=l, bin_ndx=m, mmr=raer)
       call self%get_cldbrne_mmr(species_ndx=l, bin_ndx=m, mmr=qqcw)
       call aero_props%get(m,l, density=specdens, hygro=spechygro, spectype=spectype)
       if (present(pom_hygro)) then
          if (spectype=='p-organic'.and.pom_hygro>0._r8) then
             spechygro=pom_hygro
          endif
       endif
       if (phase == 3) then
          vol(:ncol,:) = max(raer(:ncol,:) + qqcw(:ncol,:), 0._r8)/specdens
       else if (phase == 2) then
          vol(:ncol,:) = max(qqcw(:ncol,:), 0._r8)/specdens
       else if (phase == 1) then
          vol(:ncol,:) = max(raer(:ncol,:), 0._r8)/specdens
       else
          errnum = -1
          write(errstr,*)'phase = ',phase,' in aerosol_state::loadaer not recognized'
          return
       end if
       vaerosol(:ncol,:) = vaerosol(:ncol,:) + vol(:ncol,:)
       hygro(:ncol,:)    = hygro(:ncol,:) + vol(:ncol,:)*spechygro
    end do
    where(vaerosol(:ncol,:) > 1.0e-30_r8)
       hygro(:ncol,:)    = hygro(:ncol,:)/(vaerosol(:ncol,:))
       vaerosol(:ncol,:) = vaerosol(:ncol,:)*cs(:ncol,:)
    elsewhere
       hygro(:ncol,:)    = 0._r8
       vaerosol(:ncol,:) = 0._r8
    end where
    ! aerosol number mixing ratios (#/kg)
    call self%get_ambient_num(m, raer)
    call self%get_cldbrne_num(m, qqcw)
    if (phase == 3) then
       naerosol(:ncol,:) = (raer(:ncol,:) + qqcw(:ncol,:))*cs(:ncol,:) ! #/kg -> #/m3
    else if (phase == 2) then
       naerosol(:ncol,:) = qqcw(:ncol,:)*cs(:ncol,:)
    else
       naerosol(:ncol,:) = raer(:ncol,:)*cs(:ncol,:)
    end if
    ! adjust number
    call aero_props%apply_number_limits( naerosol, vaerosol, ncol, nlev, m )
  end subroutine loadaer
Call graph
loadaer calls apply_number_limits, get, get_ambient_mmr, get_ambient_num, get_cldbrne_mmr, get_cldbrne_num, nspecies