lw_props – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
lw_props Subroutine
32 statements
Source File
private subroutine lw_props(self, ncol, ilev, iwav, pabs)
Type Bound
refractive_aerosol_optics
Arguments
Type Intent Optional Attributes Name
class(refractive_aerosol_optics), intent(in) :: self
integer, intent(in) :: ncol
integer, intent(in) :: ilev
integer, intent(in) :: iwav
real(kind=r8), intent(out) :: pabs(ncol)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: cabs(self%ncoef,ncol)
complex(kind=r8), private :: crefin(ncol)
integer, private :: icoef
integer, private :: icol
real(kind=r8), private :: refi(ncol)
real(kind=r8), private :: refr(ncol)
type(table_interp_wghts), private :: wghtsi(ncol)
type(table_interp_wghts), private :: wghtsr(ncol)
Source Code
  subroutine lw_props(self, ncol, ilev, iwav, pabs)
    class(refractive_aerosol_optics), intent(in) :: self
    integer, intent(in) :: ncol        ! number of columns
    integer, intent(in) :: ilev        ! vertical level index
    integer, intent(in) :: iwav        ! wave length index
    real(r8),intent(out) :: pabs(ncol) ! parameterized specific absorption (m2/kg)
    real(r8) :: refr(ncol)      ! real part of refractive index
    real(r8) :: refi(ncol)      ! imaginary part of refractive index
    real(r8) :: cabs(self%ncoef,ncol)
    complex(r8) :: crefin(ncol) ! complex refractive index
    integer :: icol, icoef
    type(table_interp_wghts) :: wghtsr(ncol)
    type(table_interp_wghts) :: wghtsi(ncol)
    crefin(:ncol) = self%aero_state%refractive_index_lw(ncol, ilev, self%ibin, iwav, self%aero_props)
    do icol = 1, ncol
       crefin(icol) = crefin(icol) + self%watervol(icol,ilev)*self%crefwlw(iwav)
       crefin(icol) = crefin(icol)/max(self%wetvol(icol,ilev), 1.e-40_r8)
       refr(icol) = real(crefin(icol))
       refi(icol) = aimag(crefin(icol))
    end do
    ! interpolate coefficients linear in refractive index
    wghtsr = table_interp_calcwghts( self%prefr, self%refrtablw(:,iwav), ncol, refr(:ncol) )
    wghtsi = table_interp_calcwghts( self%prefi, self%refitablw(:,iwav), ncol, refi(:ncol) )
    cabs(:,:ncol)= table_interp( self%ncoef,ncol, self%prefr,self%prefi, wghtsr,wghtsi, self%absplw(:,:,:,iwav))
    do icol = 1,ncol
       pabs(icol) = 0.5_r8*cabs(1,icol)
       do icoef = 2, self%ncoef
          pabs(icol) = pabs(icol) + self%cheb(icoef,icol,ilev)*cabs(icoef,icol)
       end do
       pabs(icol) = pabs(icol)*self%wetvol(icol,ilev)*rhoh2o
       pabs(icol) = max(0._r8,pabs(icol))
    end do
  end subroutine lw_props
Call graph
lw_props calls refractive_index_lw, table_interp, table_interp_calcwghts
refractive_index_lw calls get, get_ambient_mmr, nspecies