mass_mean_radius – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
mass_mean_radius Function
33 statements
Source File
private function mass_mean_radius(self, bin_ndx, species_ndx, ncol, nlev, aero_props, rho) result(radius)
Type Bound
aerosol_state
Arguments
Type Intent Optional Attributes Name
class(aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: species_ndx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
class(aerosol_properties), intent(in) :: aero_props
real(kind=r8), intent(in) :: rho(:,:)
Return Value real(kind=r8), (ncol,nlev)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: aer_massdens(ncol,nlev)
real(kind=r8), private, pointer :: aer_mmr(:,:)
real(kind=r8), private :: aer_numdens(ncol,nlev)
integer, private :: i
integer, private :: k
real(kind=r8), private :: minrad
real(kind=r8), private :: specdens
character(len=aero_name_len), private :: species_type
real(kind=r8), private :: wght(ncol,nlev)
Source Code
  function mass_mean_radius(self, bin_ndx, species_ndx, ncol, nlev, aero_props, rho) result(radius)
    class(aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    integer, intent(in) :: species_ndx            ! species number
    integer, intent(in) :: ncol                   ! number of columns
    integer, intent(in) :: nlev                   ! number of vertical levels
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    real(r8), intent(in) :: rho(:,:)              ! air density (kg m-3)
    real(r8) :: radius(ncol,nlev) ! m
    character(len=aero_name_len) :: species_type
    real(r8) :: aer_numdens(ncol,nlev) ! kg/m3
    real(r8) :: aer_massdens(ncol,nlev) ! kg/m3
    real(r8),pointer :: aer_mmr(:,:) ! kg/kg
    real(r8) :: specdens,minrad
    real(r8) :: wght(ncol,nlev)
    integer :: i,k
    wght = self%hetfrz_size_wght(bin_ndx, ncol, nlev)
    call aero_props%species_type(bin_ndx, species_ndx, spectype=species_type)
    call aero_props%get(bin_ndx, species_ndx, density=specdens) ! kg/m3
    call self%get_ambient_mmr(species_ndx=species_ndx, bin_ndx=bin_ndx, mmr=aer_mmr) ! kg/kg
    call self%get_amb_species_numdens(bin_ndx, ncol, nlev, species_type, aero_props, rho, aer_numdens) ! #/cm3
    aer_massdens(:ncol,:) = aer_mmr(:ncol,:)*rho(:ncol,:)*wght(:ncol,:) ! kg/m3
    minrad = aero_props%min_mass_mean_rad(bin_ndx, species_ndx)
    do k = 1,nlev
       do i = 1,ncol
          if (aer_massdens(i,k)*1.0e-3_r8 > 1.0e-30_r8 .and. aer_numdens(i,k) > 1.0e-3_r8) then
             radius(i,k) = (3._r8/(4*pi*specdens)*aer_massdens(i,k)/(aer_numdens(i,k)*per_m3))**(1._r8/3._r8) ! m
          else
             radius(i,k) = minrad
          end if
       end do
    end do
  end function mass_mean_radius
Call graph
mass_mean_radius calls get, get_ambient_mmr, hetfrz_size_wght, min_mass_mean_rad, get_amb_species_numdens, species_type
get_amb_species_numdens calls hetfrz_size_wght, get_ambient_num, icenuc_type_wght_base
icenuc_type_wght_base calls get_ambient_mmr, species_type, get_cldbrne_mmr, nspecies