nspecies_all_bins – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
nspecies_all_bins Function
5 statements
Source File
private pure function nspecies_all_bins(self) result(arr)
Type Bound
aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in) :: self
Return Value integer, (self%nbins_)
Called by
Source Code
  pure function nspecies_all_bins(self) result(arr)
    class(aerosol_properties), intent(in) :: self
    integer :: arr(self%nbins_)
    arr(:) = self%nspecies_(:)
  end function nspecies_all_bins
Call graph
aerosol_optics_sw_bin calls nspecies
ambient_total_bin_mmr calls nspecies
aqu_gain_binfraction calls nspecies
coated_frac calls nspecies
constructor calls nspecies
convcld_actfrac calls nspecies
dry_volume calls nspecies
get calls nspecies
get_states calls nspecies
icenuc_type_wght_base calls nspecies
icenuc_updates_num calls nspecies
loadaer calls nspecies
nuclice_get_numdens calls nspecies, icenuc_type_wght_base
rebin_bulk_fluxes calls nspecies, get
refractive_index_lw calls nspecies
refractive_index_sw calls nspecies
scav_diam calls nspecies, get
sol_factb_interstitial calls nspecies
sox_cldaero_create_obj calls nspecies
sox_cldaero_update calls nspecies
watact_mfactor calls nspecies, get_amb_species_numdens
hygrocoreshell_aerosol_optics calls constructor
hygrowghtpct_aerosol_optics calls constructor
refractive_aerosol_optics calls constructor
get_amb_species_numdens calls icenuc_type_wght_base
get_cld_species_numdens calls icenuc_type_wght_base
icenuc_type_wght calls icenuc_type_wght_base
icenuc_updates_mmr calls icenuc_updates_num
lw_props calls refractive_index_lw
sw_props calls refractive_index_sw
wet_volume calls dry_volume
mass_mean_radius calls get_amb_species_numdens