nuclice_get_numdens – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
nuclice_get_numdens Subroutine
40 statements
Source File
private subroutine nuclice_get_numdens(self, aero_props, use_preexisting_ice, ncol, nlev, rho, dust_num_col, sulf_num_col, soot_num_col, sulf_num_tot_col)
Type Bound
aerosol_state
Arguments
Type Intent Optional Attributes Name
class(aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
logical, intent(in) :: use_preexisting_ice
integer, intent(in) :: ncol
integer, intent(in) :: nlev
real(kind=r8), intent(in) :: rho(:,:)
real(kind=r8), intent(out) :: dust_num_col(:,:)
real(kind=r8), intent(out) :: sulf_num_col(:,:)
real(kind=r8), intent(out) :: soot_num_col(:,:)
real(kind=r8), intent(out) :: sulf_num_tot_col(:,:)
Calls
Variables
Type Visibility Attributes Name Initial
integer, private :: ibin
integer, private :: ispc
real(kind=r8), private, pointer :: num_col(:,:)
real(kind=r8), private :: size_wghts(ncol,nlev)
character(len=aero_name_len), private :: spectype
real(kind=r8), private :: type_wghts(ncol,nlev)
Source Code
  subroutine nuclice_get_numdens(self, aero_props, use_preexisting_ice, ncol, nlev, rho, dust_num_col, sulf_num_col, soot_num_col, sulf_num_tot_col )
    class(aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    logical, intent(in) :: use_preexisting_ice
    integer, intent(in) :: ncol                   ! number of columns
    integer, intent(in) :: nlev                   ! number of vertical levels
    real(r8), intent(in) :: rho(:,:) ! air density (kg m-3)
    real(r8), intent(out) :: dust_num_col(:,:) ! dust number densities (#/cm^3)
    real(r8), intent(out) :: sulf_num_col(:,:) ! sulfate number densities (#/cm^3)
    real(r8), intent(out) :: soot_num_col(:,:) ! soot number densities (#/cm^3)
    real(r8), intent(out) :: sulf_num_tot_col(:,:) ! stratopsheric sulfate number densities (#/cm^3)
    integer :: ibin,ispc
    character(len=aero_name_len) :: spectype
    real(r8) :: size_wghts(ncol,nlev)
    real(r8) :: type_wghts(ncol,nlev)
    real(r8), pointer :: num_col(:,:)
    dust_num_col(:,:) = 0._r8
    sulf_num_col(:,:) = 0._r8
    soot_num_col(:,:) = 0._r8
    sulf_num_tot_col(:,:) = 0._r8
    ! collect number densities (#/cm^3) for dust, sulfate, and soot
    do ibin = 1,aero_props%nbins()
       call self%get_ambient_num(ibin, num_col)
       do ispc = 1,aero_props%nspecies(ibin)
          call aero_props%species_type(ibin, ispc, spectype)
          call self%icenuc_size_wght(ibin, ncol, nlev, spectype, use_preexisting_ice, size_wghts)
          call self%icenuc_type_wght(ibin, ncol, nlev, spectype, aero_props, rho, type_wghts)
          select case ( trim(spectype) )
          case('dust')
             dust_num_col(:ncol,:) = dust_num_col(:ncol,:) &
                  + size_wghts(:ncol,:)*type_wghts(:ncol,:)*num_col(:ncol,:)*rho(:ncol,:)*per_cm3
          case('sulfate')
             ! This order of ops gives bit-for-bit results for cam5 phys ( use_preexisting_ice = .false. )
             sulf_num_col(:ncol,:) = sulf_num_col(:ncol,:) &
                  + num_col(:ncol,:)*rho(:ncol,:)*per_cm3  * size_wghts(:ncol,:)*type_wghts(:ncol,:)
          case('black-c')
             soot_num_col(:ncol,:) = soot_num_col(:ncol,:) &
                  + size_wghts(:ncol,:)*type_wghts(:ncol,:)*num_col(:ncol,:)*rho(:ncol,:)*per_cm3
          end select
       enddo
       ! stratospheric sulfates -- special case not included in the species loop above
       call self%icenuc_size_wght(ibin, ncol, nlev, 'sulfate_strat', use_preexisting_ice, size_wghts)
       call self%icenuc_type_wght(ibin, ncol, nlev, 'sulfate_strat', aero_props, rho, type_wghts)
       sulf_num_tot_col(:ncol,:) = sulf_num_tot_col(:ncol,:) &
            + size_wghts(:ncol,:)*type_wghts(:ncol,:)*num_col(:ncol,:)*rho(:ncol,:)*per_cm3
    enddo
  end subroutine nuclice_get_numdens
Call graph
nuclice_get_numdens calls get_ambient_num, icenuc_size_wght, nspecies, get_nbins, icenuc_type_wght_base, species_type
icenuc_type_wght_base calls nspecies, species_type, get_ambient_mmr, get_cldbrne_mmr
icenuc_size_wght_arr calls endrun, pbuf_get_field, pbuf_get_index, rad_aer_get_mode_props, rad_aer_get_info
icenuc_size_wght_val calls endrun, pbuf_get_field, pbuf_get_index, rad_aer_get_mode_props, rad_aer_get_info
rad_aer_get_mode_props calls endrun, physprop_get