optics_params – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
optics_params Subroutine
51 statements
Source File
private subroutine optics_params(self, bin_ndx, opticstype, extpsw, abspsw, asmpsw, absplw, refrtabsw, refitabsw, refrtablw, refitablw, ncoef, prefr, prefi, sw_hygro_ext_wtp, sw_hygro_ssa_wtp, sw_hygro_asm_wtp, lw_hygro_ext_wtp, wgtpct, nwtp, sw_hygro_coreshell_ext, sw_hygro_coreshell_ssa, sw_hygro_coreshell_asm, lw_hygro_coreshell_ext, corefrac, bcdust, kap, relh, nfrac, nbcdust, nkap, nrelh, sw_hygroscopic_ext, sw_hygroscopic_ssa, sw_hygroscopic_asm, lw_hygroscopic_ext, sw_insoluble_ext, sw_insoluble_ssa, sw_insoluble_asm, lw_insoluble_ext, r_sw_ext, r_sw_scat, r_sw_ascat, r_mu, r_lw_abs)
Uses
phys_prop
Type Bound
aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
character(len=*), intent(out), optional :: opticstype
real(kind=r8), optional, pointer :: extpsw(:,:,:,:)
real(kind=r8), optional, pointer :: abspsw(:,:,:,:)
real(kind=r8), optional, pointer :: asmpsw(:,:,:,:)
real(kind=r8), optional, pointer :: absplw(:,:,:,:)
real(kind=r8), optional, pointer :: refrtabsw(:,:)
real(kind=r8), optional, pointer :: refitabsw(:,:)
real(kind=r8), optional, pointer :: refrtablw(:,:)
real(kind=r8), optional, pointer :: refitablw(:,:)
integer, intent(out), optional :: ncoef
integer, intent(out), optional :: prefr
integer, intent(out), optional :: prefi
real(kind=r8), optional, pointer :: sw_hygro_ext_wtp(:,:)
real(kind=r8), optional, pointer :: sw_hygro_ssa_wtp(:,:)
real(kind=r8), optional, pointer :: sw_hygro_asm_wtp(:,:)
real(kind=r8), optional, pointer :: lw_hygro_ext_wtp(:,:)
real(kind=r8), optional, pointer :: wgtpct(:)
integer, intent(out), optional :: nwtp
real(kind=r8), optional, pointer :: sw_hygro_coreshell_ext(:,:,:,:,:)
real(kind=r8), optional, pointer :: sw_hygro_coreshell_ssa(:,:,:,:,:)
real(kind=r8), optional, pointer :: sw_hygro_coreshell_asm(:,:,:,:,:)
real(kind=r8), optional, pointer :: lw_hygro_coreshell_ext(:,:,:,:,:)
real(kind=r8), optional, pointer :: corefrac(:)
real(kind=r8), optional, pointer :: bcdust(:)
real(kind=r8), optional, pointer :: kap(:)
real(kind=r8), optional, pointer :: relh(:)
integer, intent(out), optional :: nfrac
integer, intent(out), optional :: nbcdust
integer, intent(out), optional :: nkap
integer, intent(out), optional :: nrelh
real(kind=r8), optional, pointer :: sw_hygroscopic_ext(:,:)
real(kind=r8), optional, pointer :: sw_hygroscopic_ssa(:,:)
real(kind=r8), optional, pointer :: sw_hygroscopic_asm(:,:)
real(kind=r8), optional, pointer :: lw_hygroscopic_ext(:,:)
real(kind=r8), optional, pointer :: sw_insoluble_ext(:)
real(kind=r8), optional, pointer :: sw_insoluble_ssa(:)
real(kind=r8), optional, pointer :: sw_insoluble_asm(:)
real(kind=r8), optional, pointer :: lw_insoluble_ext(:)
real(kind=r8), optional, pointer :: r_sw_ext(:,:)
real(kind=r8), optional, pointer :: r_sw_scat(:,:)
real(kind=r8), optional, pointer :: r_sw_ascat(:,:)
real(kind=r8), optional, pointer :: r_mu(:)
real(kind=r8), optional, pointer :: r_lw_abs(:,:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: id
Source Code
  subroutine optics_params(self, bin_ndx, opticstype, extpsw, abspsw, asmpsw, absplw, &
       refrtabsw, refitabsw, refrtablw, refitablw, ncoef, prefr, prefi, sw_hygro_ext_wtp, &
       sw_hygro_ssa_wtp, sw_hygro_asm_wtp, lw_hygro_ext_wtp, wgtpct, nwtp, &
       sw_hygro_coreshell_ext, sw_hygro_coreshell_ssa, sw_hygro_coreshell_asm, lw_hygro_coreshell_ext, &
       corefrac, bcdust, kap, relh, nfrac, nbcdust, nkap, nrelh, &
       sw_hygroscopic_ext, sw_hygroscopic_ssa, sw_hygroscopic_asm, lw_hygroscopic_ext, &
       sw_insoluble_ext, sw_insoluble_ssa, sw_insoluble_asm, lw_insoluble_ext, &
       r_sw_ext, r_sw_scat, r_sw_ascat, r_mu, r_lw_abs)
    use phys_prop,    only: physprop_get
    class(aerosol_properties),  intent(in)  :: self
    integer,                    intent(in)  :: bin_ndx     ! mode/bin index
    character(len=*), optional, intent(out) :: opticstype
    ! refactive index table parameters
    real(r8),  optional, pointer     :: extpsw(:,:,:,:) ! short wave specific extinction
    real(r8),  optional, pointer     :: abspsw(:,:,:,:) ! short wave specific absorption
    real(r8),  optional, pointer     :: asmpsw(:,:,:,:) ! short wave asymmetry factor
    real(r8),  optional, pointer     :: absplw(:,:,:,:) ! long wave specific absorption
    real(r8),  optional, pointer     :: refrtabsw(:,:)  ! table of short wave real refractive indices for aerosols
    real(r8),  optional, pointer     :: refitabsw(:,:)  ! table of short wave imaginary refractive indices for aerosols
    real(r8),  optional, pointer     :: refrtablw(:,:)  ! table of long wave real refractive indices for aerosols
    real(r8),  optional, pointer     :: refitablw(:,:)  ! table of long wave imaginary refractive indices for aerosols
    integer,   optional, intent(out) :: ncoef  ! number of chebychev polynomials
    integer,   optional, intent(out) :: prefr  ! number of real refractive indices in table
    integer,   optional, intent(out) :: prefi  ! number of imaginary refractive indices in table
    ! hygrowghtpct table parameters
    real(r8),  optional, pointer     :: sw_hygro_ext_wtp(:,:) ! short wave extinction table
    real(r8),  optional, pointer     :: sw_hygro_ssa_wtp(:,:) ! short wave single-scatter albedo table
    real(r8),  optional, pointer     :: sw_hygro_asm_wtp(:,:) ! short wave asymmetry table
    real(r8),  optional, pointer     :: lw_hygro_ext_wtp(:,:) ! long wave absorption table
    real(r8),  optional, pointer     :: wgtpct(:)             ! weight percent of H2SO4/H2O solution
    integer,   optional, intent(out) :: nwtp                  ! number of weight percent values
    ! hygrocoreshell table parameters
    real(r8),  optional, pointer     :: sw_hygro_coreshell_ext(:,:,:,:,:) ! short wave extinction table
    real(r8),  optional, pointer     :: sw_hygro_coreshell_ssa(:,:,:,:,:) ! short wave single-scatter albedo table
    real(r8),  optional, pointer     :: sw_hygro_coreshell_asm(:,:,:,:,:) ! short wave asymmetry table
    real(r8),  optional, pointer     :: lw_hygro_coreshell_ext(:,:,:,:,:) ! long wave absorption table
    real(r8),  optional, pointer     :: corefrac(:) ! core fraction dimension values
    real(r8),  optional, pointer     :: bcdust(:)   ! bc/(bc + dust) fraction dimension values
    real(r8),  optional, pointer     :: kap(:)      ! hygroscopicity dimension values
    real(r8),  optional, pointer     :: relh(:)     ! relative humidity dimension values
    integer,   optional, intent(out) :: nfrac       ! core fraction dimension size
    integer,   optional, intent(out) :: nbcdust     ! bc/(bc + dust) fraction dimension size
    integer,   optional, intent(out) :: nkap        ! hygroscopicity dimension size
    integer,   optional, intent(out) :: nrelh       ! relative humidity dimension size
    ! hygroscopic
    real(r8),  optional, pointer :: sw_hygroscopic_ext(:,:) ! short wave extinction table
    real(r8),  optional, pointer :: sw_hygroscopic_ssa(:,:) ! short wave single-scatter albedo table
    real(r8),  optional, pointer :: sw_hygroscopic_asm(:,:) ! short wave asymmetry table
    real(r8),  optional, pointer :: lw_hygroscopic_ext(:,:) ! long wave absorption table
    ! non-hygroscopic (insoluble)
    real(r8),  optional, pointer :: sw_insoluble_ext(:) ! short wave extinction table
    real(r8),  optional, pointer :: sw_insoluble_ssa(:) ! short wave single-scatter albedo table
    real(r8),  optional, pointer :: sw_insoluble_asm(:) ! short wave asymmetry table
    real(r8),  optional, pointer :: lw_insoluble_ext(:) ! long wave absorption table
    ! volcanic radius
    real(r8),  optional, pointer :: r_sw_ext(:,:)
    real(r8),  optional, pointer :: r_sw_scat (:,:)
    real(r8),  optional, pointer :: r_sw_ascat(:,:)
    real(r8),  optional, pointer :: r_mu(:)
    real(r8),  optional, pointer :: r_lw_abs(:,:)
    integer :: id
    id = self%physprop_id(bin_ndx)
    ! Retrieve all requested parameters from physprop.
    ! Absent optional arguments are passed through as absent to physprop_get.
    ! Pointer fields that are not populated for this physprop are nullified
    ! during physprop_init, so physprop_get returns disassociated pointers
    ! for unused optics types.
    !
    ! Several parameter names differ between this interface and physprop_get:
    !   lw_hygro_ext_wtp       -> lw_hygro_abs_wtp
    !   lw_hygro_coreshell_ext -> lw_hygro_coreshell_abs
    !   sw_hygroscopic_ext     -> sw_hygro_ext
    !   sw_hygroscopic_ssa     -> sw_hygro_ssa
    !   sw_hygroscopic_asm     -> sw_hygro_asm
    !   lw_hygroscopic_ext     -> lw_hygro_abs
    !   sw_insoluble_ext       -> sw_nonhygro_ext
    !   sw_insoluble_ssa       -> sw_nonhygro_ssa
    !   sw_insoluble_asm       -> sw_nonhygro_asm
    !   lw_insoluble_ext       -> lw_abs
    !   r_mu                   -> mu
    call physprop_get(id, opticstype=opticstype, &
         ! refractive index table parameters (modal)
         extpsw=extpsw, abspsw=abspsw, asmpsw=asmpsw, absplw=absplw, &
         refrtabsw=refrtabsw, refitabsw=refitabsw, &
         refrtablw=refrtablw, refitablw=refitablw, &
         ncoef=ncoef, prefr=prefr, prefi=prefi, &
         ! hygrowghtpct table parameters (CARMA)
         sw_hygro_ext_wtp=sw_hygro_ext_wtp, &
         sw_hygro_ssa_wtp=sw_hygro_ssa_wtp, &
         sw_hygro_asm_wtp=sw_hygro_asm_wtp, &
         lw_hygro_abs_wtp=lw_hygro_ext_wtp, &
         wgtpct=wgtpct, nwtp=nwtp, &
         ! hygrocoreshell table parameters (CARMA)
         sw_hygro_coreshell_ext=sw_hygro_coreshell_ext, &
         sw_hygro_coreshell_ssa=sw_hygro_coreshell_ssa, &
         sw_hygro_coreshell_asm=sw_hygro_coreshell_asm, &
         lw_hygro_coreshell_abs=lw_hygro_coreshell_ext, &
         corefrac=corefrac, bcdust=bcdust, kap=kap, relh=relh, &
         nfrac=nfrac, nbcdust=nbcdust, nkap=nkap, nrelh=nrelh, &
         ! hygroscopic table parameters (bulk)
         sw_hygro_ext=sw_hygroscopic_ext, &
         sw_hygro_ssa=sw_hygroscopic_ssa, &
         sw_hygro_asm=sw_hygroscopic_asm, &
         lw_hygro_abs=lw_hygroscopic_ext, &
         ! non-hygroscopic / insoluble table parameters (bulk)
         sw_nonhygro_ext=sw_insoluble_ext, &
         sw_nonhygro_ssa=sw_insoluble_ssa, &
         sw_nonhygro_asm=sw_insoluble_asm, &
         lw_abs=lw_insoluble_ext, &
         ! volcanic radius table parameters (bulk)
         r_sw_ext=r_sw_ext, r_sw_scat=r_sw_scat, &
         r_sw_ascat=r_sw_ascat, r_lw_abs=r_lw_abs, mu=r_mu)
  end subroutine optics_params
Call graph
optics_params calls physprop_get, physprop_id
constructor calls optics_params
create_aerosol_optics_object calls optics_params
hygro_aerosol_optics calls constructor
hygrocoreshell_aerosol_optics calls constructor
hygroscopic_aerosol_optics calls constructor
hygrowghtpct_aerosol_optics calls constructor
insoluble_aerosol_optics calls constructor
refractive_aerosol_optics calls constructor
volcrad_aerosol_optics calls constructor
aerosol_optics_lw_bin calls create_aerosol_optics_object
aerosol_optics_sw_bin calls create_aerosol_optics_object