parse_bin_defs – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
parse_bin_defs Subroutine
192 statements
Source File
public subroutine parse_bin_defs(nl_in, bins)
Uses
cam_logfile
cam_abortutils
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: nl_in(:)
type(bins_t), intent(inout) :: bins
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: iend
integer, private :: ipos
integer, private :: ispec
integer, private :: istat
integer, private :: m
logical, private :: mass_mr_found
integer, private :: mbeg
integer, private :: mcur
integer, private :: nbins
integer, private :: nspec
integer, private :: nstr
logical, private :: num_mr_found
integer, private :: strlen
character(len=*), private, parameter :: subname = 'parse_bin_defs'
character(len=32), private :: tmp_morph
character(len=32), private :: tmp_name_a
character(len=32), private :: tmp_name_c
character(len=1), private :: tmp_src_a
character(len=1), private :: tmp_src_c
character(len=32), private :: tmp_type
character(len=len), private :: tmpstr
Subroutines
subroutine check_bin_morph(str, ib, ie)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer, intent(in) :: ib
integer, intent(in) :: ie
subroutine check_bin_type(str, ib, ie)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer, intent(in) :: ib
integer, intent(in) :: ie
subroutine parse_error(msg, str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: msg
character(len=*), intent(in) :: str
Source Code
subroutine parse_bin_defs(nl_in, bins)
   use cam_abortutils, only: endrun
   use cam_logfile,    only: iulog
   ! Parse the bin definition specifiers.
   character(len=*), intent(inout) :: nl_in(:)    ! namelist input (blanks are removed on output)
   type(bins_t),    intent(inout) :: bins       ! structure containing parsed input
   ! Local variables
   logical :: num_mr_found, mass_mr_found
   integer :: m
   integer :: istat
   integer :: nbins, nstr
   integer :: mbeg, mcur
   integer :: nspec, ispec
   integer :: strlen, iend, ipos
   character(len=*), parameter :: subname = 'parse_bin_defs'
   character(len=len(nl_in(1))) :: tmpstr
   character(len=1)  :: tmp_src_a
   character(len=32) :: tmp_name_a
   character(len=1)  :: tmp_src_c
   character(len=32) :: tmp_name_c
   character(len=32) :: tmp_type
   character(len=32) :: tmp_morph
   !-------------------------------------------------------------------------
   ! Determine number of bins defined by counting number of strings that are
   ! terminated by ':='
   ! (algorithm stops counting at first blank element).
   nbins = 0
   nstr = 0
   do m = 1, n_bin_str
      if (len_trim(nl_in(m)) == 0) exit
      nstr = nstr + 1
      ! There are no fields in the input strings in which a blank character is allowed.
      ! To simplify the parsing go through the input strings and remove blanks.
      tmpstr = adjustl(nl_in(m))
      nl_in(m) = tmpstr
      do
         strlen = len_trim(nl_in(m))
         ipos = index(nl_in(m), ' ')
         if (ipos == 0 .or. ipos > strlen) exit
         tmpstr = nl_in(m)(:ipos-1) // nl_in(m)(ipos+1:strlen)
         nl_in(m) = tmpstr
      end do
      ! count strings with ':=' terminator
      if (nl_in(m)(strlen-1:strlen) == ':=') nbins = nbins + 1
   end do
   bins%nbins = nbins
   ! return if no bins defined
   if (nbins == 0) return
   ! allocate components that depend on nmodes
   allocate( &
      bins%names(nbins),  &
      bins%comps(nbins),  &
      stat=istat )
   if (istat > 0) then
      write(iulog,*) subname//': ERROR: cannot allocate storage for bins.  nbins=', nbins
      call endrun(subname//': ERROR allocating storage for bins')
   end if
   mcur = 1              ! index of current string being processed
   ! loop over bins
   bins_loop: do m = 1, nbins
      mbeg = mcur  ! remember the first string of a bin
      ! check that first string in bin definition is ':=' terminated
      iend = len_trim(nl_in(mcur))
      if (nl_in(mcur)(iend-1:iend) /= ':=') call parse_error('= not found', nl_in(mcur))
      ! count species in bin definition.  definition will contain 1 string with
      ! with a ':+' terminator for each specie
      nspec = 0
      mcur = mcur + 1
      do
         iend = len_trim(nl_in(mcur))
         if (nl_in(mcur)(iend-1:iend) /=    ':+') exit
         if (nl_in(mcur)(iend-4:iend) /= 'mmr:+') nspec = nspec + 1
         mcur = mcur + 1
      end do
      ! a bin must have at least one specie
      if (nspec == 0) call parse_error('bin must have at least one specie', nl_in(mbeg))
      ! allocate components that depend on number of species
      allocate( &
         bins%comps(m)%source_mmr_a(nspec),  &
         bins%comps(m)%camname_mmr_a(nspec), &
         bins%comps(m)%source_mmr_c(nspec),  &
         bins%comps(m)%camname_mmr_c(nspec), &
         bins%comps(m)%type(nspec),          &
         bins%comps(m)%morph(nspec),          &
         bins%comps(m)%props(nspec),         &
         stat=istat)
      if (istat > 0) then
         write(iulog,*) subname//': ERROR: cannot allocate storage for species.  nspec=', nspec
         call endrun(subname//': ERROR allocating storage for species')
      end if
      ! initialize components
      bins%comps(m)%nspec         = nspec
      bins%comps(m)%source_num_a  = ' '
      bins%comps(m)%camname_num_a = ' '
      bins%comps(m)%source_num_c  = ' '
      bins%comps(m)%camname_num_c = ' '
      bins%comps(m)%source_mass_a  = 'NOTSET'
      bins%comps(m)%camname_mass_a = 'NOTSET'
      bins%comps(m)%source_mass_c  = 'NOTSET'
      bins%comps(m)%camname_mass_c = 'NOTSET'
      do ispec = 1, nspec
         bins%comps(m)%source_mmr_a(ispec)  = ' '
         bins%comps(m)%camname_mmr_a(ispec) = ' '
         bins%comps(m)%source_mmr_c(ispec)  = ' '
         bins%comps(m)%camname_mmr_c(ispec) = ' '
         bins%comps(m)%type(ispec)          = ' '
         bins%comps(m)%props(ispec)         = ' '
      end do
      ! return to first string in mode definition
      mcur = mbeg
      tmpstr = nl_in(mcur)
      ! bin name
      ipos = index(tmpstr, ':')
      if (ipos < 2) call parse_error('bin name not found', tmpstr)
      bins%names(m)  = tmpstr(:ipos-1)
      tmpstr         = tmpstr(ipos+1:)
      ! bin name must be followed by '='
      if (tmpstr(1:1) /= '=') call parse_error('= not found', tmpstr)
      ! move to next string
      mcur = mcur + 1
      tmpstr = nl_in(mcur)
      ! process bin component strings
      num_mr_found = .false.        ! keep track of whether number mixing ratio component is found
      mass_mr_found = .false.       ! keep track of whether number mixing ratio component is found
      ispec = 0                     ! keep track of the number of species found
      comps_loop: do
         ! source of interstitial component
         ipos = index(tmpstr, ':')
         if (ipos < 2) call parse_error('expect to find source field first', tmpstr)
         ! check for valid source
         if (tmpstr(:ipos-1) /= 'A' .and. tmpstr(:ipos-1) /= 'N' .and. tmpstr(:ipos-1) /= 'Z') &
            call parse_error('source must be A, N or Z', tmpstr)
         tmp_src_a = tmpstr(:ipos-1)
         tmpstr    = tmpstr(ipos+1:)
         ! name of interstitial component
         ipos = index(tmpstr, ':')
         if (ipos == 0) call parse_error('next separator not found', tmpstr)
         tmp_name_a = tmpstr(:ipos-1)
         tmpstr     = tmpstr(ipos+1:)
         ! source of cloud borne component
         ipos = index(tmpstr, ':')
         if (ipos < 2) call parse_error('expect to find a source field', tmpstr)
         ! check for valid source
         if (tmpstr(:ipos-1) /= 'A' .and. tmpstr(:ipos-1) /= 'N' .and. tmpstr(:ipos-1) /= 'Z') &
            call parse_error('source must be A, N or Z', tmpstr)
         tmp_src_c = tmpstr(:ipos-1)
         tmpstr    = tmpstr(ipos+1:)
         ! name of cloud borne component
         ipos = index(tmpstr, ':')
         if (ipos == 0) call parse_error('next separator not found', tmpstr)
         tmp_name_c = tmpstr(:ipos-1)
         tmpstr     = tmpstr(ipos+1:)
         ! component type
         ipos = scan(tmpstr, ': ')
         if (ipos == 0) call parse_error('next separator not found', tmpstr)
         if (tmpstr(:ipos-1) == 'num') then
            ! there can only be one number mixing ratio component
            if (num_mr_found) call parse_error('more than 1 number component', nl_in(mcur))
            num_mr_found = .true.
            bins%comps(m)%source_num_a  = tmp_src_a
            bins%comps(m)%camname_num_a = tmp_name_a
            bins%comps(m)%source_num_c  = tmp_src_c
            bins%comps(m)%camname_num_c = tmp_name_c
            tmpstr                      = tmpstr(ipos+1:)
         else if (tmpstr(:ipos-1) == 'mmr') then
            ! there can only be one number mixing ratio component
            if (mass_mr_found) call parse_error('more than 1 mass mixing ratio component', nl_in(mcur))
            mass_mr_found = .true.
            bins%comps(m)%source_mass_a  = tmp_src_a
            bins%comps(m)%camname_mass_a = tmp_name_a
            bins%comps(m)%source_mass_c  = tmp_src_c
            bins%comps(m)%camname_mass_c = tmp_name_c
            tmpstr                       = tmpstr(ipos+1:)
         else
            ! check for valid species type
            call check_bin_type(tmpstr, 1, ipos-1)
            tmp_type = tmpstr(:ipos-1)
            tmpstr   = tmpstr(ipos+1:)
            ipos = index(tmpstr, ':')
            if (ipos == 0) call parse_error('next separator not found', tmpstr)
            ! check for valid species type
            call check_bin_morph(tmpstr, 1, ipos-1)
            tmp_morph = tmpstr(:ipos-1)
            tmpstr   = tmpstr(ipos+1:)
            ! get the properties file
            ipos = scan(tmpstr, ': ')
            if (ipos == 0) call parse_error('next separator not found', tmpstr)
             ! check for valid filename -- must have .nc extension
            if (tmpstr(ipos-3:ipos-1) /= '.nc') &
               call parse_error('filename not valid', tmpstr)
            ispec = ispec + 1
            bins%comps(m)%source_mmr_a(ispec)  = tmp_src_a
            bins%comps(m)%camname_mmr_a(ispec) = tmp_name_a
            bins%comps(m)%source_mmr_c(ispec)  = tmp_src_c
            bins%comps(m)%camname_mmr_c(ispec) = tmp_name_c
            bins%comps(m)%type(ispec)          = tmp_type
            bins%comps(m)%morph(ispec)         = tmp_morph
            bins%comps(m)%props(ispec)         = tmpstr(:ipos-1)
            tmpstr                             = tmpstr(ipos+1:)
         endif
         ! check if there are more components.  either the current character is
         ! a ' ' which means this string is the final mode component, or the character
         ! is a '+' which means there are more components
         if (tmpstr(1:1) == ' ') then
            exit comps_loop
         endif
         if (tmpstr(1:1) /= '+') &
               call parse_error('+ field not found', tmpstr)
         ! continue to next component...
         mcur = mcur + 1
         tmpstr = nl_in(mcur)
      end do comps_loop
      ! check that a number component was found
      if (.not. num_mr_found) call parse_error('number component not found', nl_in(mbeg))
      ! check that the right number of species were found
      if (ispec /= nspec) then
         write(*,*) 'ispec, nspec = ',ispec, nspec
         call parse_error('component parsing got wrong number of species', nl_in(mbeg))
      endif
      ! continue to next bin...
      mcur = mcur + 1
      tmpstr = nl_in(mcur)
   end do bins_loop
   !------------------------------------------------------------------------------------------------
   contains
   !------------------------------------------------------------------------------------------------
   subroutine parse_error(msg, str)
      character(len=*), intent(in) :: msg
      character(len=*), intent(in) :: str
      write(iulog,*) subname//': ERROR: '//msg
      write(iulog,*) ' input string: '//trim(str)
      call endrun(subname//': ERROR: '//msg)
   end subroutine parse_error
   !------------------------------------------------------------------------------------------------
   subroutine check_bin_morph(str, ib, ie)
      character(len=*), intent(in) :: str
      integer,          intent(in) :: ib, ie
      integer :: i
      do i = 1, num_bin_morphs
         if (str(ib:ie) == trim(bin_morph_names(i))) return
      end do
      call parse_error('bin morph not valid', str(ib:ie))
   end subroutine check_bin_morph
   !------------------------------------------------------------------------------------------------
   subroutine check_bin_type(str, ib, ie)
      character(len=*), intent(in) :: str
      integer,          intent(in) :: ib, ie  ! begin, end character of mode type substring
      integer :: i
      do i = 1, num_spec_types
         if (str(ib:ie) == trim(spec_type_names(i))) return
      end do
      call parse_error('bin species type not valid', str(ib:ie))
   end subroutine check_bin_type
   !------------------------------------------------------------------------------------------------
end subroutine parse_bin_defs
Call graph
parse_bin_defs calls endrun, check_bin_morph, check_bin_type, parse_error
rad_aer_readnl calls parse_bin_defs