rad_aer_readnl – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rad_aer_readnl Subroutine
53 statements
Source File
public subroutine rad_aer_readnl(mode_defs, bin_defs)
Uses
radiative_aerosol_definitions
shr_kind_mod
phys_prop
spmd_utils
Arguments
Type Intent Optional Attributes Name
character(len=shr_kind_cl), intent(inout) :: mode_defs(:)
character(len=shr_kind_cl), intent(inout) :: bin_defs(:)
Calls
Variables
Type Visibility Attributes Name Initial
character(len=1), private, pointer :: ctype(:)
integer, private :: i
character(len=*), private, parameter :: subname = 'rad_aer_readnl'
character(len=2), private :: suffix
Source Code
subroutine rad_aer_readnl(mode_defs, bin_defs)
   use shr_kind_mod,   only: shr_kind_cl
   use phys_prop,      only: physprop_accum_unique_files
   use spmd_utils,     only: masterproc
   use radiative_aerosol_definitions, only: &
      verbose, N_DIAG, modes, bins, &
      active_calls, bulk_aerosol_list, modal_aerosol_list, sectional_aerosol_list, &
      radcnst_namelist, parse_mode_defs, parse_bin_defs, &
      list_populate, print_modes, print_bins
   ! Arguments
   character(len=shr_kind_cl), intent(inout) :: mode_defs(:)
   character(len=shr_kind_cl), intent(inout) :: bin_defs(:)
   ! Local variables
   integer :: i
   character(len=2) :: suffix
   character(len=1), pointer   :: ctype(:)
   character(len=*), parameter :: subname = 'rad_aer_readnl'
   !-----------------------------------------------------------------------------
   ! Parse mode definition strings
   call parse_mode_defs(mode_defs, modes)
   ! Parse bin definition strings
   call parse_bin_defs(bin_defs, bins)
   ! Set the list_id fields for aerosol lists
   do i = 0, N_DIAG
      if (active_calls(i)) then
         if (i > 0) then
            write(suffix, fmt = '(i2.2)') i
         else
            suffix='  '
         end if
         bulk_aerosol_list(i)%list_id      = suffix
         modal_aerosol_list(i)%list_id     = suffix
         sectional_aerosol_list(i)%list_id = suffix
      end if
   end do
   ! Accumulate unique physprop files for bulk aerosol species
   do i = 0, N_DIAG
      if (active_calls(i)) then
         call physprop_accum_unique_files(radcnst_namelist(i)%radname, radcnst_namelist(i)%type)
      endif
   enddo
   ! Accumulate physprop files for mode species
   do i = 1, modes%nmodes
      allocate(ctype(modes%comps(i)%nspec))
      ctype = 'A'
      call physprop_accum_unique_files(modes%comps(i)%props, ctype)
      deallocate(ctype)
   end do
   ! Accumulate physprop files for bin species
   do i = 1, bins%nbins
      allocate(ctype(bins%comps(i)%nspec))
      ctype = 'A'
      call physprop_accum_unique_files(bins%comps(i)%props, ctype)
      deallocate(ctype)
   end do
   ! Initialize aerosol lists (populate from namelist specifiers)
   do i = 0, N_DIAG
      if (active_calls(i)) then
         ! has to be done at readnl phase as information on structure of the lists will be needed
         ! in physics/chemistry initialization.
         call list_populate(radcnst_namelist(i), bulk_aerosol_list(i), modal_aerosol_list(i), sectional_aerosol_list(i))
         if (masterproc .and. verbose) then
            call print_aerosol_lists(bulk_aerosol_list(i), modal_aerosol_list(i), sectional_aerosol_list(i))
         end if
      end if
   end do
   if (masterproc .and. verbose) call print_modes(modes)
   if (masterproc .and. verbose) call print_bins(bins)
end subroutine rad_aer_readnl
Call graph
rad_aer_readnl calls physprop_accum_unique_files, list_populate, parse_bin_defs, parse_mode_defs, print_aerosol_lists, print_bins, print_modes
list_populate calls endrun
parse_bin_defs calls endrun, check_bin_morph, check_bin_type, parse_error
parse_mode_defs calls endrun, check_mode_type, check_specie_type, parse_error