rad_aer_init – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rad_aer_init Subroutine
18 statements
Source File
public subroutine rad_aer_init()
Uses
aerosol_mmr_cam
phys_prop
radiative_aerosol_definitions
Arguments
None
Calls
Variables
Type Visibility Attributes Name Initial
integer, private :: i
character(len=*), private, parameter :: subname = 'rad_aer_init'
Source Code
subroutine rad_aer_init()
   use phys_prop,      only: physprop_init
   use radiative_aerosol_definitions, only: &
      N_DIAG, modes, bins, active_calls, &
      bulk_aerosol_list, modal_aerosol_list, sectional_aerosol_list, list_resolve_physprops
   !REMOVECAM: aerosol_mmr_cam handles CAM-specific index resolution
   use aerosol_mmr_cam, only: aerosol_mmr_init, &
      resolve_mode_idx, resolve_bin_idx, resolve_bulk_idx, &
      rad_aer_diag_init
   !REMOVECAM_END
   integer :: i
   character(len=*), parameter :: subname = 'rad_aer_init'
   !-----------------------------------------------------------------------------
   ! Initialize a zero target for the 'Z' type of aerosol MMR.
   call aerosol_mmr_init()
   ! Read physical properties from data files
   call physprop_init()
   !REMOVECAM: resolve host-specific indices (CAM uses pbuf and state)
   call resolve_mode_idx(modes)
   call resolve_bin_idx(bins)
   !REMOVECAM_END
   ! Resolve physprop indices for aerosol lists
   do i = 0, N_DIAG
      if (active_calls(i)) then
         !REMOVECAM: resolve host-specific indices (CAM uses pbuf and state)
         call resolve_bulk_idx(bulk_aerosol_list(i))
         !REMOVECAM_END
         call list_resolve_physprops(bulk_aerosol_list(i), modal_aerosol_list(i), sectional_aerosol_list(i))
      end if
   end do
   !REMOVECAM: history add calls for radiative aerosol diagnostics.
   call rad_aer_diag_init(bulk_aerosol_list(0))
   !REMOVECAM_END
end subroutine rad_aer_init
Call graph
rad_aer_init calls aerosol_mmr_init, physprop_init, list_resolve_physprops, rad_aer_diag_init, resolve_bin_idx, resolve_bulk_idx, resolve_mode_idx
list_resolve_physprops calls physprop_get_id