rad_aer_get_info_by_bin_spec – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rad_aer_get_info_by_bin_spec Subroutine
40 statements
Source File
public subroutine rad_aer_get_info_by_bin_spec(list_idx, m_idx, s_idx, spec_type, spec_morph, spec_name, spec_name_cw)
Uses
radiative_aerosol_definitions
cam_logfile
cam_abortutils
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
integer, intent(in) :: m_idx
integer, intent(in) :: s_idx
character(len=32), intent(out), optional :: spec_type
character(len=32), intent(out), optional :: spec_morph
character(len=32), intent(out), optional :: spec_name
character(len=32), intent(out), optional :: spec_name_cw
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: mm
integer, private :: nbins
integer, private :: nspec
type(binlist_t), private, pointer :: s_list
character(len=*), private, parameter :: subname = 'rad_aer_get_info_by_bin_spec'
Source Code
subroutine rad_aer_get_info_by_bin_spec(list_idx, m_idx, s_idx, &
   spec_type, spec_morph, spec_name, spec_name_cw)
   use cam_abortutils, only: endrun
   use cam_logfile,    only: iulog
   use radiative_aerosol_definitions, only: binlist_t, sectional_aerosol_list, bins
   ! Return info about CARMA aerosol lists
   ! Arguments
   integer,                     intent(in)  :: list_idx    ! index of the climate or a diagnostic list
   integer,                     intent(in)  :: m_idx       ! index of bin in the specified list
   integer,                     intent(in)  :: s_idx       ! index of species in the specified mode
   character(len=32), optional, intent(out) :: spec_type   ! type of species
   character(len=32), optional, intent(out) :: spec_morph  ! type of species
   character(len=32), optional, intent(out) :: spec_name   ! name of interstitial species
   character(len=32), optional, intent(out) :: spec_name_cw ! name of cloud borne species
   ! Local variables
   type(binlist_t), pointer :: s_list ! local pointer to mode list of interest
   integer          :: nbins,  nspec
   integer          :: mm
   character(len=*), parameter :: subname = 'rad_aer_get_info_by_bin_spec'
   !-----------------------------------------------------------------------------
   s_list => sectional_aerosol_list(list_idx)
   ! check for valid mode index
   nbins = s_list%nbins
   if (m_idx < 1 .or. m_idx > nbins) then
      write(iulog,*) subname//': ERROR - invalid bin index: ', m_idx
      call endrun(subname//': ERROR - invalid bin index')
   end if
   ! get index into the mode definition object
   mm = s_list%idx(m_idx)
   ! check for valid species index
   nspec = bins%comps(mm)%nspec
   if (s_idx < 1 .or. s_idx > nspec) then
      write(iulog,*) subname//': ERROR - invalid specie index: ', s_idx
      call endrun(subname//': ERROR - invalid specie index')
   end if
   if (present(spec_type)) then
      spec_type = bins%comps(mm)%type(s_idx)
   endif
   if (present(spec_morph)) then
      spec_morph = bins%comps(mm)%morph(s_idx)
   endif
   if (present(spec_name)) then
      spec_name = bins%comps(mm)%camname_mmr_a(s_idx)
   endif
   if (present(spec_name_cw)) then
      spec_name_cw = bins%comps(mm)%camname_mmr_c(s_idx)
   endif
end subroutine rad_aer_get_info_by_bin_spec
Call graph
rad_aer_get_info_by_bin_spec calls endrun
amb_mmr_name calls rad_aer_get_info_by_bin_spec
get calls rad_aer_get_info_by_bin_spec
mmr_names calls rad_aer_get_info_by_bin_spec
species_type calls rad_aer_get_info_by_bin_spec
constructor calls species_type
hetfrz_species calls species_type
icenuc_updates_mmr calls species_type, icenuc_updates_num
icenuc_updates_num calls species_type
rebin_bulk_fluxes calls get
scav_diam calls get, species_type
carma_aerosol_properties calls constructor