rad_aer_get_bin_props_by_idx – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rad_aer_get_bin_props_by_idx Subroutine
81 statements
Source File
public subroutine rad_aer_get_bin_props_by_idx(list_idx, bin_idx, spec_idx, opticstype, sw_hygro_ext, sw_hygro_ssa, sw_hygro_asm, lw_hygro_ext, sw_nonhygro_ext, sw_nonhygro_ssa, sw_nonhygro_asm, sw_nonhygro_scat, sw_nonhygro_ascat, lw_ext, refindex_aer_sw, refindex_aer_lw, r_sw_ext, r_sw_scat, r_sw_ascat, r_lw_abs, mu, aername, density_aer, hygro_aer, dryrad_aer, dispersion_aer, num_to_mass_aer, spectype, specmorph)
Uses
cam_logfile
radiative_aerosol_definitions
cam_abortutils
shr_kind_mod
phys_prop
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
integer, intent(in) :: bin_idx
integer, intent(in) :: spec_idx
character(len=ot_length), intent(out), optional :: opticstype
real(kind=r8), optional, pointer :: sw_hygro_ext(:,:)
real(kind=r8), optional, pointer :: sw_hygro_ssa(:,:)
real(kind=r8), optional, pointer :: sw_hygro_asm(:,:)
real(kind=r8), optional, pointer :: lw_hygro_ext(:,:)
real(kind=r8), optional, pointer :: sw_nonhygro_ext(:)
real(kind=r8), optional, pointer :: sw_nonhygro_ssa(:)
real(kind=r8), optional, pointer :: sw_nonhygro_asm(:)
real(kind=r8), optional, pointer :: sw_nonhygro_scat(:)
real(kind=r8), optional, pointer :: sw_nonhygro_ascat(:)
real(kind=r8), optional, pointer :: lw_ext(:)
complex(kind=r8), optional, pointer :: refindex_aer_sw(:)
complex(kind=r8), optional, pointer :: refindex_aer_lw(:)
real(kind=r8), optional, pointer :: r_sw_ext(:,:)
real(kind=r8), optional, pointer :: r_sw_scat(:,:)
real(kind=r8), optional, pointer :: r_sw_ascat(:,:)
real(kind=r8), optional, pointer :: r_lw_abs(:,:)
real(kind=r8), optional, pointer :: mu(:)
character(len=20), intent(out), optional :: aername
real(kind=r8), intent(out), optional :: density_aer
real(kind=r8), intent(out), optional :: hygro_aer
real(kind=r8), intent(out), optional :: dryrad_aer
real(kind=r8), intent(out), optional :: dispersion_aer
real(kind=r8), intent(out), optional :: num_to_mass_aer
character(len=32), intent(out), optional :: spectype
character(len=32), intent(out), optional :: specmorph
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: idx
integer, private :: m_idx
type(binlist_t), private, pointer :: slist
character(len=*), private, parameter :: subname = 'rad_aer_get_bin_props_by_idx'
Source Code
subroutine rad_aer_get_bin_props_by_idx(list_idx, &
   bin_idx, spec_idx,  opticstype, &
   sw_hygro_ext, sw_hygro_ssa, sw_hygro_asm, lw_hygro_ext, &
   sw_nonhygro_ext, sw_nonhygro_ssa, sw_nonhygro_asm, &
   sw_nonhygro_scat, sw_nonhygro_ascat, lw_ext, &
   refindex_aer_sw, refindex_aer_lw, &
   r_sw_ext, r_sw_scat, r_sw_ascat, r_lw_abs, mu, &
   aername, density_aer, hygro_aer, dryrad_aer, dispersion_aer, &
   num_to_mass_aer, spectype, specmorph)
   use shr_kind_mod,   only: r8 => shr_kind_r8
   use phys_prop,      only: physprop_get, ot_length
   use cam_abortutils, only: endrun
   use cam_logfile,    only: iulog
   use radiative_aerosol_definitions, only: N_DIAG, binlist_t, sectional_aerosol_list, bins
   ! Return requested properties for the aerosol from the specified
   ! climate or diagnostic list.
   ! Arguments
   integer,                     intent(in)  :: list_idx  ! index of the climate or a diagnostic list
   integer,                     intent(in)  :: bin_idx   ! mode index
   integer,                     intent(in)  :: spec_idx  ! index of specie in the mode
   character(len=ot_length), optional, intent(out) :: opticstype
   real(r8),          optional, pointer     :: sw_hygro_ext(:,:)
   real(r8),          optional, pointer     :: sw_hygro_ssa(:,:)
   real(r8),          optional, pointer     :: sw_hygro_asm(:,:)
   real(r8),          optional, pointer     :: lw_hygro_ext(:,:)
   real(r8),          optional, pointer     :: sw_nonhygro_ext(:)
   real(r8),          optional, pointer     :: sw_nonhygro_ssa(:)
   real(r8),          optional, pointer     :: sw_nonhygro_asm(:)
   real(r8),          optional, pointer     :: sw_nonhygro_scat(:)
   real(r8),          optional, pointer     :: sw_nonhygro_ascat(:)
   real(r8),          optional, pointer     :: lw_ext(:)
   complex(r8),       optional, pointer     :: refindex_aer_sw(:)
   complex(r8),       optional, pointer     :: refindex_aer_lw(:)
   real(r8),          optional, pointer     :: r_sw_ext(:,:)
   real(r8),          optional, pointer     :: r_sw_scat(:,:)
   real(r8),          optional, pointer     :: r_sw_ascat(:,:)
   real(r8),          optional, pointer     :: r_lw_abs(:,:)
   real(r8),          optional, pointer     :: mu(:)
   character(len=20), optional, intent(out) :: aername
   real(r8),          optional, intent(out) :: density_aer
   real(r8),          optional, intent(out) :: hygro_aer
   real(r8),          optional, intent(out) :: dryrad_aer
   real(r8),          optional, intent(out) :: dispersion_aer
   real(r8),          optional, intent(out) :: num_to_mass_aer
   character(len=32), optional, intent(out) :: spectype
   character(len=32), optional, intent(out) :: specmorph
   ! Local variables
   integer :: m_idx, idx
   type(binlist_t), pointer :: slist
   character(len=*), parameter :: subname = 'rad_aer_get_bin_props_by_idx'
   !------------------------------------------------------------------------------------
   if (list_idx >= 0 .and. list_idx <= N_DIAG) then
      slist => sectional_aerosol_list(list_idx)
   else
      write(iulog,*) subname//': list_idx = ', list_idx
      call endrun(subname//': list_idx out of range')
   endif
   ! Check for valid mode index
   if (bin_idx < 1  .or.  bin_idx > slist%nbins) then
      write(iulog,*) subname//': bin_idx= ', bin_idx, '  nbins= ', slist%nbins
      call endrun(subname//': bin list index out of range')
   end if
   ! Get the index for the corresponding mode in the mode definition object
   m_idx = slist%idx(bin_idx)
   ! Check for valid specie index
   if (spec_idx < 1  .or.  spec_idx > bins%comps(m_idx)%nspec) then
      write(iulog,*) subname//': spec_idx= ', spec_idx, '  nspec= ', bins%comps(m_idx)%nspec
      call endrun(subname//': specie list index out of range')
   end if
   idx = bins%comps(m_idx)%idx_props(spec_idx)
   if (present(opticstype))        call physprop_get(idx, opticstype=opticstype)
   if (present(sw_hygro_ext))      call physprop_get(idx, sw_hygro_ext=sw_hygro_ext)
   if (present(sw_hygro_ssa))      call physprop_get(idx, sw_hygro_ssa=sw_hygro_ssa)
   if (present(sw_hygro_asm))      call physprop_get(idx, sw_hygro_asm=sw_hygro_asm)
   if (present(lw_hygro_ext))      call physprop_get(idx, lw_hygro_abs=lw_hygro_ext)
   if (present(sw_nonhygro_ext))   call physprop_get(idx, sw_nonhygro_ext=sw_nonhygro_ext)
   if (present(sw_nonhygro_ssa))   call physprop_get(idx, sw_nonhygro_ssa=sw_nonhygro_ssa)
   if (present(sw_nonhygro_asm))   call physprop_get(idx, sw_nonhygro_asm=sw_nonhygro_asm)
   if (present(sw_nonhygro_scat))  call physprop_get(idx, sw_nonhygro_scat=sw_nonhygro_scat)
   if (present(sw_nonhygro_ascat)) call physprop_get(idx, sw_nonhygro_ascat=sw_nonhygro_ascat)
   if (present(lw_ext))            call physprop_get(idx, lw_abs=lw_ext)
   if (present(refindex_aer_sw))   call physprop_get(idx, refindex_aer_sw=refindex_aer_sw)
   if (present(refindex_aer_lw))   call physprop_get(idx, refindex_aer_lw=refindex_aer_lw)
   if (present(r_lw_abs))          call physprop_get(idx, r_lw_abs=r_lw_abs)
   if (present(r_sw_ext))          call physprop_get(idx, r_sw_ext=r_sw_ext)
   if (present(r_sw_scat))         call physprop_get(idx, r_sw_scat=r_sw_scat)
   if (present(r_sw_ascat))        call physprop_get(idx, r_sw_ascat=r_sw_ascat)
   if (present(mu))                call physprop_get(idx, mu=mu)
   if (present(aername))           call physprop_get(idx, aername=aername)
   if (present(density_aer))       call physprop_get(idx, density_aer=density_aer)
   if (present(hygro_aer))         call physprop_get(idx, hygro_aer=hygro_aer)
   if (present(dryrad_aer))        call physprop_get(idx, dryrad_aer=dryrad_aer)
   if (present(dispersion_aer))    call physprop_get(idx, dispersion_aer=dispersion_aer)
   if (present(num_to_mass_aer))   call physprop_get(idx, num_to_mass_aer=num_to_mass_aer)
   if (present(spectype)) spectype = bins%comps(m_idx)%type(spec_idx)
   if (present(specmorph)) specmorph = bins%comps(m_idx)%morph(spec_idx)
end subroutine rad_aer_get_bin_props_by_idx
Call graph
rad_aer_get_bin_props_by_idx calls endrun, physprop_get
get calls rad_aer_get_bin_props_by_idx
rebin_bulk_fluxes calls get
scav_diam calls get