rad_aer_get_info_by_mode_spec – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rad_aer_get_info_by_mode_spec Subroutine
37 statements
Source File
public subroutine rad_aer_get_info_by_mode_spec(list_idx, m_idx, s_idx, spec_type, spec_name, spec_name_cw)
Uses
radiative_aerosol_definitions
cam_logfile
cam_abortutils
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
integer, intent(in) :: m_idx
integer, intent(in) :: s_idx
character(len=32), intent(out), optional :: spec_type
character(len=32), intent(out), optional :: spec_name
character(len=32), intent(out), optional :: spec_name_cw
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(modelist_t), private, pointer :: m_list
integer, private :: mm
integer, private :: nmodes
integer, private :: nspec
character(len=*), private, parameter :: subname = 'rad_aer_get_info_by_mode_spec'
Source Code
subroutine rad_aer_get_info_by_mode_spec(list_idx, m_idx, s_idx, &
   spec_type, spec_name, spec_name_cw)
   use cam_abortutils, only: endrun
   use cam_logfile,    only: iulog
   use radiative_aerosol_definitions, only: modelist_t, modal_aerosol_list, modes
   ! Return info about modal aerosol lists
   ! Arguments
   integer,                     intent(in)  :: list_idx    ! index of the climate or a diagnostic list
   integer,                     intent(in)  :: m_idx       ! index of mode in the specified list
   integer,                     intent(in)  :: s_idx       ! index of specie in the specified mode
   character(len=32), optional, intent(out) :: spec_type   ! type of specie
   character(len=32), optional, intent(out) :: spec_name   ! name of interstitial specie
   character(len=32), optional, intent(out) :: spec_name_cw ! name of cloud borne specie
   ! Local variables
   type(modelist_t), pointer :: m_list ! local pointer to mode list of interest
   integer          :: nmodes
   integer          :: nspec
   integer          :: mm
   character(len=*), parameter :: subname = 'rad_aer_get_info_by_mode_spec'
   !-----------------------------------------------------------------------------
   m_list => modal_aerosol_list(list_idx)
   ! check for valid mode index
   nmodes = m_list%nmodes
   if (m_idx < 1 .or. m_idx > nmodes) then
      write(iulog,*) subname//': ERROR - invalid mode index: ', m_idx
      call endrun(subname//': ERROR - invalid mode index')
   end if
   ! get index into the mode definition object
   mm = m_list%idx(m_idx)
   ! check for valid specie index
   nspec = modes%comps(mm)%nspec
   if (s_idx < 1 .or. s_idx > nspec) then
      write(iulog,*) subname//': ERROR - invalid specie index: ', s_idx
      call endrun(subname//': ERROR - invalid specie index')
   end if
   ! specie type
   if (present(spec_type)) then
      spec_type = modes%comps(mm)%type(s_idx)
   endif
   ! interstitial specie name
   if (present(spec_name)) then
      spec_name = modes%comps(mm)%camname_mmr_a(s_idx)
   endif
   ! cloud borne specie name
   if (present(spec_name_cw)) then
      spec_name_cw = modes%comps(mm)%camname_mmr_c(s_idx)
   endif
end subroutine rad_aer_get_info_by_mode_spec
Call graph
rad_aer_get_info_by_mode_spec calls endrun
rad_aer_get_info calls rad_aer_get_info_by_mode_spec, rad_aer_get_info