rad_aer_get_mode_props – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rad_aer_get_mode_props Subroutine
59 statements
Source File
public subroutine rad_aer_get_mode_props(list_idx, mode_idx, opticstype, extpsw, abspsw, asmpsw, absplw, refrtabsw, refitabsw, refrtablw, refitablw, ncoef, prefr, prefi, sigmag, dgnum, dgnumlo, dgnumhi, rhcrystal, rhdeliques)
Uses
shr_kind_mod
phys_prop
cam_abortutils
cam_logfile
radiative_aerosol_definitions
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
integer, intent(in) :: mode_idx
character(len=ot_length), intent(out), optional :: opticstype
real(kind=r8), optional, pointer :: extpsw(:,:,:,:)
real(kind=r8), optional, pointer :: abspsw(:,:,:,:)
real(kind=r8), optional, pointer :: asmpsw(:,:,:,:)
real(kind=r8), optional, pointer :: absplw(:,:,:,:)
real(kind=r8), optional, pointer :: refrtabsw(:,:)
real(kind=r8), optional, pointer :: refitabsw(:,:)
real(kind=r8), optional, pointer :: refrtablw(:,:)
real(kind=r8), optional, pointer :: refitablw(:,:)
integer, intent(out), optional :: ncoef
integer, intent(out), optional :: prefr
integer, intent(out), optional :: prefi
real(kind=r8), intent(out), optional :: sigmag
real(kind=r8), intent(out), optional :: dgnum
real(kind=r8), intent(out), optional :: dgnumlo
real(kind=r8), intent(out), optional :: dgnumhi
real(kind=r8), intent(out), optional :: rhcrystal
real(kind=r8), intent(out), optional :: rhdeliques
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: idx
type(modelist_t), private, pointer :: mlist
character(len=*), private, parameter :: subname = 'rad_aer_get_mode_props'
Source Code
subroutine rad_aer_get_mode_props(list_idx, mode_idx, opticstype, &
   extpsw, abspsw, asmpsw, absplw, refrtabsw, &
   refitabsw, refrtablw, refitablw, ncoef, prefr, &
   prefi, sigmag, dgnum, dgnumlo, dgnumhi, &
   rhcrystal, rhdeliques)
   use shr_kind_mod,   only: r8 => shr_kind_r8
   use phys_prop,      only: physprop_get, ot_length
   use cam_abortutils, only: endrun
   use cam_logfile,    only: iulog
   use radiative_aerosol_definitions, only: N_DIAG, modelist_t, modal_aerosol_list
   ! Return requested properties for the mode from the specified
   ! climate or diagnostic list.
   ! Arguments
   integer,             intent(in)  :: list_idx  ! index of the climate or a diagnostic list
   integer,             intent(in)  :: mode_idx  ! mode index
   character(len=ot_length), optional, intent(out) :: opticstype
   real(r8),  optional, pointer     :: extpsw(:,:,:,:)
   real(r8),  optional, pointer     :: abspsw(:,:,:,:)
   real(r8),  optional, pointer     :: asmpsw(:,:,:,:)
   real(r8),  optional, pointer     :: absplw(:,:,:,:)
   real(r8),  optional, pointer     :: refrtabsw(:,:)
   real(r8),  optional, pointer     :: refitabsw(:,:)
   real(r8),  optional, pointer     :: refrtablw(:,:)
   real(r8),  optional, pointer     :: refitablw(:,:)
   integer,   optional, intent(out) :: ncoef
   integer,   optional, intent(out) :: prefr
   integer,   optional, intent(out) :: prefi
   real(r8),  optional, intent(out) :: sigmag
   real(r8),  optional, intent(out) :: dgnum
   real(r8),  optional, intent(out) :: dgnumlo
   real(r8),  optional, intent(out) :: dgnumhi
   real(r8),  optional, intent(out) :: rhcrystal
   real(r8),  optional, intent(out) :: rhdeliques
   ! Local variables
   integer :: idx
   type(modelist_t), pointer :: mlist
   character(len=*), parameter :: subname = 'rad_aer_get_mode_props'
   !------------------------------------------------------------------------------------
   if (list_idx >= 0 .and. list_idx <= N_DIAG) then
      mlist => modal_aerosol_list(list_idx)
   else
      write(iulog,*) subname//': list_idx = ', list_idx
      call endrun(subname//': list_idx out of range')
   endif
   ! Check for valid mode index
   if (mode_idx < 1  .or.  mode_idx > mlist%nmodes) then
      write(iulog,*) subname//': mode_idx= ', mode_idx, '  nmodes= ', mlist%nmodes
      call endrun(subname//': mode list index out of range')
   end if
   ! Get the physprop index for the requested mode
   idx = mlist%idx_props(mode_idx)
   if (present(opticstype))  call physprop_get(idx, opticstype=opticstype)
   if (present(extpsw))      call physprop_get(idx, extpsw=extpsw)
   if (present(abspsw))      call physprop_get(idx, abspsw=abspsw)
   if (present(asmpsw))      call physprop_get(idx, asmpsw=asmpsw)
   if (present(absplw))      call physprop_get(idx, absplw=absplw)
   if (present(refrtabsw))   call physprop_get(idx, refrtabsw=refrtabsw)
   if (present(refitabsw))   call physprop_get(idx, refitabsw=refitabsw)
   if (present(refrtablw))   call physprop_get(idx, refrtablw=refrtablw)
   if (present(refitablw))   call physprop_get(idx, refitablw=refitablw)
   if (present(ncoef))       call physprop_get(idx, ncoef=ncoef)
   if (present(prefr))       call physprop_get(idx, prefr=prefr)
   if (present(prefi))       call physprop_get(idx, prefi=prefi)
   if (present(sigmag))      call physprop_get(idx, sigmag=sigmag)
   if (present(dgnum))       call physprop_get(idx, dgnum=dgnum)
   if (present(dgnumlo))     call physprop_get(idx, dgnumlo=dgnumlo)
   if (present(dgnumhi))     call physprop_get(idx, dgnumhi=dgnumhi)
   if (present(rhcrystal))   call physprop_get(idx, rhcrystal=rhcrystal)
   if (present(rhdeliques))  call physprop_get(idx, rhdeliques=rhdeliques)
end subroutine rad_aer_get_mode_props
Call graph
rad_aer_get_mode_props calls endrun, physprop_get
constructor calls rad_aer_get_mode_props
icenuc_size_wght_arr calls rad_aer_get_mode_props
icenuc_size_wght_val calls rad_aer_get_mode_props, icenuc_size_wght
rebin_bulk_fluxes calls rad_aer_get_mode_props
modal_aerosol_properties calls constructor
nuclice_get_numdens calls icenuc_size_wght