rad_aer_get_info_by_bin – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rad_aer_get_info_by_bin Subroutine
42 statements
Source File
public subroutine rad_aer_get_info_by_bin(list_idx, m_idx, bin_name, num_name, num_name_cw, mmr_name, mmr_name_cw, nspec)
Uses
cam_logfile
radiative_aerosol_definitions
cam_abortutils
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: list_idx
integer, intent(in) :: m_idx
character(len=*), intent(out), optional :: bin_name
character(len=32), intent(out), optional :: num_name
character(len=32), intent(out), optional :: num_name_cw
character(len=32), intent(out), optional :: mmr_name
character(len=32), intent(out), optional :: mmr_name_cw
integer, intent(out), optional :: nspec
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: mm
integer, private :: nbins
type(binlist_t), private, pointer :: s_list
character(len=*), private, parameter :: subname = 'rad_aer_get_info_by_bin'
Source Code
subroutine rad_aer_get_info_by_bin(list_idx, m_idx, &
   bin_name, num_name, num_name_cw, mmr_name, mmr_name_cw, nspec)
   use cam_abortutils, only: endrun
   use cam_logfile,    only: iulog
   use radiative_aerosol_definitions, only: binlist_t, sectional_aerosol_list, bins
   ! Return info about CARMA aerosol lists
   ! Arguments
   integer,                     intent(in)  :: list_idx    ! index of the climate or a diagnostic list
   integer,                     intent(in)  :: m_idx       ! index of bin in the specified list
   character(len=*),  optional, intent(out) :: bin_name
   character(len=32), optional, intent(out) :: num_name    ! name of interstitial number mixing ratio
   character(len=32), optional, intent(out) :: num_name_cw ! name of cloud borne number mixing ratio
   character(len=32), optional, intent(out) :: mmr_name    ! name of interstitial mass mixing ratio
   character(len=32), optional, intent(out) :: mmr_name_cw ! name of cloud borne mass mixing ratio
   integer,           optional, intent(out) :: nspec       ! number of species in the mode
   ! Local variables
   type(binlist_t), pointer :: s_list ! local pointer to mode list of interest
   integer          :: nbins
   integer          :: mm
   character(len=*), parameter :: subname = 'rad_aer_get_info_by_bin'
   !-----------------------------------------------------------------------------
   s_list => sectional_aerosol_list(list_idx)
   ! check for valid mode index
   nbins = s_list%nbins
   if (m_idx < 1 .or. m_idx > nbins) then
      write(iulog,*) subname//': ERROR - invalid bin index: ', m_idx
      call endrun(subname//': ERROR - invalid bin index')
   end if
   ! get index into the mode definition object
   mm = s_list%idx(m_idx)
   ! number of species in the mode
   if (present(nspec)) then
      nspec = bins%comps(mm)%nspec
   endif
   ! bin name
   if (present(bin_name)) then
      bin_name = bins%names(m_idx)
   end if
   ! name of interstitial number mixing ratio
   if (present(num_name)) then
      num_name = bins%comps(mm)%camname_num_a
   endif
   ! name of cloud borne number mixing ratio
   if (present(num_name_cw)) then
      num_name_cw = bins%comps(mm)%camname_num_c
   endif
   ! name of interstitial mass mixing ratio
   if (present(mmr_name)) then
      mmr_name = bins%comps(mm)%camname_mass_a
   endif
   ! name of cloud borne mass mixing ratio
   if (present(mmr_name_cw)) then
      mmr_name_cw = bins%comps(mm)%camname_mass_c
   endif
end subroutine rad_aer_get_info_by_bin
Call graph
rad_aer_get_info_by_bin calls endrun
amb_mmr_name calls rad_aer_get_info_by_bin
amb_num_name calls rad_aer_get_info_by_bin
ambient_total_bin_mmr calls rad_aer_get_info_by_bin
aqu_gain_binfraction calls rad_aer_get_info_by_bin
bin_name calls rad_aer_get_info_by_bin
constructor calls rad_aer_get_info_by_bin, bin_name
dry_volume calls rad_aer_get_info_by_bin
get calls rad_aer_get_info_by_bin
get_ambient_num calls rad_aer_get_info_by_bin
get_cldbrne_num calls rad_aer_get_info_by_bin
hetfrz_size_wght calls rad_aer_get_info_by_bin
hygroscopicity calls rad_aer_get_info_by_bin
icenuc_size_wght_arr calls rad_aer_get_info_by_bin
mmr_names calls rad_aer_get_info_by_bin
num_names calls rad_aer_get_info_by_bin
scav_diam calls rad_aer_get_info_by_bin, get
wet_diameter calls rad_aer_get_info_by_bin
wet_volume calls rad_aer_get_info_by_bin
carma_aerosol_properties calls constructor
get_states calls get_ambient_num, get_cldbrne_num
rebin_bulk_fluxes calls bin_mass, get
water_volume calls dry_volume, wet_volume