rebin_bulk_fluxes – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rebin_bulk_fluxes Subroutine
65 statements
Source File
private subroutine rebin_bulk_fluxes(self, bulk_type, dep_fluxes, diam_edges, bulk_fluxes, error_code, error_string)
Uses
shr_infnan_mod
Type Bound
modal_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_properties), intent(in) :: self
character(len=*), intent(in) :: bulk_type
real(kind=r8), intent(in) :: dep_fluxes(:)
real(kind=r8), intent(in) :: diam_edges(:)
real(kind=r8), intent(out) :: bulk_fluxes(:)
integer, intent(out) :: error_code
character(len=*), intent(out) :: error_string
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: dns_dst
logical, private :: has_type
integer, private :: k
integer, private :: l
integer, private :: m
real(kind=r8), private :: massfrac_bin(size(bulk_fluxes))
integer, private :: mm
character(len=aero_name_len), private :: modetype
real(kind=r8), private :: mtotal
real(kind=r8), private :: mtype
integer, private :: nbulk
real(kind=r8), private :: ntot
real(kind=r8), private :: ntype
real(kind=r8), private, parameter :: onethrd = 1._r8/3._r8
real(kind=r8), private :: sigma_g
character(len=aero_name_len), private :: spectype
real(kind=r8), private, parameter :: sqrtwo = sqrt(2._r8)
real(kind=r8), private :: tmp
logical, private :: type_not_found
real(kind=r8), private :: vmd
Source Code
  subroutine rebin_bulk_fluxes(self, bulk_type, dep_fluxes, diam_edges, bulk_fluxes, &
                               error_code, error_string)
    use shr_infnan_mod, only: nan => shr_infnan_nan, assignment(=)
    class(modal_aerosol_properties), intent(in) :: self
    character(len=*),intent(in) :: bulk_type       ! aerosol type to rebin
    real(r8), intent(in) :: dep_fluxes(:)          ! kg/m2
    real(r8), intent(in) :: diam_edges(:)          ! meters
    real(r8), intent(out) :: bulk_fluxes(:)        ! kg/m2
    integer,  intent(out) :: error_code            ! error code (0 if no error)
    character(len=*), intent(out) :: error_string  ! error string
    real(r8) :: dns_dst ! kg/m3
    real(r8) :: sigma_g, vmd, tmp, massfrac_bin(size(bulk_fluxes))
    real(r8) :: Ntype, Mtype, Mtotal, Ntot
    integer :: k,l,m,mm, nbulk
    logical :: has_type, type_not_found
    character(len=aero_name_len) :: spectype
    character(len=aero_name_len) :: modetype
    real(r8), parameter :: sqrtwo = sqrt(2._r8)
    real(r8), parameter :: onethrd = 1._r8/3._r8
    error_code = 0
    error_string = ' '
    type_not_found = .true.
    nbulk = size(bulk_fluxes)
    bulk_fluxes(:) = 0.0_r8
    do m = 1,self%nbins()
       Mtype = 0._r8
       Mtotal = 0._r8
       mm = self%indexer(m,0)
       Ntot = dep_fluxes(mm) ! #/m2
       has_type = .false.
       do l = 1,self%nspecies(m)
          mm = self%indexer(m,l)
          call self%get(m,l, spectype=spectype, density=dns_dst) ! kg/m3
          if (spectype==bulk_type) then
             Mtype = dep_fluxes(mm) ! kg/m2
             has_type = .true.
             type_not_found = .false.
          end if
          Mtotal = Mtotal + dep_fluxes(mm) ! kg/m2
       end do
       mode_has_type: if (has_type) then
          call rad_aer_get_info(self%list_idx_, m, mode_type=modetype)
          if (Ntot>1.e-40_r8 .and. Mtype>1.e-40_r8 .and. Mtotal>1.e-40_r8) then
             call rad_aer_get_mode_props(self%list_idx_, m, sigmag=sigma_g)
             tmp = sqrtwo*log(sigma_g)
             ! type number concentration
             Ntype = Ntot * Mtype/Mtotal ! #/m2
             ! volume median diameter (meters)
             vmd = (6._r8*Mtype/(pi*Ntype*dns_dst))**onethrd * exp(1.5_r8*(log(sigma_g))**2)
             massfrac_bin = 0._r8
             do k = 1,nbulk
                massfrac_bin(k) = 0.5_r8*( erf((log(diam_edges(k+1)/vmd))/tmp) &
                                - erf((log(diam_edges(k  )/vmd))/tmp) )
                bulk_fluxes(k) = bulk_fluxes(k) + massfrac_bin(k) * Mtype
             end do
             if (debug) then
                if (abs(1._r8-sum(massfrac_bin)) > 1.e-6_r8) then
                   write(*,*) 'rebin_bulk_fluxes WARNING mode-num, massfrac_bin, sum(massfrac_bin) = ', &
                        m, massfrac_bin, sum(massfrac_bin)
                end if
             end if
          end if
       end if mode_has_type
    end do
    if (type_not_found) then
       bulk_fluxes(:) = nan
       error_code = 1
       write(error_string,*) 'aerosol_properties::rebin_bulk_fluxes ERROR : ',trim(bulk_type),' not found'
    end if
  end subroutine rebin_bulk_fluxes
Call graph
rebin_bulk_fluxes calls nspecies, get_nbins, get, indexer, rad_aer_get_mode_props, rad_aer_get_info
get calls rad_aer_get_info, endrun, rad_aer_get_props
rad_aer_get_mode_props calls endrun, physprop_get
rad_aer_get_props calls rad_aer_get_mam_props_by_idx, rad_aer_get_props_by_idx
rad_aer_get_mam_props_by_idx calls endrun, physprop_get
rad_aer_get_props_by_idx calls endrun, physprop_get