rebin_bulk_fluxes – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
rebin_bulk_fluxes Subroutine
69 statements
Source File
private subroutine rebin_bulk_fluxes(self, bulk_type, dep_fluxes, diam_edges, bulk_fluxes, error_code, error_string)
Type Bound
carma_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_properties), intent(in) :: self
character(len=*), intent(in) :: bulk_type
real(kind=r8), intent(in) :: dep_fluxes(:)
real(kind=r8), intent(in) :: diam_edges(:)
real(kind=r8), intent(out) :: bulk_fluxes(:)
integer, intent(out) :: error_code
character(len=*), intent(out) :: error_string
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: diam
real(kind=r8), private :: frac
integer, private :: i
integer, private :: l
integer, private :: m
real(kind=r8), private :: mass
real(kind=r8), private :: mflx
real(kind=r8), private :: mflx_tot
integer, private :: mm
integer, private :: n_bulk_bins
real(kind=r8), private :: rho
character(len=aero_name_len), private :: spectype
logical, private :: type_not_found
Functions
function bin_mass(bin_ndx)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: bin_ndx
Return Value real(kind=r8)
Source Code
  subroutine rebin_bulk_fluxes(self, bulk_type, dep_fluxes, diam_edges, bulk_fluxes, &
                               error_code, error_string)
    class(carma_aerosol_properties), intent(in) :: self
    character(len=*),intent(in) :: bulk_type ! aerosol type to rebin
    real(r8), intent(in) :: dep_fluxes(:) ! kg/m2/sec
    real(r8), intent(in) :: diam_edges(:) ! meters
    real(r8), intent(out) :: bulk_fluxes(:) ! kg/m2/sec
       integer,  intent(out) :: error_code            ! error code (0 if no error)
       character(len=*), intent(out) :: error_string  ! error string
    real(r8) :: mflx, mflx_tot
    real(r8) :: rho, mass, frac, diam
    integer :: i, m,l,mm
    integer :: n_bulk_bins
    character(len=aero_name_len) :: spectype
    logical :: type_not_found
    error_code = 0
    error_string = ' '
    n_bulk_bins = size(bulk_fluxes)
    bulk_fluxes(:) = 0._r8
    type_not_found = .true.
    bin_loop: do m = 1,self%nbins()
       mflx_tot = 0._r8
       mflx = 0._r8
       species: do l = 1,self%nmasses(m)
          mm = self%indexer(m,l)
          if (l>self%nspecies(m)) then
             ! use mass flux for the entire bin (concentration element) if available
             ! -- override the total summed below
             mflx_tot = dep_fluxes(mm)
          else
             ! this sums up the total assuming all species are transported
             mflx_tot = mflx_tot + dep_fluxes(mm)
             call self%get(m,l,spectype=spectype)
             if (spectype==bulk_type) then
                ! get mass flux and density of the specified type
                mflx = dep_fluxes(mm)
                call self%get(m,l,density=rho) ! kg/m3
                type_not_found = .false.
             end if
          end if
       end do species
       if (mflx>0._r8 .and. mflx_tot>0._r8) then
          ! mass flux fraction
          frac = mflx/mflx_tot
          ! mass of the specified aerosol type
          mass = frac * bin_mass(m) ! kg
          ! diameter in meters
          diam = 2._r8*((0.75_r8*mass/pi/rho)**onethird)
          ! add the flux to the corresponding bulk bin
          blk_loop: do i = 1,n_bulk_bins-1
             if (diam>diam_edges(i) .and. diam<=diam_edges(i+1)) then
                bulk_fluxes(i) = bulk_fluxes(i) + mflx
                exit blk_loop
             end if
          end do blk_loop
       endif
    end do bin_loop
    if (type_not_found) then
       bulk_fluxes(:) = nan
       error_code = 1
       write(error_string,*) 'aerosol_properties::rebin_bulk_fluxes ERROR : ',trim(bulk_type),' not found'
    end if
  contains
    !---------------------------------------------------------------
    ! get mass of the specified bin in kg -- could be done at init time ...
    !---------------------------------------------------------------
    real(r8) function bin_mass(bin_ndx) ! (kg)
      use carma_intr, only: carma_get_bin_rmass, carma_get_group_by_name
      integer, intent(in) :: bin_ndx
      character(len=aero_name_len) :: bin_name, shortname
      integer :: ibin, igroup, rc, nchr
      real(r8) :: rmass
      call rad_aer_get_info_by_bin(self%list_idx_, bin_ndx, bin_name=bin_name)
      nchr = len_trim(bin_name)-2
      shortname = bin_name(:nchr)
      call carma_get_group_by_name(shortname, igroup, rc)
      read(bin_name(nchr+1:),*) ibin
      call carma_get_bin_rmass(igroup, ibin, rmass, rc)
      bin_mass = rmass * 1.e-3_r8 ! g->kg
    end function bin_mass
  end subroutine rebin_bulk_fluxes
Call graph
rebin_bulk_fluxes calls bin_mass, nmasses, nspecies, get, get_nbins, indexer
get calls nspecies, endrun, rad_aer_get_bin_props_by_idx, rad_aer_get_info_by_bin, rad_aer_get_info_by_bin_spec
rad_aer_get_bin_props_by_idx calls endrun, physprop_get
rad_aer_get_info_by_bin calls endrun
rad_aer_get_info_by_bin_spec calls endrun