refractive_index_lw – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
refractive_index_lw Function
23 statements
Source File
private function refractive_index_lw(self, ncol, ilev, ibin, iwav, aero_props) result(crefin)
Type Bound
aerosol_state
Arguments
Type Intent Optional Attributes Name
class(aerosol_state), intent(in) :: self
integer, intent(in) :: ncol
integer, intent(in) :: ilev
integer, intent(in) :: ibin
integer, intent(in) :: iwav
class(aerosol_properties), intent(in) :: aero_props
Return Value complex(kind=r8), (ncol)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: icol
integer, private :: ispec
real(kind=r8), private :: specdens
real(kind=r8), private, pointer :: specmmr(:,:)
complex(kind=r8), private, pointer :: specrefindex(:)
real(kind=r8), private :: vol(ncol)
Source Code
  function refractive_index_lw(self, ncol, ilev, ibin, iwav, aero_props) result(crefin)
    class(aerosol_state), intent(in) :: self
    integer, intent(in) :: ncol   ! number of columes
    integer, intent(in) :: ilev   ! level index
    integer, intent(in) :: ibin   ! bin index
    integer, intent(in) :: iwav   ! wave length index
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    complex(r8) :: crefin(ncol) ! complex refractive index
    real(r8), pointer :: specmmr(:,:) ! species mass mixing ratio
    complex(r8), pointer :: specrefindex(:)     ! species refractive index
    real(r8) :: specdens              ! species density (kg/m3)
    integer :: ispec, icol
    real(r8) :: vol(ncol)
    crefin(:ncol) = (0._r8, 0._r8)
    do ispec = 1, aero_props%nspecies(ibin)
       call self%get_ambient_mmr(species_ndx=ispec, bin_ndx=ibin, mmr=specmmr)
       call aero_props%get(ibin, ispec, density=specdens,  refindex_lw=specrefindex)
       do icol = 1, ncol
          vol(icol) = specmmr(icol,ilev)/specdens
          crefin(icol) = crefin(icol) + vol(icol)*specrefindex(iwav)
       end do
    end do
  end function refractive_index_lw
Call graph
refractive_index_lw calls get, get_ambient_mmr, nspecies
lw_props calls refractive_index_lw