scav_diam – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
scav_diam Function
26 statements
Source File
private function scav_diam(self, bin_ndx) result(diam)
Uses
carma_intr
Type Bound
carma_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
Return Value real(kind=r8)
Calls
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: bin_name
integer, private :: ibin
integer, private :: igroup
integer, private :: ispec
real(kind=r8), private :: mass
integer, private :: nchr
integer, private :: rc
real(kind=r8), private :: rho
character(len=aero_name_len), private :: shortname
character(len=32), private :: spectype
Source Code
  function scav_diam(self, bin_ndx) result(diam)
    use carma_intr, only: carma_get_bin_rmass
    use carma_intr, only: carma_get_group_by_name
    class(carma_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx  ! bin number
    real(r8) :: diam ! cm
    real(r8) :: mass   ! the bin mass (g)
    real(r8) :: rho    ! density (kg/m3)
    integer :: ispec
    character(len=32) :: spectype
    character(len=aero_name_len) :: bin_name, shortname
    integer :: igroup, ibin, rc, nchr
    call rad_aer_get_info_by_bin(self%list_idx_, bin_ndx, bin_name=bin_name)
    nchr = len_trim(bin_name)-2
    shortname = bin_name(:nchr)
    call carma_get_group_by_name(shortname, igroup, rc)
    read(bin_name(nchr+1:),*) ibin
    call carma_get_bin_rmass(igroup, ibin, mass, rc)
    do ispec = 1, self%nspecies(bin_ndx)
       call self%species_type(bin_ndx,ispec, spectype)
       if (trim(spectype) == 'sulfate') then
          call self%get(bin_ndx,ispec,density=rho)
       end if
    end do
    ! specdens kg/m3 to g/cm3, convert from radius to diameter
    diam = 2._r8*((0.75_r8*mass / pi  / (1.0e-3_r8*rho))**onethird)
  end function scav_diam
Call graph
scav_diam calls carma_get_bin_rmass, carma_get_group_by_name, nspecies, get, rad_aer_get_info_by_bin, species_type
get calls nspecies, rad_aer_get_info_by_bin, endrun, rad_aer_get_bin_props_by_idx, rad_aer_get_info_by_bin_spec
rad_aer_get_info_by_bin calls endrun
species_type calls rad_aer_get_info_by_bin_spec
rad_aer_get_bin_props_by_idx calls endrun, physprop_get
rad_aer_get_info_by_bin_spec calls endrun