sox_cldaero_create_obj – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
sox_cldaero_create_obj Function
52 statements
Source File
public function sox_cldaero_create_obj(cldfrc, qcw, lwc, cfact, ncol) result(conc_obj)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), intent(in) :: cldfrc(:,:)
real(kind=r8), intent(in) :: qcw(:,:,:)
real(kind=r8), intent(in) :: lwc(:,:)
real(kind=r8), intent(in) :: cfact(:,:)
integer, intent(in) :: ncol
Return Value type(cldaero_conc_t), pointer
Calls
Variables
Type Visibility Attributes Name Initial
integer, private :: i
integer, private :: k
integer, private :: l
integer, private :: m
integer, private :: mm
logical, private :: mode7
integer, private :: ntot_amode
character(len=32), private :: spectype
Source Code
  function sox_cldaero_create_obj(cldfrc, qcw, lwc, cfact, ncol) result( conc_obj )
    real(r8), intent(in) :: cldfrc(:,:)
    real(r8), intent(in) :: qcw(:,:,:)
    real(r8), intent(in) :: lwc(:,:)
    real(r8), intent(in) :: cfact(:,:)
    integer,  intent(in) :: ncol
    type(cldaero_conc_t), pointer :: conc_obj
    character(len=32) :: spectype
    integer :: l,m
    integer :: i,k,mm, ntot_amode
    logical :: mode7
    conc_obj => cldaero_allocate()
    if (aero_props%model_is('BAM')) then
       ! no cloud-borne aerosols
       conc_obj%xlwc(:ncol,:) = lwc(:ncol,:)*cfact(:ncol,:) ! cloud water L(water)/L(air)
       return
    end if
    if (aero_props%model_is('MAM')) then
       ntot_amode = aero_props%nbins()
       if (ntot_amode /= 7) then
          conc_obj%so4_fact = 1._r8
       end if
    end if
    do k = 1,pver
       do i = 1,ncol
          if(cldfrc(i,k)>0._r8) then
             conc_obj%xlwc(i,k) = lwc(i,k) *cfact(i,k) ! cloud water L(water)/L(air)
             conc_obj%xlwc(i,k) = conc_obj%xlwc(i,k) / cldfrc(i,k) ! liquid water in the cloudy fraction of cell
          else
             conc_obj%xlwc(i,k) = 0._r8
          endif
       enddo
    enddo
    conc_obj%no3c(:,:) = 0._r8
    conc_obj%nh4c(:,:) = 0._r8
    conc_obj%so4c(:,:) = 0._r8
    do k = 1,pver
       do i = 1,ncol
          do m = 1, aero_props%nbins()
            do l = 1, aero_props%nspecies(m)
               mm = aero_props%indexer(m,l)
               call  aero_props%get(m,l, spectype=spectype)
               if (trim(spectype) == 'sulfate') then
                  conc_obj%so4c(i,k) = conc_obj%so4c(i,k) +  qcw(i,k,mm)
               end if
               if (trim(spectype) == 'ammonium') then
                  conc_obj%nh4c(i,k) = conc_obj%nh4c(i,k) +  qcw(i,k,mm)
               end if
            end do
          end do
       end do
    end do
  end function sox_cldaero_create_obj
Call graph
sox_cldaero_create_obj calls cldaero_allocate, get, model_is, nh4c, no3c, nspecies, get_nbins, indexer, so4c, xlwc