sox_cldaero_update – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
sox_cldaero_update Subroutine
211 statements
Source File
public subroutine sox_cldaero_update(aero_state, ncol, dtime, mbar, pdel, press, tfld, cldnum, cldfrc, cfact, xlwc, delso4_hprxn, xh2so4, xso4, xso4_init, nh3g, xnh3, xnh4c, xmsa, xso2, xh2o2, qcw, qin, aqso4, aqh2so4, aqso4_h2o2, aqso4_o3, aqso4_h2o2_3d, aqso4_o3_3d)
Uses
physics_types
when cloud is present
when cloud is present
Arguments
Type Intent Optional Attributes Name
class(aerosol_state), intent(in) :: aero_state
integer, intent(in) :: ncol
real(kind=r8), intent(in) :: dtime
real(kind=r8), intent(in) :: mbar(:,:)
real(kind=r8), intent(in) :: pdel(:,:)
real(kind=r8), intent(in) :: press(:,:)
real(kind=r8), intent(in) :: tfld(:,:)
real(kind=r8), intent(in) :: cldnum(:,:)
real(kind=r8), intent(in) :: cldfrc(:,:)
real(kind=r8), intent(in) :: cfact(:,:)
real(kind=r8), intent(in) :: xlwc(:,:)
real(kind=r8), intent(in) :: delso4_hprxn(:,:)
real(kind=r8), intent(in) :: xh2so4(:,:)
real(kind=r8), intent(in) :: xso4(:,:)
real(kind=r8), intent(in) :: xso4_init(:,:)
real(kind=r8), intent(in) :: nh3g(:,:)
real(kind=r8), intent(in) :: xnh3(:,:)
real(kind=r8), intent(in) :: xnh4c(:,:)
real(kind=r8), intent(in) :: xmsa(:,:)
real(kind=r8), intent(in) :: xso2(:,:)
real(kind=r8), intent(in) :: xh2o2(:,:)
real(kind=r8), intent(inout) :: qcw(:,:,:)
real(kind=r8), intent(inout) :: qin(:,:,:)
real(kind=r8), intent(out) :: aqso4(:,:)
real(kind=r8), intent(out) :: aqh2so4(:,:)
real(kind=r8), intent(out) :: aqso4_h2o2(:)
real(kind=r8), intent(out) :: aqso4_o3(:)
real(kind=r8), intent(out), optional :: aqso4_h2o2_3d(:,:)
real(kind=r8), intent(out), optional :: aqso4_o3_3d(:,:)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: delnh3
real(kind=r8), private :: delnh4
real(kind=r8), private :: delso4_ox(ncol,pver)
real(kind=r8), private :: dmsadt_gasuptk
real(kind=r8), private :: dmsadt_gasuptk_tomsa
real(kind=r8), private :: dmsadt_gasuptk_toso4
real(kind=r8), private :: dqdt
real(kind=r8), private :: dqdt_aq
real(kind=r8), private :: dqdt_aqh2so4(ncol,pver,ncnst_tot)
real(kind=r8), private :: dqdt_aqhprxn(ncol,pver)
real(kind=r8), private :: dqdt_aqo3rxn(ncol,pver)
real(kind=r8), private :: dqdt_aqso4(ncol,pver,ncnst_tot)
real(kind=r8), private :: dqdt_wr
real(kind=r8), private :: dso4dt_aqrxn
real(kind=r8), private :: dso4dt_gasuptk
real(kind=r8), private :: dso4dt_hprxn
real(kind=r8), private :: faqgain_msa(nbins,ncol,pver)
real(kind=r8), private :: faqgain_so4(nbins,ncol,pver)
real(kind=r8), private :: fwetrem
integer, private :: i
integer, private :: k
integer, private :: l
integer, private :: m
integer, private :: mm
real(kind=r8), private :: mw_so4
integer, private :: n
character(len=32), private :: specname
character(len=32), private :: spectype
real(kind=r8), private :: uptkrate
real(kind=r8), private :: xl
Source Code
  subroutine sox_cldaero_update( aero_state, &
       ncol, dtime, mbar, pdel, press, tfld, cldnum, cldfrc, cfact, xlwc, &
       delso4_hprxn, xh2so4, xso4, xso4_init, nh3g, xnh3, xnh4c, xmsa, xso2, xh2o2, qcw, qin, &
       aqso4, aqh2so4, aqso4_h2o2, aqso4_o3, aqso4_h2o2_3d, aqso4_o3_3d)
    use physics_types, only: physics_state
    ! args
    class(aerosol_state), intent(in) :: aero_state
    integer,  intent(in) :: ncol
    real(r8), intent(in) :: dtime ! time step (sec)
    real(r8), intent(in) :: mbar(:,:) ! mean wet atmospheric mass ( amu )
    real(r8), intent(in) :: pdel(:,:)
    real(r8), intent(in) :: press(:,:)
    real(r8), intent(in) :: tfld(:,:)
    real(r8), intent(in) :: cldnum(:,:)
    real(r8), intent(in) :: cldfrc(:,:)
    real(r8), intent(in) :: cfact(:,:)
    real(r8), intent(in) :: xlwc(:,:)
    real(r8), intent(in) :: delso4_hprxn(:,:)
    real(r8), intent(in) :: xh2so4(:,:)
    real(r8), intent(in) :: xso4(:,:)
    real(r8), intent(in) :: xso4_init(:,:)
    real(r8), intent(in) :: nh3g(:,:)
    real(r8), intent(in) :: xnh3(:,:)
    real(r8), intent(in) :: xnh4c(:,:)
    real(r8), intent(in) :: xmsa(:,:)
    real(r8), intent(in) :: xso2(:,:)
    real(r8), intent(in) :: xh2o2(:,:)
    real(r8), intent(inout) :: qcw(:,:,:) ! cloud-borne aerosol (vmr)
    real(r8), intent(inout) :: qin(:,:,:) ! xported species ( vmr )
    real(r8), intent(out) :: aqso4(:,:)                   ! aqueous phase chemistry
    real(r8), intent(out) :: aqh2so4(:,:)                 ! aqueous phase chemistry
    real(r8), intent(out) :: aqso4_h2o2(:)                ! SO4 aqueous phase chemistry due to H2O2 (kg/m2)
    real(r8), intent(out) :: aqso4_o3(:)                  ! SO4 aqueous phase chemistry due to O3 (kg/m2)
    real(r8), intent(out), optional :: aqso4_h2o2_3d(:,:)                ! SO4 aqueous phase chemistry due to H2O2 (kg/m2)
    real(r8), intent(out), optional :: aqso4_o3_3d(:,:)                  ! SO4 aqueous phase chemistry due to O3 (kg/m2)
    ! local vars ...
    real(r8) :: dqdt_aqso4(ncol,pver,ncnst_tot), &
         dqdt_aqh2so4(ncol,pver,ncnst_tot), &
         dqdt_aqhprxn(ncol,pver), dqdt_aqo3rxn(ncol,pver)
    real(r8) :: faqgain_msa(nbins,ncol,pver), faqgain_so4(nbins,ncol,pver)
    real(r8) :: delso4_ox(ncol,pver)
    real(r8) :: delnh3, delnh4
    real(r8) :: dso4dt_aqrxn, dso4dt_hprxn, &
         dso4dt_gasuptk, dmsadt_gasuptk, &
         dmsadt_gasuptk_tomsa, dmsadt_gasuptk_toso4, &
         dqdt_aq, dqdt_wr, dqdt
    real(r8) :: fwetrem, uptkrate
    integer :: l, m, n, mm
    integer :: i,k
    real(r8) :: xl
    real(r8) :: mw_so4
    character(len=32) :: spectype
    character(len=32) :: specname
    ! make sure dqdt is zero initially, for budgets
    dqdt_aqso4(:,:,:) = 0.0_r8
    dqdt_aqh2so4(:,:,:) = 0.0_r8
    dqdt_aqhprxn(:,:) = 0.0_r8
    dqdt_aqo3rxn(:,:) = 0.0_r8
    aqso4 = 0.0_r8
    aqh2so4 = 0.0_r8
    aqso4_h2o2 = 0.0_r8
    aqso4_o3 = 0.0_r8
    delso4_ox = 0.0_r8
    ! Avoid double counting in-cloud sulfur oxidation when running with
    ! GEOS-Chem. If running with GEOS-Chem then sulfur oxidation
    ! is performed internally to GEOS-Chem. Here, we just return to the
    ! parent routine and thus we do not apply tendencies calculated by MAM.
    if ( cam_chempkg_is('geoschem_mam4') ) return
    where (cldfrc(:ncol,:) >= 1.0e-5_r8)
       delso4_ox(:ncol,:) = xso4(:ncol,:) - xso4_init(:ncol,:)
    end where
    !-------------------------------------------------------------------------
    ! Compute factors for partitioning aerosol mass gains among bins / modes.
    ! The factors are proportional to the activated particle MR for each
    ! bin, which is the MR of cloud drops "associated with" the mode
    ! thus we are assuming the cloud drop size is independent of the
    ! associated aerosol mode properties
    call aero_state%aqu_gain_binfraction(aero_props, 'sulfate', qcw, delso4_ox, faqgain_so4)
    if (has_msa) call aero_state%aqu_gain_binfraction(aero_props, 'msa', qcw, delso4_ox, faqgain_msa)
    lev_loop: do k = 1,pver
       col_loop: do i = 1,ncol
          cloud: if (cldfrc(i,k) >= 1.0e-5_r8) then
             xl = xlwc(i,k)
             if (xl .ge. 1.e-8_r8) then !! when cloud is present
                if (id_nh3>0) then
                   delnh3 = nh3g(i,k) - xnh3(i,k)
                   delnh4 = - delnh3
                endif
                ! faqgain_msa(n) = fraction of total msa_c gain going to mode n
                uptkrate = cldaero_uptakerate( xl, cldnum(i,k), cfact(i,k), cldfrc(i,k), tfld(i,k),  press(i,k) )
                ! average uptake rate over dtime
                uptkrate = (1.0_r8 - exp(-min(100._r8,dtime*uptkrate))) / dtime
                ! dso4dt_gasuptk = so4_c tendency from h2so4 gas uptake (mol/mol/s)
                ! dmsadt_gasuptk = msa_c tendency from msa gas uptake (mol/mol/s)
                dso4dt_gasuptk = xh2so4(i,k) * uptkrate
                if (has_msa) then
                   dmsadt_gasuptk = xmsa(i,k) * uptkrate
                else
                   dmsadt_gasuptk = 0.0_r8
                end if
                ! if no modes have msa aerosol, then "rename" scavenged msa gas to so4
                if (has_msa) then
                   dmsadt_gasuptk_toso4 = 0.0_r8
                   dmsadt_gasuptk_tomsa = dmsadt_gasuptk
                else
                   ! no MSA
                   dmsadt_gasuptk_tomsa = 0.0_r8
                   dmsadt_gasuptk_toso4 = dmsadt_gasuptk
                end if
                !-----------------------------------------------------------------------
                ! now compute TMR tendencies
                ! this includes the above aqueous so2 chemistry AND
                ! the uptake of highly soluble aerosol precursor gases (h2so4, msa, ...)
                ! AND the wetremoval of dissolved, unreacted so2 and h2o2
                dso4dt_aqrxn = (delso4_ox(i,k) + delso4_hprxn(i,k)) / dtime
                dso4dt_hprxn = delso4_hprxn(i,k) / dtime
                ! fwetrem = fraction of in-cloud-water material that is wet removed
                ! fwetrem = max( 0.0_r8, (1.0_r8-exp(-min(100._r8,dtime*clwlrat(i,k)))) )
                fwetrem = 0.0_r8 ! don't have so4 & msa wet removal here
                ! compute TMR tendencies for so4 and msa aerosol-in-cloud-water
                do m = 1, aero_props%nbins()
                   do l = 1, aero_props%nspecies(m)
                      mm = aero_props%indexer(m,l)
                      call  aero_props%get(m,l, spectype=spectype)
                      if (trim(spectype) == 'sulfate') then
                         dqdt_aqso4(i,k,mm) = faqgain_so4(m,i,k)*dso4dt_aqrxn*cldfrc(i,k)
                         dqdt_aqh2so4(i,k,mm) = faqgain_so4(m,i,k)* &
                              (dso4dt_gasuptk + dmsadt_gasuptk_toso4)*cldfrc(i,k)
                         dqdt_aq = dqdt_aqso4(i,k,mm) + dqdt_aqh2so4(i,k,mm)
                         dqdt_wr = -fwetrem*dqdt_aq
                         dqdt = dqdt_aq + dqdt_wr
                         qcw(i,k,mm) = qcw(i,k,mm) + dqdt*dtime
                      end if
                      if (trim(spectype) == 'msa') then
                         dqdt_aq = faqgain_msa(m,i,k)*dmsadt_gasuptk_tomsa*cldfrc(i,k)
                         dqdt_wr = -fwetrem*dqdt_aq
                         dqdt = dqdt_aq + dqdt_wr
                         qcw(i,k,mm) = qcw(i,k,mm) + dqdt*dtime
                      end if
                      if (trim(spectype) == 'ammonium') then
                         if (delnh4 > 0.0_r8) then
                            dqdt_aq = faqgain_so4(m,i,k)*delnh4/dtime*cldfrc(i,k)
                            dqdt = dqdt_aq
                            qcw(i,k,mm) = qcw(i,k,mm) + dqdt*dtime
                         else
                            dqdt = (qcw(i,k,mm)/max(xnh4c(i,k),1.0e-35_r8)) &
                                 *delnh4/dtime*cldfrc(i,k)
                            qcw(i,k,mm) = qcw(i,k,mm) + dqdt*dtime
                         endif
                      end if
                   end do
                end do
                ! For gas species, tendency includes
                ! reactive uptake to cloud water that essentially transforms the gas to
                ! a different species. Wet removal associated with this is applied
                ! to the "new" species (e.g., so4_c) rather than to the gas.
                ! wet removal of the unreacted gas that is dissolved in cloud water.
                ! Need to multiply both these parts by cldfrc
                ! h2so4 (g) & msa (g)
                qin(i,k,id_h2so4) = qin(i,k,id_h2so4) - dso4dt_gasuptk * dtime * cldfrc(i,k)
                if (has_msa) qin(i,k,id_msa) = qin(i,k,id_msa) - dmsadt_gasuptk * dtime * cldfrc(i,k)
                ! so2 -- the first order loss rate for so2 is frso2_c*clwlrat(i,k)
                ! fwetrem = max( 0.0_r8, (1.0_r8-exp(-min(100._r8,dtime*frso2_c*clwlrat(i,k)))) )
                fwetrem = 0.0_r8 ! don't include so2 wet removal here
                dqdt_wr = -fwetrem*xso2(i,k)/dtime*cldfrc(i,k)
                dqdt_aq = -dso4dt_aqrxn*cldfrc(i,k)
                dqdt = dqdt_aq + dqdt_wr
                qin(i,k,id_so2) = qin(i,k,id_so2) + dqdt * dtime
                ! h2o2 -- the first order loss rate for h2o2 is frh2o2_c*clwlrat(i,k)
                ! fwetrem = max( 0.0_r8, (1.0_r8-exp(-min(100._r8,dtime*frh2o2_c*clwlrat(i,k)))) )
                fwetrem = 0.0_r8 ! don't include h2o2 wet removal here
                dqdt_wr = -fwetrem*xh2o2(i,k)/dtime*cldfrc(i,k)
                dqdt_aq = -dso4dt_hprxn*cldfrc(i,k)
                dqdt = dqdt_aq + dqdt_wr
                qin(i,k,id_h2o2) = qin(i,k,id_h2o2) + dqdt * dtime
                ! NH3
                if (id_nh3>0) then
                   dqdt_aq = delnh3/dtime*cldfrc(i,k)
                   dqdt = dqdt_aq
                   qin(i,k,id_nh3) = qin(i,k,id_nh3) + dqdt * dtime
                endif
                ! for SO4 from H2O2/O3 budgets
                dqdt_aqhprxn(i,k) = dso4dt_hprxn*cldfrc(i,k)
                dqdt_aqo3rxn(i,k) = (dso4dt_aqrxn - dso4dt_hprxn)*cldfrc(i,k)
             endif !! when cloud is present
          endif cloud
       enddo col_loop
    enddo lev_loop
    !==============================================================
    ! ... Update the mixing ratios
    !==============================================================
    do k = 1,pver
       do n = 1, aero_props%nbins()
          do l = 1, aero_props%nspecies(n)
             mm = aero_props%indexer(n,l)
             call  aero_props%get(n,l, spectype=spectype)
             if (trim(spectype) == 'sulfate') then
                qcw(:ncol,k,mm) = MAX(qcw(:ncol,k,mm), small_value )
             end if
             if (trim(spectype) == 'msa') then
                qcw(:ncol,k,mm) = MAX(qcw(:ncol,k,mm), small_value )
             end if
             if (trim(spectype) == 'ammonium') then
                qcw(:ncol,k,mm) = MAX(qcw(:ncol,k,mm), small_value )
             end if
          end do
       end do
       qin(:ncol,k,id_so2)   = MAX( qin(:ncol,k,id_so2),   small_value )
       qin(:ncol,k,id_h2o2)  = MAX( qin(:ncol,k,id_h2o2),  small_value )
       qin(:ncol,k,id_h2so4) = MAX( qin(:ncol,k,id_h2so4), small_value )
       if ( id_msa > 0 ) qin(:ncol,k,id_msa) = MAX( qin(:ncol,k,id_msa), small_value )
       if ( id_nh3 > 0 ) qin(:ncol,k,id_nh3) = MAX( qin(:ncol,k,id_nh3), small_value )
    end do
    ! diagnostics
    mw_so4 = -huge(1._r8)
    do n = 1, aero_props%nbins()
       ! while looking through all species, only dqdt_aqso4 from sulfates  is gt zero
       do l = 1, aero_props%nspecies(n)
          mm = aero_props%indexer(n,l)
          call aero_props%get(n,l, spectype=spectype, specname=specname)
          if (trim(spectype) == 'sulfate') then
             call aero_props%get(n,l, spec_mw=mw_so4)
             aqso4(:,n)=0._r8
             do k=1,pver
                do i=1,ncol
                   aqso4(i,n)=aqso4(i,n)+dqdt_aqso4(i,k,mm)*mw_so4/mbar(i,k) &
                        *pdel(i,k)/gravit ! kg/m2/s
                enddo
             enddo
             aqh2so4(:,n)=0._r8
             do k=1,pver
                do i=1,ncol
                   aqh2so4(i,n)=aqh2so4(i,n)+dqdt_aqh2so4(i,k,mm)*mw_so4/mbar(i,k) &
                        *pdel(i,k)/gravit ! kg/m2/s
                enddo
             enddo
          end if
       end do
    end do
    aqso4_h2o2(:) = 0._r8
    do k=1,pver
       do i=1,ncol
          aqso4_h2o2(i)=aqso4_h2o2(i)+dqdt_aqhprxn(i,k)*mw_so4/mbar(i,k) &
               *pdel(i,k)/gravit ! kg SO4 /m2/s
       enddo
    enddo
    if (present(aqso4_h2o2_3d)) then
       aqso4_h2o2_3d(:,:) = 0._r8
       do k=1,pver
          do i=1,ncol
             aqso4_h2o2_3d(i,k)=dqdt_aqhprxn(i,k)*mw_so4/mbar(i,k) &
                  *pdel(i,k)/gravit ! kg SO4 /m2/s
          enddo
       enddo
    end if
    aqso4_o3(:)=0._r8
    do k=1,pver
       do i=1,ncol
          aqso4_o3(i)=aqso4_o3(i)+dqdt_aqo3rxn(i,k)*mw_so4/mbar(i,k) &
               *pdel(i,k)/gravit ! kg SO4 /m2/s
       enddo
    enddo
    if (present(aqso4_o3_3d)) then
       aqso4_o3_3d(:,:)=0._r8
       do k=1,pver
          do i=1,ncol
             aqso4_o3_3d(i,k)=dqdt_aqo3rxn(i,k)*mw_so4/mbar(i,k) &
                  *pdel(i,k)/gravit ! kg SO4 /m2/s
          enddo
       enddo
    end if
  end subroutine sox_cldaero_update
Call graph
sox_cldaero_update calls aqu_gain_binfraction, cam_chempkg_is, cldaero_uptakerate, get, nspecies, get_nbins, indexer