species_type – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
species_type Subroutine
7 statements
Source File
private subroutine species_type(self, bin_ndx, species_ndx, spectype)
Type Bound
modal_aerosol_properties
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_properties), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: species_ndx
character(len=*), intent(out) :: spectype
Calls
Called by
Source Code
  subroutine species_type(self, bin_ndx, species_ndx, spectype)
    class(modal_aerosol_properties), intent(in) :: self
    integer, intent(in) :: bin_ndx           ! bin number
    integer, intent(in) :: species_ndx       ! species number
    character(len=*), intent(out) :: spectype ! species type
    call rad_aer_get_info(self%list_idx_, bin_ndx, species_ndx, spec_type=spectype)
  end subroutine species_type
Call graph
species_type calls rad_aer_get_info
constructor calls species_type
hetfrz_species calls species_type
icenuc_updates_mmr calls species_type
icenuc_updates_num calls species_type
min_mass_mean_rad calls species_type
modal_aerosol_properties calls constructor