update_bin – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
update_bin Subroutine
21 statements
Source File
private subroutine update_bin(self, bin_ndx, col_ndx, lyr_ndx, delmmr_sum, delnum_sum, tnd_ndx, dtime, tend)
Type Bound
modal_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
integer, intent(in) :: col_ndx
integer, intent(in) :: lyr_ndx
real(kind=r8), intent(in) :: delmmr_sum
real(kind=r8), intent(in) :: delnum_sum
integer, intent(in) :: tnd_ndx
real(kind=r8), intent(in) :: dtime
real(kind=r8), intent(inout) :: tend(:,:,:)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, pointer :: amb_num(:,:)
real(kind=r8), private, pointer :: cld_num(:,:)
Source Code
  subroutine update_bin( self, bin_ndx, col_ndx, lyr_ndx, delmmr_sum, delnum_sum, tnd_ndx, dtime, tend )
    class(modal_aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    integer, intent(in) :: col_ndx                ! column index
    integer, intent(in) :: lyr_ndx                ! vertical layer index
    real(r8),intent(in) :: delmmr_sum             ! mass mixing ratio change summed over all species in bin
    real(r8),intent(in) :: delnum_sum             ! number mixing ratio change summed over all species in bin
    integer, intent(in) :: tnd_ndx                ! tendency index
    real(r8),intent(in) :: dtime                  ! time step size (sec)
    real(r8),intent(inout) :: tend(:,:,:)         ! tendency
    real(r8), pointer :: amb_num(:,:)
    real(r8), pointer :: cld_num(:,:)
    call self%get_ambient_num(bin_ndx, amb_num)
    call self%get_cldbrne_num(bin_ndx, cld_num)
    ! if there is no bin mass compute updates/tendencies for bin number
    ! -- apply the total number change to bin number
    if (tnd_ndx>0) then
       tend(col_ndx,lyr_ndx,tnd_ndx) = -delnum_sum/dtime
    else
       amb_num(col_ndx,lyr_ndx) = amb_num(col_ndx,lyr_ndx) - delnum_sum
    end if
    ! apply the total number change to bin number
    cld_num(col_ndx,lyr_ndx) = cld_num(col_ndx,lyr_ndx) + delnum_sum
  end subroutine update_bin
Call graph
update_bin calls get_ambient_num, get_cldbrne_num
get_ambient_num calls rad_cnst_get_mode_num
get_cldbrne_num calls rad_cnst_get_mode_num