watact_mfactor – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
watact_mfactor Subroutine
48 statements
Source File
private subroutine watact_mfactor(self, bin_ndx, species_type, ncol, nlev, aero_props, rho, wact_factor)
Type Bound
aerosol_state
Arguments
Type Intent Optional Attributes Name
class(aerosol_state), intent(in) :: self
integer, intent(in) :: bin_ndx
character(len=*), intent(in) :: species_type
integer, intent(in) :: ncol
integer, intent(in) :: nlev
class(aerosol_properties), intent(in) :: aero_props
real(kind=r8), intent(in) :: rho(:,:)
real(kind=r8), intent(out) :: wact_factor(:,:)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, pointer :: aer_mmr(:,:)
real(kind=r8), private :: aer_numdens(ncol,nlev)
real(kind=r8), private :: awcam(ncol,nlev)
real(kind=r8), private :: awfacm(ncol,nlev)
real(kind=r8), private, pointer :: bin_num(:,:)
integer, private :: ispc
character(len=aero_name_len), private :: spectype
real(kind=r8), private :: tot1_mmr(ncol,nlev)
real(kind=r8), private :: tot2_mmr(ncol,nlev)
Source Code
  subroutine watact_mfactor(self, bin_ndx,  species_type, ncol, nlev, aero_props, rho, wact_factor)
    class(aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_ndx                ! bin number
    character(len=*), intent(in) :: species_type  ! species type
    integer, intent(in) :: ncol                   ! number of columns
    integer, intent(in) :: nlev                   ! number of vertical levels
    class(aerosol_properties), intent(in) :: aero_props ! aerosol properties object
    real(r8), intent(in) :: rho(:,:)              ! air density (kg m-3)
    real(r8), intent(out) :: wact_factor(:,:)     ! water activity factor -- density*(1.-(OC+BC)/(OC+BC+SO4)) [mug m-3]
    real(r8), pointer :: aer_mmr(:,:)
    real(r8), pointer :: bin_num(:,:)
    real(r8) :: tot2_mmr(ncol,nlev)
    real(r8) :: tot1_mmr(ncol,nlev)
    real(r8) :: aer_numdens(ncol,nlev)
    integer :: ispc
    character(len=aero_name_len) :: spectype
    real(r8) :: awcam(ncol,nlev)          ! mass density [mug m-3]
    real(r8) :: awfacm(ncol,nlev)         ! mass factor ! (OC+BC)/(OC+BC+SO4)
    tot2_mmr = 0.0_r8
    tot1_mmr = 0.0_r8
    if (aero_props%soluble(bin_ndx)) then
       do ispc = 1, aero_props%nspecies(bin_ndx)
          call aero_props%species_type(bin_ndx, ispc, spectype)
          if (trim(spectype)=='black-c' .or. trim(spectype)=='p-organic' .or. trim(spectype)=='s-organic') then
             call self%get_ambient_mmr(species_ndx=ispc, bin_ndx=bin_ndx, mmr=aer_mmr)
             tot2_mmr(:ncol,:) = tot2_mmr(:ncol,:) + aer_mmr(:ncol,:)
          end if
          if (trim(spectype)=='sulfate') then
             call self%get_ambient_mmr(species_ndx=ispc, bin_ndx=bin_ndx, mmr=aer_mmr)
             tot1_mmr(:ncol,:) = tot1_mmr(:ncol,:) + aer_mmr(:ncol,:)
          end if
       end do
    end if
    tot1_mmr(:ncol,:) = tot1_mmr(:ncol,:) + tot2_mmr(:ncol,:)
    call self%get_amb_species_numdens(bin_ndx, ncol, nlev, species_type, aero_props, rho, aer_numdens) ! #/cm3
    call self%get_ambient_num(bin_ndx, bin_num) ! #/kg
    where(bin_num(:ncol,:)>0._r8)
       awcam(:ncol,:) = ((aer_numdens(:ncol,:)*per_m3/bin_num(:ncol,:)) * tot1_mmr(:ncol,:)) * kg2mug  ! [mug m-3]
    elsewhere
       awcam(:ncol,:) = 0._r8
    end where
    where(tot1_mmr(:ncol,:)>0)
       awfacm(:ncol,:) = tot2_mmr(:ncol,:) / tot1_mmr(:ncol,:)
    elsewhere
       awfacm(:ncol,:) = 0._r8
    end where
    wact_factor(:ncol,:) = awcam(:ncol,:)*(1._r8-awfacm(:ncol,:))
  end subroutine watact_mfactor
Call graph
watact_mfactor calls get_ambient_mmr, get_ambient_num, nspecies, get_amb_species_numdens, soluble, species_type
get_amb_species_numdens calls get_ambient_num, hetfrz_size_wght, icenuc_type_wght_base
icenuc_type_wght_base calls get_ambient_mmr, nspecies, species_type, get_cldbrne_mmr