water_uptake – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
water_uptake Subroutine
50 statements
Source File
private subroutine water_uptake(self, aero_props, bin_idx, ncol, nlev, dgnumwet, qaerwat)
Uses
modal_aero_calcsize
modal_aero_wateruptake
Type Bound
modal_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: bin_idx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
real(kind=r8), intent(out) :: dgnumwet(ncol,nlev)
real(kind=r8), intent(out) :: qaerwat(ncol,nlev)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private, pointer :: dgnumdry_m(:,:,:)
real(kind=r8), private, pointer :: dgnumwet_m(:,:,:)
real(kind=r8), private, pointer :: drymass_m(:,:,:)
real(kind=r8), private, pointer :: dryrad_m(:,:,:)
real(kind=r8), private, pointer :: dryvol_m(:,:,:)
real(kind=r8), private, pointer :: hygro_m(:,:,:)
integer, private :: istat
real(kind=r8), private, pointer :: naer_m(:,:,:)
integer, private :: nmodes
real(kind=r8), private, pointer :: qaerwat_m(:,:,:)
real(kind=r8), private, pointer :: so4dryvol_m(:,:,:)
real(kind=r8), private, pointer :: wetdens_m(:,:,:)
Source Code
  subroutine water_uptake(self, aero_props, bin_idx, ncol, nlev, dgnumwet, qaerwat)
    use modal_aero_wateruptake, only: modal_aero_wateruptake_dr
    use modal_aero_calcsize,    only: modal_aero_calcsize_diag
    class(modal_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props
    integer, intent(in) :: bin_idx              ! bin number
    integer, intent(in) :: ncol                 ! number of columns
    integer, intent(in) :: nlev                 ! number of levels
    real(r8),intent(out) :: dgnumwet(ncol,nlev) ! aerosol wet diameter (m)
    real(r8),intent(out) :: qaerwat(ncol,nlev)  ! aerosol water concentration (g/g)
    integer :: istat, nmodes
    real(r8), pointer :: dgnumdry_m(:,:,:) ! number mode dry diameter for all modes
    real(r8), pointer :: dgnumwet_m(:,:,:) ! number mode wet diameter for all modes
    real(r8), pointer :: qaerwat_m(:,:,:)  ! aerosol water (g/g) for all modes
    real(r8), pointer :: wetdens_m(:,:,:)  !
    real(r8), pointer :: hygro_m(:,:,:)  !
    real(r8), pointer :: dryvol_m(:,:,:)  !
    real(r8), pointer :: dryrad_m(:,:,:)  !
    real(r8), pointer :: drymass_m(:,:,:)  !
    real(r8), pointer :: so4dryvol_m(:,:,:)  !
    real(r8), pointer :: naer_m(:,:,:)  !
    nmodes = aero_props%nbins()
    if (self%list_idx_ == 0) then
       ! water uptake and wet radius for the climate list has already been calculated
       call pbuf_get_field(self%pbuf, pbuf_get_index('DGNUMWET'), dgnumwet_m)
       call pbuf_get_field(self%pbuf, pbuf_get_index('QAERWAT'),  qaerwat_m)
       dgnumwet(:ncol,:nlev) = dgnumwet_m(:ncol,:nlev,bin_idx)
       qaerwat (:ncol,:nlev) =  qaerwat_m(:ncol,:nlev,bin_idx)
    else
       ! If doing a diagnostic calculation then need to calculate the wet radius
       ! and water uptake for the diagnostic modes
       allocate(dgnumdry_m(ncol,nlev,nmodes),  dgnumwet_m(ncol,nlev,nmodes), &
                qaerwat_m(ncol,nlev,nmodes),   wetdens_m(ncol,nlev,nmodes), &
                hygro_m(ncol,nlev,nmodes),     dryvol_m(ncol,nlev,nmodes), &
                dryrad_m(ncol,nlev,nmodes),    drymass_m(ncol,nlev,nmodes),  &
                so4dryvol_m(ncol,nlev,nmodes), naer_m(ncol,nlev,nmodes), stat=istat)
       if (istat > 0) then
          dgnumwet = -huge(1._r8)
          qaerwat = -huge(1._r8)
          return
       end if
       call modal_aero_calcsize_diag(self%state, self%pbuf, aero_props, self, dgnumdry_m, hygro_m, &
                                     dryvol_m, dryrad_m, drymass_m, so4dryvol_m, naer_m)
       call modal_aero_wateruptake_dr(self%state, self%pbuf, aero_props, self, dgnumdry_m, dgnumwet_m, &
                                      qaerwat_m, wetdens_m, hygro_m, dryvol_m, dryrad_m, &
                                      drymass_m, so4dryvol_m, naer_m)
       dgnumwet(:ncol,:nlev) = dgnumwet_m(:ncol,:nlev,bin_idx)
       qaerwat (:ncol,:nlev) =  qaerwat_m(:ncol,:nlev,bin_idx)
       deallocate(dgnumdry_m)
       deallocate(dgnumwet_m)
       deallocate(qaerwat_m)
       deallocate(wetdens_m)
       deallocate(hygro_m)
       deallocate(dryvol_m)
       deallocate(dryrad_m)
       deallocate(drymass_m)
       deallocate(so4dryvol_m)
       deallocate(naer_m)
    endif
  end subroutine water_uptake
Call graph
water_uptake calls modal_aero_calcsize_diag, modal_aero_wateruptake_dr, pbuf_get_field, pbuf_get_index, get_nbins
water_volume calls water_uptake
wet_volume calls water_volume