water_volume – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
water_volume Function
16 statements
Source File
private function water_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
Type Bound
carma_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: bin_idx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
Return Value real(kind=r8), (ncol,nlev)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: dryvol(ncol,nlev)
real(kind=r8), private :: wetvol(ncol,nlev)
Source Code
  function water_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
    class(carma_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props
    integer, intent(in) :: bin_idx   ! bin number
    integer, intent(in) :: ncol      ! number of columns
    integer, intent(in) :: nlev      ! number of levels
    real(r8) :: vol(ncol,nlev)       ! m3/kg
    real(r8) :: wetvol(ncol,nlev)
    real(r8) :: dryvol(ncol,nlev)
    wetvol = self%wet_volume(aero_props, bin_idx, ncol, nlev)
    dryvol = self%dry_volume(aero_props, bin_idx, ncol, nlev)
    vol(:ncol,:) = wetvol(:ncol,:) - dryvol(:ncol,:)
    where (vol<0._r8)
       vol = 0._r8
    end where
  end function water_volume
Call graph
water_volume calls dry_volume, wet_volume
dry_volume calls carma_get_dry_radius, carma_get_group_by_name, carma_get_number, rad_aer_get_info_by_bin
wet_volume calls carma_get_group_by_name, carma_get_number, carma_get_wet_radius, rad_aer_get_info_by_bin
rad_aer_get_info_by_bin calls endrun