water_volume – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
water_volume Function
15 statements
Source File
private function water_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
Type Bound
modal_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: bin_idx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
Return Value real(kind=r8), (ncol,nlev)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: dgnumwet(ncol,nlev)
real(kind=r8), private :: qaerwat(ncol,nlev)
Source Code
  function water_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
    class(modal_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props
    integer, intent(in) :: bin_idx   ! bin number
    integer, intent(in) :: ncol      ! number of columns
    integer, intent(in) :: nlev      ! number of levels
    real(r8) :: vol(ncol,nlev)       ! m3/kg
    real(r8) :: dgnumwet(ncol,nlev)
    real(r8) :: qaerwat(ncol,nlev)
    call self%water_uptake(aero_props, bin_idx, ncol, nlev, dgnumwet, qaerwat)
    vol(:ncol,:nlev) = qaerwat(:ncol,:nlev)*rh2odens
    where (vol<0._r8)
       vol = 0._r8
    end where
  end function water_volume
Call graph
water_volume calls water_uptake
water_uptake calls modal_aero_calcsize_diag, modal_aero_wateruptake_dr, pbuf_get_field, pbuf_get_index, get_nbins
wet_volume calls water_volume