wet_diameter – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
wet_diameter Function
18 statements
Source File
private function wet_diameter(self, bin_idx, ncol, nlev) result(diam)
Type Bound
carma_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_state), intent(in) :: self
integer, intent(in) :: bin_idx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
Return Value real(kind=r8), (ncol,nlev)
Calls
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: bin_name
integer, private :: ibin
integer, private :: igroup
integer, private :: nchr
real(kind=r8), private :: radwet(pcols,pver)
wet radius (m)
integer, private :: rc
real(kind=r8), private :: rhowet(pcols,pver)
wet density (kg/m3)
character(len=aero_name_len), private :: shortname
Source Code
  function wet_diameter(self, bin_idx, ncol, nlev) result(diam)
    class(carma_aerosol_state), intent(in) :: self
    integer, intent(in) :: bin_idx   ! bin number
    integer, intent(in) :: ncol      ! number of columns
    integer, intent(in) :: nlev      ! number of levels
    real(r8) :: diam(ncol,nlev)
    real(r8) :: radwet(pcols,pver)   !! wet radius (m)
    real(r8) :: rhowet(pcols,pver)   !! wet density (kg/m3)
    character(len=aero_name_len) :: bin_name, shortname
    integer :: igroup, ibin, rc, nchr
    call rad_aer_get_info_by_bin(0, bin_idx, bin_name=bin_name)
    nchr = len_trim(bin_name)-2
    shortname = bin_name(:nchr)
    call  carma_get_group_by_name(shortname, igroup, rc)
    read(bin_name(nchr+1:),*) ibin
    call carma_get_wet_radius(self%state, igroup, ibin, radwet, rhowet, rc)
    diam(:ncol,:nlev) = 2._r8*radwet(:ncol,:nlev)
  end function wet_diameter
Call graph
wet_diameter calls carma_get_group_by_name, carma_get_wet_radius, rad_aer_get_info_by_bin
rad_aer_get_info_by_bin calls endrun