wet_volume – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
wet_volume Function
22 statements
Source File
private function wet_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
Type Bound
carma_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(carma_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: bin_idx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
Return Value real(kind=r8), (ncol,nlev)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=aero_name_len), private :: bin_name
integer, private :: ibin
integer, private :: igroup
integer, private :: nchr
real(kind=r8), private :: nmr(pcols,pver)
real(kind=r8), private :: radwet(pcols,pver)
integer, private :: rc
real(kind=r8), private :: rhowet(pcols,pver)
character(len=aero_name_len), private :: shortname
Source Code
  function wet_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
    class(carma_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props
    integer, intent(in) :: bin_idx   ! bin number
    integer, intent(in) :: ncol      ! number of columns
    integer, intent(in) :: nlev      ! number of levels
    real(r8) :: vol(ncol,nlev)       ! m3/kg
    real(r8) :: radwet(pcols,pver)   ! wet radius (m)
    real(r8) :: rhowet(pcols,pver)   ! wet density (kg/m3)
    real(r8) :: nmr(pcols,pver)      ! number mixing ratio (#/kg)
    character(len=aero_name_len) :: bin_name, shortname
    integer :: igroup, ibin, rc, nchr
    call rad_aer_get_info_by_bin(0, bin_idx, bin_name=bin_name)
    nchr = len_trim(bin_name)-2
    shortname = bin_name(:nchr)
    call  carma_get_group_by_name(shortname, igroup, rc)
    read(bin_name(nchr+1:),*) ibin
    vol = 0._r8
    call carma_get_wet_radius(self%state, igroup, ibin, radwet, rhowet, rc)
    call carma_get_number(self%state, igroup, ibin, nmr, rc)
    vol(:ncol,:) = four_thirds_pi * (radwet(:ncol,:)**3) * nmr(:ncol,:) ! units = m3/kg
  end function wet_volume
Call graph
wet_volume calls carma_get_group_by_name, carma_get_number, carma_get_wet_radius, rad_aer_get_info_by_bin
rad_aer_get_info_by_bin calls endrun
water_volume calls wet_volume