wet_volume – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
wet_volume Function
13 statements
Source File
private function wet_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
Type Bound
modal_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(modal_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: bin_idx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
Return Value real(kind=r8), (ncol,nlev)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=r8), private :: dryvol(ncol,nlev)
real(kind=r8), private :: watervol(ncol,nlev)
Source Code
  function wet_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
    class(modal_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props
    integer, intent(in) :: bin_idx   ! bin number
    integer, intent(in) :: ncol      ! number of columns
    integer, intent(in) :: nlev      ! number of levels
    real(r8) :: vol(ncol,nlev)       ! m3/kg
    real(r8) :: dryvol(ncol,nlev)
    real(r8) :: watervol(ncol,nlev)
    dryvol = self%dry_volume(aero_props, bin_idx, ncol, nlev)
    watervol = self%water_volume(aero_props, bin_idx, ncol, nlev)
    vol = watervol + dryvol
  end function wet_volume
Call graph
wet_volume calls dry_volume, water_volume
dry_volume calls get, nspecies, get_ambient_mmr
water_volume calls water_uptake
get_ambient_mmr calls rad_cnst_get_aer_mmr
water_uptake calls modal_aero_calcsize_diag, modal_aero_wateruptake_dr, pbuf_get_field, pbuf_get_index, get_nbins