wet_volume – CAM Abstract Aerosol Interface
Draft preview — work in progress. This is not official CAM documentation. Content may be incomplete or inaccurate and is subject to change without notice.
wet_volume Function
9 statements
Source File
public function wet_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
Type Bound
bulk_aerosol_state
Arguments
Type Intent Optional Attributes Name
class(bulk_aerosol_state), intent(in) :: self
class(aerosol_properties), intent(in) :: aero_props
integer, intent(in) :: bin_idx
integer, intent(in) :: ncol
integer, intent(in) :: nlev
Return Value real(kind=r8), (ncol,nlev)
Calls
Source Code
  function wet_volume(self, aero_props, bin_idx, ncol, nlev) result(vol)
    class(bulk_aerosol_state), intent(in) :: self
    class(aerosol_properties), intent(in) :: aero_props
    integer, intent(in) :: bin_idx   ! bin number
    integer, intent(in) :: ncol      ! number of columns
    integer, intent(in) :: nlev      ! number of levels
    real(r8) :: vol(ncol,nlev)       ! m3/kg
    vol = self%dry_volume(aero_props, bin_idx, ncol, nlev) &
        + self%water_volume(aero_props, bin_idx, ncol, nlev)
  end function wet_volume
Call graph
wet_volume calls dry_volume, water_volume
dry_volume calls get, get_ambient_mmr
get_ambient_mmr calls rad_cnst_get_aer_mmr